### ISSUE TITLE
can't use DateSent >= YYYY-MM-DD

### ISSUE THREAD

**Issue by mikz** [twilio/twilio-ruby#120]
Twilio docs mention that you can use DateSent `>=` and `<=` for querying the messages.

Unfortunately I don't see a way how this could be used with twilio-ruby client.

At least I would expect `client.messages.list('DateSent>=2014-11-05')` to work (as it would be quite impossible to specify as a hash). But that tries to serialize it as a hash.

`client.account.messages.list({'' => 'DateSent<=2014-11-04'})` is close, but it prefixes it with `=` so it does not work anyway.

**Comment by carlosdp** [comment]
for future reference, you can use those special characters in ruby hash keys as such:

```ruby
yesterday = client.account.messages.list(:'DateSent>=' => '2014-11-04')
```

Yea, you have to use the pre-1.9 hash rockets, which is ugly. We are working on a solution for the future!

**Comment by siannopollo** [comment]
I just came across this issue too, and I should mention that the last comment by @carlosdp has a typo in the example. The `=` **_should not_** be in the hash key. It should really be:
```
yesterday = client.account.messages.list(:'DateSent>' => '2014-11-04')
```

**Comment by VicenteFava** [comment]
```
@client.api.account.messages.list(
        to: to,
        from: from,
        date_sent_after: date_sent_after,
        limit: limit
    )
```
