### ISSUE TITLE
twilio test credentials do not work for sending sms‏ - throws exception “Resource not accessible with Test Account Credentials”

### ISSUE THREAD

**Issue by doug7410** [twilio/twilio-ruby#121]
I am building an application for sending sms messages. I'm following example 1 for test sending an sms in the documentation.

Example on Twilio site:
https://www.twilio.com/docs/api/rest/test-credentials#test-sms-messages

```ruby
# Get your Account Sid and Auth Token from twilio.com/user/account
account_sid = 'ACb62e32327e8ec258781341a039e65c46'
auth_token = '{{ auth_token }}'
@client = Twilio::REST::Client.new account_sid, auth_token

sms = @client.account.sms.messages.create(:body => "All in the game, yo",
    :to => "+14108675309",
    :from => "+15005550006")
puts sms.body
https://www.twilio.com/docs/api/rest/test-credentials#test-sms-messages
```

Here is what my code looks like

```ruby
client = Twilio::REST::Client.new(ENV['twilio_account_sid'], ENV['twilio_auth_token'])

response = client.account.sms.messages.create({ 
:from => '+15005550006', #valid phone number for testing
:to => '<<a valid number>>', 
:body => "Some message" 
})
```
When I send to a valid number with my test credentials and this valid test from number (15005550006) I get an exception saying

`"Resource not accessible with Test Account Credentials"`

I don't see what I'm doing differently than the example.

I also tested out their API with my test credentials on Postman REST client and it works fine there, so I'm pretty sure this is an issue with the gem. When I use my production credentials and my actual twilio phone number I have no problems.

**Comment by ursuleacv** [comment]
Most probably you have a GET request after your POST to send the sms.

I was getting the same error and after I removed the get request

    $message = $client->account->messages->get($sms->sid);

is working as well.

**Comment by carlosdp** [comment]
This was likely a result of an outdated version of the library being used. Closing the issue unless there are any updates.
