### ISSUE TITLE
Retrieving Sent Messages 

### ISSUE THREAD

**Issue by em-gazelle** [twilio/twilio-ruby#127]
I'd like to fix the code [(found here)] (https://github.com/twilio/twilio-ruby/blob/56a56c374b0462e6b03d1029a6d53a0b877f0785/docs/usage/messages.rst#) on how to retrieve sent messages.

The current code is:

    @client.account.messages.each do |message|

which returns an error of:

    undefined method `each' for #<Twilio::REST::Messages:0xa3abd6c>

From [Twilio's docs] (https://www.twilio.com/docs/api/rest/message#list-get), the correct code is:

    @client.account.messages.list.each do |message|

**Comment by philnash** [comment]
Hey Emma,

Thanks for the report, that appears to be an older version of the docs there. The latest can be found [here](https://github.com/twilio/twilio-ruby/blob/master/docs/usage/messages.rst#retrieving-sent-messages) and uses the most up to date way of getting messages, like this:

```ruby
@client.messages.list.each do |message|
    puts message.body
end
```

I did notice that there are some unclosed blocks on that page though, I will fix that up now!
