### ISSUE TITLE
Generating twiml doesn't create attributes in camelcase 

### ISSUE THREAD

**Issue by samjbmason** [twilio/twilio-ruby#130]
Im using twilio-ruby and when I try to create this twiml response 
```
  Twilio::TwiML::Response.new do |r|
      r.Enqueue "Wait", wait_url: "###################, wait_url_method: 'GET'
    end.text
```

The output looks like this 
```
<?xml version="1.0" encoding="UTF-8"?>
<Response>
<Enqueue wait_url="###########" wait_url_method="GET">Wait</Enqueue>  
</Response>
```

I assumed it would convert the underscores to camelcase but it doesnt and trying to type it in in camelcase converts it all to lower case

**Comment by philnash** [comment]
Hey Sam,

As far as I can see within the code, the `Twilio::TwiML::Response` is really just a wrapping of a builder object from the builder gem. So, whilst for now that does mean that it won't convert snake case attributes to camel case it should mean that if you put your attributes in camel case, it will pass them through to the XML output like that.

I ran a quick test with your example and this is what I got:

```ruby
Twilio::TwiML::Response.new do |r|
  r.Enqueue "Wait", waitUrl: "###################", waitUrlMethod: 'GET'
end.text
=> "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Response><Enqueue waitUrl=\"###################\" waitUrlMethod=\"GET\">Wait</Enqueue></Response>"
```

As you can see, the attributes came through camel cased for me. Can you just check that my example above works the same way for you?

Thanks!

**Comment by samjbmason** [comment]
Hey Phil,
Apologies, it all my fault my browser was automatically formatting the text. You are correct, just writing it out as camel case works.

Thanks for helping man, hope you had a good holiday
