### ISSUE TITLE
Undefined method call from TwilioWebhookAuthentication

### ISSUE THREAD

**Issue by samjbmason** [twilio/twilio-ruby#131]
I have been trying to use the TwilioWebHookAuthentication and keep getting this error `NoMethodError: undefined method `bytesize' for nil:NilClass`

Im using ruby 2.2.0 and SInatra, this is what my config.ru looks like

```ruby
require 'bundler'
Bundler.require
Dotenv.load

require './app'

use Rack::TwilioWebhookAuthentication, ENV['TWILIO_AUTH_TOKEN'], '/incoming-call'
run Incoming


```

**Comment by skimbrel** [comment]
Are you sure TWILIO_AUTH_TOKEN is set in your process environment?

**Comment by samjbmason** [comment]
Yeah its set up in my `.env` file

**Comment by skimbrel** [comment]
OK. Can you get a full stacktrace? That would make tracking down the source of the error easier.

**Comment by samjbmason** [comment]
Yeah sure here it is
```ruby
NoMethodError: undefined method `bytesize' for nil:NilClass
~/Sites/incoming/vendor/bundle/gems/twilio-ruby-3.14.2/lib/twilio-ruby/util/request_validator.rb:27:in `secure_compare'
~/Sites/incoming/vendor/bundle/gems/twilio-ruby-3.14.2/lib/twilio-ruby/util/request_validator.rb:12:in `validate'
~/Sites/incoming/vendor/bundle/gems/twilio-ruby-3.14.2/lib/rack/twilio_webhook_authentication.rb:33:in `call'
~/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:155:in `handle'
~/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:109:in `rescue in block (2 levels) in start'
~/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:106:in `block (2 levels) in start'
~/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:96:in `each'
~/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:96:in `block in start'
~/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:76:in `loop'
~/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:76:in `start'
~/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:12:in `run'
~/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/bin/nack_worker:4:in `<main>'
```

**Comment by skimbrel** [comment]
Are you seeing this error when Twilio sends you a TwiML request? Can you dump out the Rack request object and make sure it has the X-Twilio-Signature header? I’m wondering whether this nack thing you’re using is actually getting all of the request headers sent over in a way that Rack understands.

**Comment by samjbmason** [comment]
I'm seeing it when I visit the action through a normal browser, so yes it should throw an error but it seems to stop it from loading up in the first place. 

—

**Comment by skimbrel** [comment]
OH. Duh. We already merged a fix for this from #124. Update to the latest twilio-ruby and you should be all set!

**Comment by samjbmason** [comment]
I'm pretty sure I am already running the latest version. 

—

**Comment by skimbrel** [comment]
Yeah, my bad. I realized we hadn’t done the release yet. Stay tuned...

**Comment by samjbmason** [comment]
Ah right, any knowledge about timings on when you maybe will release the update? 


Also any idea on issue #130


—

**Comment by skimbrel** [comment]
3.14.3 is live on rubygems now. Will take a look at #130 early next week, most likely.
