### ISSUE TITLE
TaskRouterClient missing

### ISSUE THREAD

**Issue by bouk** [twilio/twilio-ruby#139]
@skimbrel it seems https://github.com/twilio/twilio-ruby/commit/f6d4e669635fc05e785ea8224bbf8b6ebf0c4fef didn't actually add the code for the new TaskRouter API

**Comment by skimbrel** [comment]
Wow, I'm bad at git, it seems. I'll actually do the merge and release 3.15.1, stand by.

**Comment by skimbrel** [comment]
Okay, 3.15.1 is out. Give that a shot?

**Comment by bouk** [comment]
:+1:
