### ISSUE TITLE
Documentation for SMS TwiML Verb Attributes

### ISSUE THREAD

**Issue by monfresh** [twilio/twilio-ruby#140]
Hi,

I'm trying to build a Rails app that can respond to SMS, then provide options to the user, such as "type 1 for this, type 2 for that", and then be able to respond again accordingly, and continue having an interactive "conversation", but only through SMS, not voice.

I can't seem to find any documentation for doing this, and I tried adding the `action` attributes to the `Message`, but that didn't work:
```ruby
twiml = Twilio::TwiML::Response.new do |r|
  r.Message action: '/locations/process_zip', method: 'GET'
end
```
How can I use SMS to guide a user through an interactive session, similar to the `Gather` method for voice?

Thanks!

**Comment by philnash** [comment]
Hey,

SMS doesn't act like Gather I'm afraid. However, you can track a user's journey through an interactive session like this. We do allow you to track SMS conversations via a session though, like a normal session with a user visiting from a browser.

There's a [quickstart example in the Twilio documentation](https://www.twilio.com/docs/quickstart/ruby/sms/tracking-conversations) that should tell you a bit more.

Let me know if that helps!

**Comment by monfresh** [comment]
Thanks! I was able to get something basic working.
