### ISSUE TITLE
TaskRouter Functionality

### ISSUE THREAD

**Issue by adamwiggall** [twilio/twilio-ruby#141]
Is there any estimated date for adding the TaskRouter API interface?

Thanks

**Comment by makaimc** [comment]
@adamwiggall Adam! how are you sir? looks like TR was pulled into the gem yesterday. having issues with the latest version?

**Comment by adamwiggall** [comment]
Matt!

Very well thank you, and loving TR so far.

I must have been staring at the screen for too long. Ignore me, I'll update the gem and stop bothering you all on here.

Hope you are well and hopefully going to be seeing you at Signal?

Sorry to raise a non issue and thanks for the prompt response.

**Comment by makaimc** [comment]
No problem! I'm going to close this ticket down. Make sure to check out the latest Ruby post by my colleague Phil at https://www.twilio.com/blog/2015/02/creating-a-priority-queue-for-your-call-centre-with-taskrouter.html

I'll definitely be at Signal. I'll shoot you an email and follow up.
