### ISSUE TITLE
NoMethodError for .select on array

### ISSUE THREAD

**Issue by LucasCioffi** [twilio/twilio-ruby#146]
Hello, I'm wondering why the code above works in the Heroku console...

    TWILIO.conferences.list(friendly_name: "abc").first.participants.list.select{|participant| participant.call_sid == "xyz"}

... but in the Heroku log, I see this error

    NoMethodError (private method `select' called for #<Twilio::REST::Participants:0x0001234567>)

It appears to be a class, so .select should work.

> TWILIO.conferences.list(friendly_name: "abc").first.participants.list.class
=> Array

Any ideas what might be going on?  Thank you!

**Comment by philnash** [comment]
Hi Lucas, can you check the code in your application again? It looks like you're calling `select` directly on `participants` rather than calling `list` first as you do in your example here. I can't think of any reason right now that `list` would return an instance of `Twilio::REST::Participants`.

**Comment by LucasCioffi** [comment]
Aha, in the light of day you have found what I could not see in the dark of night at 2am.  :)

The error was in my controller on a different line which was indeed missing .list prior to .select.

**Comment by philnash** [comment]
Glad to hear it's sorted @LucasCioffi! 2am is never the best time for debugging :laughing:
