### ISSUE TITLE
Secret sauce to lookup national_format formatting

### ISSUE THREAD

**Issue by radar** [twilio/twilio-ruby#155]
Hey Twilio-ers,

I was wondering if this Ruby library would ever contain code to format numbers as per a local format. The lookup service is useful in that it does this, but we're looking for something that we can run locally (i.e. no external service hits) and then that can format the number neatly for us.

Is that something this library would be able to do?

**Comment by philnash** [comment]
Hey @radar,

The secret sauce for national formatting, and used by our [lookups API](https://www.twilio.com/docs/api/rest/lookups) is actually [Google's libphonenumber](https://github.com/googlei18n/libphonenumber). 

There are a couple of existing gems around that wrap this library, perhaps one of those would suit?

* [global_phone](https://github.com/sstephenson/global_phone)
* [phonelib](https://github.com/daddyz/phonelib)

**Comment by radar** [comment]
Thanks @philnash :)

We've found [phony](https://github.com/floere/phony) as well and we're going with that.
