### ISSUE TITLE
Unable to make any API call gives SSL error

### ISSUE THREAD

**Issue by EMRJ** [twilio/twilio-ruby#157]
When I make this call Twilio::REST::Client.new it gives following error - undefined method `ssl_verify_peer=`

/home/emrj/gems/twilio-ruby-4.1.0/lib/twilio-ruby/util/client_config.rb:24:in `block in initialize': undefined method `ssl_verify_peer=' for #<Twilio::Util::ClientConfig:0x00000001b29ac0> (NoMethodError)

**Comment by philnash** [comment]
Hi @EMRJ, what call are you making? You've only put the error message there.

**Comment by EMRJ** [comment]
I have tried make call - https://www.twilio.com/docs/quickstart/ruby/rest/call-request

**Comment by philnash** [comment]
Ah, sorry! I mean what is the code you've written that is causing that error?

**Comment by EMRJ** [comment]
The sample code available in the above url

make_call.rb

require 'rubygems' # not necessary with ruby 1.9 but included for completeness
require 'twilio-ruby'
 
# put your own credentials here - from twilio.com/user/account
account_sid = 'ACC SID'
auth_token = 'AUTH TOKEN'
 
# set up a client to talk to the Twilio REST API
@client = Twilio::REST::Client.new account_sid, auth_token
 
@call = @client.account.calls.create(
  :from => '+14159341234',   # From your Twilio number
  :to => '+18004567890',     # To any number
  # Fetch instructions from this URL when the call connects
  :url => 'http://twimlets.com/holdmusic?Bucket=com.twilio.music.ambient'
)

**Comment by philnash** [comment]
Could you post the full stack trace as well, please?

**Comment by EMRJ** [comment]
$ruby make_call.rb 
/home/emrj/.rvm/gems/ruby-2.2.0@proj/gems/twilio-ruby-4.1.0/lib/twilio-ruby/util/client_config.rb:24:in `block in initialize': undefined method `ssl_verify_peer=' for #<Twilio::Util::ClientConfig:0x00000002a4e208> (NoMethodError)
	from /home/emrj/.rvm/gems/ruby-2.2.0@prj/gems/twilio-ruby-4.1.0/lib/twilio-ruby/util/client_config.rb:23:in `each'
	from /home/emrj/.rvm/gems/ruby-2.2.0@prj/gems/twilio-ruby-4.1.0/lib/twilio-ruby/util/client_config.rb:23:in `initialize'
	from /home/emrj/.rvm/gems/ruby-2.2.0@prj/gems/twilio-ruby-4.1.0/lib/twilio-ruby/rest/base_client.rb:27:in `new'
	from /home/emrj/.rvm/gems/ruby-2.2.0@prj/gems/twilio-ruby-4.1.0/lib/twilio-ruby/rest/base_client.rb:27:in `initialize'
	from /home/emrj/.rvm/gems/ruby-2.2.0@prj/gems/twilio-ruby-4.1.0/lib/twilio-ruby/rest/client.rb:125:in `initialize'
	from make_call.rb:7:in `new'
	from make_call.rb:7:in `<main>'

**Comment by philnash** [comment]
I actually have no idea what's going on here. The issue seems to be that the `Twilio::Util::ClientConfig` object is trying to set `ssl_verify_peer` but that it doesn't exist. However, it should only be trying to set things in the keys of the `DEFAULTS` object.

I cannot actually reproduce the issue you're getting. Is there any more information you can give me?

**Comment by EMRJ** [comment]
downgraded version to 3.16.0 now works fine

**Comment by philnash** [comment]
Can you update to the latest version (4.2.1 as of today) and see if this works for you? Thanks.

**Comment by EMRJ** [comment]
Now works fine

**Comment by philnash** [comment]
Thanks @EMRJ!
