### ISSUE TITLE
Errors when attempting to move numbers between subaccounts

### ISSUE THREAD

**Issue by smedrick** [twilio/twilio-ruby#160]
I'm attempting to move a number from a subaccount to a master account. When I use the master account credentials, and try to update the number, I get

```
Twilio::REST::RequestError: The requested resource /2010-04-01/Accounts/xxxx/IncomingPhoneNumbers/yyyy.json was not found
```

When using the subaccount's credentials, I get the following error:

```
Twilio::REST::RequestError: API user must be the parent account to transfer phone numbers.
```

My code:
```
  @client = Twilio::REST::Client.new account_sid, auth_token
  @client.account.incoming_phone_numbers.get(phone).update({:account_sid => master_account_sid})
```

**Comment by smedrick** [comment]
The problem is the update. It should be pointing to the subaccount rather than the master account (xxxx). Inserting the subaccount sid into the phone number resource would solve the problem.

**Comment by philnash** [comment]
Ah, I see the issue. You can access the subaccount from the master account client by doing the following:

```ruby
@client = Twilio::REST::Client.new master_account_sid, auth_token
sub_account = @client.accounts.get(sub_account_sid)
sub_account.incoming_phone_numbers.get(phone).update({:account_sid => master_account_sid})
```

Let me know if this helps!

**Comment by smedrick** [comment]
I'm getting 

```
Twilio::REST::RequestError: Twilio::REST::RequestError
```

on the update.

**Comment by philnash** [comment]
Ah, I know what's wrong now. You actually need to use the phone number's SID with the API to return the resource.

So, adding to the previous example, you'll want to do the following:

```ruby
@client = Twilio::REST::Client.new master_account_sid, auth_token
sub_account = @client.accounts.get(sub_account_sid)
phone_number_sid = sub_account.incoming_phone_numbers.list(:phone_number => phone_number).first.sid
sub_account.incoming_phone_numbers.get(phone_number_sid).update({:account_sid => master_account_sid})
```

This gets the phone number resource by filtering the list of all phone numbers for the account by the number itself and then extracts the SID from it and uses that in the final call to update.

**Comment by smedrick** [comment]
That is some weird, wild stuff...but it works.

Thanks!

**Comment by philnash** [comment]
No problem!
