### ISSUE TITLE
How to manage Twilio response for SMS send?

### ISSUE THREAD

**Issue by HiteshSongra** [twilio/twilio-ruby#161]
Hello,

I need a response of SMS send process. How can i know that SMS is send or not OR the provided mobile number is valid or not.

```ruby
@client = Twilio::REST::Client.new
res = @client.messages.create(
  from: '+12XXXXXXXXX',
  to: "+XXXXXXXXXXXX",
  body: "Your mobile number is valid."
)
```

How to get response of above code.

I write code for that as below but not working.

```ruby
render :json => {
  response: res
}	
return
```

it's throw an exception stack level too deep.

**Comment by philnash** [comment]
There are a few ways to answer your question, so hopefully this helps:
Firstly, the result of your first piece of code above should be a `<Twilio::REST::Message>` object.
```ruby
@client = Twilio::REST::Client.new
res = @client.messages.create(
  from: '+12XXXXXXXXX',
  to: "+XXXXXXXXXXXX",
  body: "Your mobile number is valid."
)
# => <Twilio::REST::Message @path=/2010-04-01/Accounts/YOUR_ACCOUNT_SID/Messages/MESSAGE_SID>
```

You can call `status` on that object, but when it is first returned it will probably be "queued" as Twilio will have queued the message to be sent.

You can get updates on the status of the message if you pass the API a [statusCallback URL](https://www.twilio.com/docs/api/rest/sending-messages#status-callback-parameter) to callback to with updates, like this:

```ruby
res = @client.messages.create(
  from: '+12XXXXXXXXX',
  to: "+XXXXXXXXXXXX",
  body: "Your mobile number is valid.",
  statusCallback: "http://example.com/message_status"
)
```

You will need to save the message SID, perhaps in the database, and look it up again when you receive the status callback to update its status. To receive the callbacks, you will need to implement an endpoint at your chosen URL (in the above example, at /message_status). Calls to that endpoint will receive [the normal message parameters](https://www.twilio.com/docs/api/twiml/sms/twilio_request#request-parameters) and a [MessageStatus and ErrorCode](https://www.twilio.com/docs/api/rest/sending-messages#status-callback-parameter-request-parameters). MessageStatus could be any of: [queued, sending, sent, receiving, received, delivered, undelivered and failed](https://www.twilio.com/docs/api/rest/message#sms-status-values).

### Checking valid phone numbers

There is another way to check whether a number is valid. Twilio now has a [lookups API](https://www.twilio.com/lookup) that allow you to check for valid phone numbers and get carrier details about them. [This blog post](https://www.twilio.com/blog/2015/04/validate-phone-numbers-in-ruby-using-the-lookup-api.html) has a great explanation of how to use this API in Ruby.

Let me know if this helps at all!

**Comment by philnash** [comment]
I'm closing this as there hasn't been a response. Please re-open and let me know if there's anything else you need help with. Thanks!

**Comment by LeandroTk** [comment]
I tested with ENV["my_phone_number"] in the "to" parameter. And the the status "queued". 
Should I wait to receive the sms message in my smartphone?

**Comment by michaelirey** [comment]
There is valuable information in this closed issue. It would be nice if this was part of the main documentation found here: https://www.twilio.com/docs/libraries/reference/twilio-ruby/index.html

**Comment by childish-sambino** [comment]
@michaelirey Which part in particular?

**Comment by michaelirey** [comment]
@childish-sambino The example of using the status callback and the events that would trigger the callback. Also an example using the lookups API would be useful. (Not sure if lookups API is part of the gem though - But a link to it in the main documentation would still be helpful)
