### ISSUE TITLE
undefined method signing_keys w/ v4.2.0

### ISSUE THREAD

**Issue by wireframe** [twilio/twilio-ruby#163]
according to the code samples Twilio API documentation for signing keys, the twilio-ruby gem should provide methods for creating signing keys.  
https://www.twilio.com/docs/api/rest/signing-keys#list-post

Current gem version:
twilio-ruby (4.2.0)

```ruby
client = Twilio::REST::Client.new account_sid, auth_token
client.account.signing_keys.create friendly_name: 'test'
#=> NoMethodError: undefined method `signing_keys' for #<Twilio::REST::Account:0x0000010eab4aa0>
```

**Comment by skimbrel** [comment]
Hey there!

You'll need to be in the beta program for access to Video and the SigningKeys endpoint. You can request access here: https://www.twilio.com/video/request-early-access

If you've already got access, your account portal should have a link to download a beta build of the helper library with methods present.
