### ISSUE TITLE
TaskRouterClient statistics does not accept arguments

### ISSUE THREAD

**Issue by abuinitski** [twilio/twilio-ruby#164]
See https://github.com/twilio/twilio-ruby/blob/master/lib/twilio-ruby/rest/task_router/statistics.rb#L7

While documentation for these method actually has parameters https://www.twilio.com/docs/taskrouter/workspace-statistics

**Comment by philnash** [comment]
Hey @abuinitski,

Argh, you're absolutely right. The final `true` parameter tells the REST client that the full path has been passed and the arguments are ignored. I will get a fix together for this this afternoon.

Thanks!

**Comment by philnash** [comment]
I've released version 4.2.1 of the gem which fixes this. Thanks for reporting!

**Comment by abuinitski** [comment]
Yay, thank you. It works.
