### ISSUE TITLE
RSpec/Testing mocks

### ISSUE THREAD

**Issue by elado** [twilio/twilio-ruby#168]
Any chance to see testing support with mocks?

Similar to Mandrill Mailer: https://github.com/renz45/mandrill_mailer#offline-testing

**Comment by elado** [comment]
Found this: https://gist.github.com/citrus/cf08110c8519beecaf1a

And in `spec_helper.rb`:

```ruby
RSpec.configure do |config|
  # ...
  config.include TwilioHelper
  # ...
end
```

Would love to see it integrated.

**Comment by carlosdp** [comment]
Thanks for the suggestion, we have some new testing stuff coming down the pipeline very soon!

**Comment by rapito** [comment]
Any updates to mock twilio requests/responses for testing frameworks?

**Comment by zinosama** [comment]
+1

**Comment by MaicolBen** [comment]
For sms/buying numbers/ number lookup you can use https://github.com/MaicolBen/twilio_mock
For phone calls https://github.com/JMongol/twilio-test-toolkit

**Comment by jeferbc** [comment]
what about twilio video?, how can I mock that?
