### ISSUE TITLE
Documentation and Examples are out of date

### ISSUE THREAD

**Issue by kubapol** [twilio/twilio-ruby#169]
Could you guys update the documentation for sending messages (https://www.twilio.com/docs/api/rest/message) and examples (https://github.com/twilio/twilio-ruby/blob/master/examples/examples.rb)? Twilio warns me when I use the older version:
"[DEPRECATED] SMS Resource is deprecated. Please use Messages (https://www.twilio.com/docs/api/rest/message)"

Thanks in advance!

**Comment by philnash** [comment]
Hey @kubapol,

You should be getting deprecations notices if you use `client.account.sms.messages` for anything. Where are you seeing documentation to tell you to use that? I don't see that on the pages you link to.
