### ISSUE TITLE
Encoding Sms: display ? instead of special characters

### ISSUE THREAD

**Issue by robinroyer** [twilio/twilio-ruby#170]
As said in the title some characteres are remplaced by `?` unless there is a `ç`or unicode `\u0040` in the body

```Ruby
require 'twilio-ruby'


account_sid = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
auth_token = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
@client = Twilio::REST::Client.new account_sid, auth_token

body = "coucou é le à @coucou"
message = @client.account.messages.create(:body => body,
    :to => "+336xxxxxxxx",
    :from => "+336xxxxxxxx")
# SMS received => coucou ? le ? ?coucou

body = "coucou é ç à @coucou"
message = @client.account.messages.create(:body => body,
    :to => "+336xxxxxxxx",
    :from => "+336xxxxxxxx")
# SMS received => coucou é ç à @coucou
```

**Comment by arambert** [comment]
:+1:  The same issue is happening with my app (twilio-ruby v4.3.0)

**Comment by philnash** [comment]
I just tried this myself in IRB with version 4.3.0 and it worked (see screenshot):

![img_2783](https://cloud.githubusercontent.com/assets/31462/10019951/2a03b2a4-6138-11e5-845c-6598cf5bc427.PNG)

If you have examples of messages like this, could you send their SIDs to help@twilio.com and perhaps they can track down what is going on.

**Comment by arambert** [comment]
I tried to send the message "testé avec adrien@silex.pro" through Twilio API Explorer and through my ruby app, both time I got ? instead of special chars on my iPhone: "test? avec adrien?silex.pro"

**Comment by arambert** [comment]
I've submit a ticket to Twilio...

**Comment by philnash** [comment]
That's interesting, there was just a StackOverflow question about [things getting escaped inthe Twilio API explorer](http://stackoverflow.com/questions/32716270/twilio-sms-line-break-doesnt-work/32718491#32718491). Can you try the same thing from the Ruby helper and see if you get the same result?

**Comment by arambert** [comment]
![twilio screenshot](https://cloud.githubusercontent.com/assets/288781/10020515/a7f533f8-6143-11e5-94b4-46c2fc50d1ff.png)

I tried the newline \n and it's also beeing escaped on my phone (displayed "\n" instead of new line)...

**Comment by philnash** [comment]
In that case, were the accented letters escaped?

**Comment by arambert** [comment]
The accented letters where replaced by question marks (?).

I tried to send accented letters with CURL but it also replaces them by "?".

**Comment by philnash** [comment]
Ok, this definitely sounds like an issue for support, I'll close this issue in the meantime.

**Comment by arambert** [comment]
This is the message sent with Curl: 
    test@test.com \n testé

This is the message received by Twilio: 
![twilio screenshot 2](https://cloud.githubusercontent.com/assets/288781/10020945/c44aa270-6145-11e5-8e24-d83dd3f32839.png)

This is how i received it on my iPhone 5S:
![img_1514](https://cloud.githubusercontent.com/assets/288781/10021147/d0130696-6146-11e5-88c5-2d645812c113.PNG)

**Comment by arambert** [comment]
I see that you could make it work in the UK (+44). 
Could it be a +33 (France) problem ? Does Twilio encode differently for some country ?

**Comment by philnash** [comment]
I don't think Twilio encodes things differently per country. Any SMS may contain a special character. This is why I think it's best for support to look into.

**Comment by arambert** [comment]
Did you transfer this issue to the support ?

**Comment by philnash** [comment]
I thought you had opened a support ticket?

**Comment by arambert** [comment]
Yes I did but they may be more diligent if you support it ;)

**Comment by philnash** [comment]
Do not worry, the support team will get to you :smile:

**Comment by arambert** [comment]
Ok, thank you.

**Comment by tomasero** [comment]
Did you fix this?

**Comment by vikramtanwar** [comment]
@arambert hi !!
Were you able to resolve the ? mark issue. 
I'm sending a text message in spanish. This is the sample screenshot of the message. 
![image](https://user-images.githubusercontent.com/24538347/30323936-c5507026-97dc-11e7-98dc-4ff813a1aaa2.png)

If you have any inputs, it would be great if you or any one can suggest something.

**Comment by tomasero** [comment]
Never :(

**Comment by imthepitts** [comment]
Hello @vikramtanwar and @tomasero, 

Character encoding issues tend to be related to how the carrier networks handle special characters (GSM vs. Unicode), not the helper libraries themselves. 

I recommend you reach out to our support team to fully investigate this issue:
https://www.twilio.com/console/support/tickets/create

When submitting the ticket, please provide a couple recent Message SIDs so they can investigate immediately.

A Message SID is a 34-digit unique identifier that starts with "SM" or "MM". You can find the Message SIDs in your account's message log: https://www.twilio.com/console/sms/logs 

All the Best,

Zack

**Comment by mtmcfarl** [comment]
I'm seeing the same behavior in twilio-ruby (5.10.2).  I created the message via the api - El baño.  And to my iPhone6 device was delivered El ba?o.  Thoughts?  I already have a support ticket open with Twilio about this very thing.  Not sure where to look next.

**Comment by philnash** [comment]
@mtmcfarl I would wait for the reply from support then. They should be able to track down what is happening and give guidance.

**Comment by vickyshah129** [comment]
anyone sort the issue out? I am having exactly the same issue specifically for e with grave **é**

**Comment by lluchez** [comment]
Was this issue ever resolved? Is there any work around?

**Comment by childish-sambino** [comment]
@vickyshah129 @lluchez The best path forward is in the above comment: https://github.com/twilio/twilio-ruby/issues/170#issuecomment-328929009

This is not something that can be solved in the helper library and the solution is not universal. Recommend opening a support ticket with specific message SIDs.

**Comment by afleishaker** [comment]
@vickyshah129 @lluchez @ anyone else interested:

In speaking to Twilio support, I can also corroborate that this pertains to varied carrier partner support for the characters. I've been told by support and have verified with testing that one can force the requisite UCS2 encoding, displaying the characters, by including a [punctuation space](http://www.fileformat.info/info/unicode/char/2008/index.htm) in one's message. They hope that the carrier partner will resolve this in "near(ish) future", but for now this is a viable temporary solution. This isn't prolific enough for them to write up a help article, according to support, but they said I could share this option, so thought I would do so to prevent any others from getting stumped.

Happy coding!

**Comment by intesamSatti** [comment]
@afleishaker Thanks for the "temporary" solution because 4.5 years later and the issue still persists so might as well call it the permanent solution
