### ISSUE TITLE
Having problems Pausing in Twilio::TwiML::Response.new

### ISSUE THREAD

**Issue by shua123** [twilio/twilio-ruby#172]
This is related, possibly the same as issue #152 .

I am trying to write a TwiML response that would send 2 messages with a pause in between. I have tried a variety of syntax including the one suggested in Issue #152 but it keeps ignoring the pause and sending both messages right away.

```ruby
 twiml = Twilio::TwiML::Response.new do |r|
         r.Message message
         r.Pause length: "10"
         r.Message message2
      end
    respond_to do |format|
      format.xml {render xml: twiml.text}
    end
```

**Comment by shua123** [comment]
Twilio logs show a "Warning: 12200 - Schema validation warning" error but the body of the response matches what is shown in Example 1 on https://www.twilio.com/docs/api/twiml/pause#attributes-length

**Comment by philnash** [comment]
@shua123 Sorry for the delay in response here. I wasn't reading the code correctly, but I've just figured it out.

The `<Pause>` verb does not actually apply when dealing with sending SMS messages. [The only TwiML verbs you can use within a response to an incoming message are `<Message>` and `<Redirect>`](https://www.twilio.com/docs/api/twiml/sms/your_response#twiml-verbs). That is why you are receiving a Schema validation warning.

If you want to send 2 messages with a pause in between them, I recommend sending the second message via the REST API and delaying it by using a job queue like Sidekiq.

Let me know if that helps!
