### ISSUE TITLE
Twilio security update to SHA2-signed certificate

### ISSUE THREAD

**Issue by jguimond** [twilio/twilio-ruby#176]
Received an email from Twilio stating they are updating their certificate.

I am wondering if this is going to affect our use of this library?

Full message:
Security is always top of mind for us at Twilio. That’s why on December 1st we’ll be updating api.twilio.com with a SHA2-signed certificate, a significant improvement in encryption technology.

Though the vast majority of applications will not be impacted in any way, there is a possibility that applications using older SSL client libraries may run into compatibility issues. To verify that your application is compatible with the new certificate, we’ve provided a test API endpoint at api.twilio.com:8443. Please note this endpoint uses a different port from the current default port of 443. Make sure you specify that port in your Twilio SDK.

The validation endpoint will be deprecated on December 1st, 2015 when the new SHA2-signed certificate is deployed to the main Twilio API endpoint (port 443). Please let us know at help@twilio.com if you have any questions. We’re always listening and we’re here to help.

**Comment by carlosdp** [comment]
It should not affect the use of the library, no. The SHA2 algorithm is already supported by the OpenSSL libraries twilio-ruby utilizes. :smiley:

**Comment by carlosdp** [comment]
Additionally, if you want to be absolutely sure, you can override the port to the test port (8443) now to test it:

```ruby
@client = Twilio::REST::Client.new('AC_SID', 'TOKEN', port: 8443)
```

**Comment by jguimond** [comment]
Thanks!!
