### ISSUE TITLE
Twilio is Retiring Version 1.1

### ISSUE THREAD

**Issue by LucasCioffi** [twilio/twilio-ruby#177]
I received an email from Twilio this week that they are retiring versions 1.0 and 1.1 soon.

Do we need to use a certain version of this twilio-ruby gem to go with version 1.3?

I didn't see any mention of any breaking changes in the new Twilio version.  If we're using the Javascript API, do we need to change anything other than the version number in our code like this?

    <script type="text/javascript" src="//static.twilio.com/libs/twiliojs/1.3/twilio.min.js"></script>

Thank you!

**Comment by carlosdp** [comment]
Hey @LucasCioffi, you don't need any different version of the twilio-ruby library to upgrade the JS client version. That <script> tag you posted should work fine without any change in how you use twilio-ruby!

**Comment by LucasCioffi** [comment]
Thank you @carlosdp.
