### ISSUE TITLE
Security Certificate Changes

### ISSUE THREAD

**Issue by dobryakov** [twilio/twilio-ruby#180]
I received this message from Twilio, may be it will be interesting for you:

----------------------------------------
We’ll be updating api.twilio.com with a SHA2-signed certificate, a significant improvement in encryption technology.

Though the vast majority of applications will not be impacted in any way, there is a possibility that applications using older SSL client libraries may run into compatibility issues. To verify that your application is compatible with the new certificate, we’ve provided a test API endpoint at api.twilio.com:8443. Please note this endpoint uses a different port from the current default port of 443. Make sure you specify that port in your Twilio SDK.

The validation endpoint will be deprecated on December 1, 2015 when the new SHA2-signed certificate is deployed to the main Twilio API endpoint (port 443). 

----------------------------------------

**Comment by kevinchandler** [comment]
I'm curious as well. Is there any update that needs to be made to this gem with regards to Twilio's update?

**Comment by philnash** [comment]
The gem does not need an update, however you may want to check if your application is using an older SSL client. You can do so by setting the port to 8443 in your `Twilio::REST::Client` instance, like this:

```
client = Twilio::REST::Client.new(account_sid, auth_token, port: 8443)
```

If you have issues then you will need to update your SSL client.

**Comment by kevinchandler** [comment]
Nice. Thanks for the info
