### ISSUE TITLE
Confirm upcoming certificate update on Twillio

### ISSUE THREAD

**Issue by Blackening999** [twilio/twilio-ruby#181]
Hello

I've received email from Twilio's reminding about certificate changes.

"This is a reminder that on December 1, 2015 at 4:30 PM PT, we’ll be updating api.twilio.com with a SHA2-signed certificate, a significant improvement in encryption technology.
From the official announcement on October 8, 2015:
Though the vast majority of applications will not be impacted in any way, there is a possibility that applications using older SSL client libraries may run into compatibility issues. To verify that your application is compatible with the new certificate, we’ve provided a test API endpoint at api.twilio.com:8443. Please note this endpoint uses a different port from the current default port of 443. Make sure you specify that port in your Twilio SDK.

The validation endpoint will be deprecated on December 1, 2015 when the new SHA2-signed certificate is deployed to the main Twilio API endpoint (port 443). Please let us know at help@twilio.com if you have any questions. We’re always listening and we’re here to help.

Cheers, 
Team Twilio"

**Comment by philnash** [comment]
Hello, that is all correct. Have you checked that API calls still work on your server using the  test port number? Do you have any issues?

**Comment by Blackening999** [comment]
Hey!
Thanks for fast response. Haven't tested it yet, will do soon and then let you know.
Great that gem have such support ;)

**Comment by philnash** [comment]
Great, I'm going to close this issue for now. Do give us a shout at help@twilio.com if you do find problems when you test this out. Thanks!
