### ISSUE TITLE
twilio-ruby 5.x not compatible with Rails 5

### ISSUE THREAD

**Issue by TangRufus** [twilio/twilio-ruby#194]
With `rails 5.0.0.beta3` & `twilio-ruby 5.0.0.rc2`, `$ bundle install` gives this error:

```
    rails (~> 5.0.0.beta3) was resolved to 5.0.0.beta3, which depends on
      activesupport (= 5.0.0.beta3)

    twilio-ruby (~> 5.0.0.rc2) was resolved to 5.0.0.rc2, which depends on
      activesupport (~> 4.2)
```

**Comment by findrails** [comment]
Getting the same issue - hope it can be fixed (relatively) easily!

**Comment by chashmeetsingh** [comment]
Tried bundle update ?

**Comment by zachlatta** [comment]
Any updates on this? Running into same issue and figure it's worth a bump now that Rails 5 is stable.

**Comment by philnash** [comment]
I'm afraid this is still the case. I'll do some sleuthing to see if I can remove the activesupport dependency.

**Comment by philnash** [comment]
I pulled the latest from the next-gen branch, removed the `activesupport` dependency and all the tests passed. So #215 makes this update and makes the next-gen version of this gem compatible with Rails 4 and 5 now.

**Comment by philnash** [comment]
Good news! #215 has been merged to the next-gen branch and will be part of the next release candidate. Look out for RC11 and look forward to trying out the next gen version of the library soon!
