### ISSUE TITLE
Can't seem to send an alphanumeric message

### ISSUE THREAD

**Issue by amingilani** [twilio/twilio-ruby#196]
Can't send an alphanumeric message

**4.11.1**
**SMS API:**

### Code Snippet
```ruby
#!/usr/bin/env ruby

require 'twilio-ruby'

TWILIO_ACCOUNT_SID = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
TWILIO_AUTH_TOKEN  = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

@twilio = Twilio::REST::Client.new TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN

# Phone numbers
my_number  = 'Zeus The Mighty'
her_number = ''xxxxxxx''

text = "Welcome to Zeus The Mighty house."

# Send a text message
@twilio.messages.create(
  from: my_number, to: her_number, body: text
)

# Log this
puts "Message sent at: #{Time.now} | #{text}"
```

### Exception / Log
```
./text.rb 
/home/gilani/.rvm/gems/ruby-2.3.1/gems/twilio-ruby-4.11.1/lib/twilio-ruby/rest/base_client.rb:125:in `connect_and_send': The 'From' number Zeus The Mighty is not a valid phone number, shortcode, or alphanumeric sender ID. (Twilio::REST::RequestError)
	from /home/gilani/.rvm/gems/ruby-2.3.1/gems/twilio-ruby-4.11.1/lib/twilio-ruby/rest/base_client.rb:55:in `block (2 levels) in <class:BaseClient>'
	from /home/gilani/.rvm/gems/ruby-2.3.1/gems/twilio-ruby-4.11.1/lib/twilio-ruby/rest/list_resource.rb:94:in `create'
	from ./text.rb:17:in `<main>'
```

### Steps to Reproduce
1. Execute the code above

**Comment by dwillie** [comment]
I believe the maximum length for the from address in alphanumeric is 11 characters

**Comment by philnash** [comment]
That is correct, the maximum length for an alphanumeric sender ID is 11 characters.

Be aware that spaces get rendered differently based on the device they are sent to as well. I've seen iOS render spaces, but Android phones strip them out.

Finally, make sure you have [contacted Twilio support](https://www.twilio.com/help/contact) to enable alphanumeric sender IDs for your account.

**Comment by philnash** [comment]
Hey @amingilani, I'm going to close this as it's a couple of months old now. But feel free to re-open if you are still having difficulties.
