### ISSUE TITLE
Media objects should include a way to get the final resource URL

### ISSUE THREAD

**Issue by markquezada** [twilio/twilio-ruby#198]
Using 5.0.0.rc4

This might be considered a feature request but I find the absence of a way to get a media object's final URL surprising.

This may be a limitation with the [Twilio Media API](https://www.twilio.com/docs/api/rest/media) itself but there is no direct way to get the final URL for media through the object returned from this gem. The problem is exacerbated by the fact that the URI returned via the API can redirect several times before reaching the final destination.

I've resorted to using this custom class:

``` ruby
class TwilioMedium
  delegate :content_type, to: :@twilio_medium_instance
  delegate :delete, to: :@twilio_medium_context

  def initialize(twilio_medium_context)
    @twilio_medium_context = twilio_medium_context
    @twilio_medium_instance = twilio_medium_context.fetch
  end

  def url
    @url ||= expanded_url
  end

private
  def uri
    @twilio_medium_instance.uri.gsub('.json', '')
  end

  def raw_url
    "https://api.twilio.com#{uri}"
  end

  def expanded_url
    result = Curl::Easy.perform(raw_url) do |curl|
      curl.head = true
      curl.follow_location = true
    end
    result.last_effective_url
  end
end
```

(Splitting context from instance is required due to the bug reported in #197)

This allows me to do this:

``` ruby
media_context = $twilio.account.messages(@message_sid).media(@medium_sid)
twilio_medium = TwilioMedium.new(twilio_medium_context)
twilio_medium.url
=> https://api.twilio.com/2010-04-01/Accounts/AC.../Message/MM.../Media/ME557ce644e5ab84fa21cc21112e22c485
```

**Comment by jingming** [comment]
@markquezada Thanks for bringing this up! We will add ticket internally to address this issue and get to it as soon as possible.

**Comment by axelson** [comment]
@jingming was this ever fixed?
