### ISSUE TITLE
attributes for channel always return nil (IP Messaging)

### ISSUE THREAD

**Issue by abscondite** [twilio/twilio-ruby#199]
But that chat have attributes have attributes and frontend see that

**Version:**
**API Subdomain (api/taskrouter/ip_messaging):** ip_messaging
### Code Snippet

``` ruby
# paste code here
[28] pry(main)> s.channels.list.first.friendly_name
=> "Hirthe Group"
[29] pry(main)> s.channels.list.first.attributes
=> nil
```

**Comment by jingming** [comment]
@abscondite Thanks for flagging the issue. We've raised the problem with the appropriate team internally and it will be prioritized.
