### ISSUE TITLE
session[:sms_time] = Time.zone.now

### ISSUE THREAD

**Issue by sri26** [twilio/twilio-ruby#203]
session[:sms_time] = Time.zone.now gets cleared for every new request..i want to get time difference between two sms requests

**Comment by philnash** [comment]
Hey @sri26, sorry for the delay in responding to this. Could you describe your issue in a bit more detail please? Is this when sending or receiving SMS messages? And what framework are you using?

Thanks!

**Comment by philnash** [comment]
I'm going to close this issue as there's been no response for a while. Feel free to re-open it with an answer to my question.
