### ISSUE TITLE
SMS not sending, but logs say it has

### ISSUE THREAD

**Issue by grandmasterspoc** [twilio/twilio-ruby#204]
I'm sending a message with the code here
```ruby

  def send_message
    @user_message = user_message
    @user_reformatted_number = user_reformatted_number
    api = Twilio::REST::Client.new ENV['AMAZONIAN_TWILIO_ACCOUNT_SID'], ENV['AMAZONIAN_TWILIO_AUTH_TOKEN']
    api.messages.create(
      :from => '+13853753097',
      :to => @user_reformatted_number,
      :body => @user_message
    )
  end
```

and there are no errors being generated, and the message shows up on the twilio dashboard logs on the website as delivered,

only my phone doesn't get any  sms message.

how can I fix this?

**Comment by philnash** [comment]
Hi @grandmasterspoc, sorry for the delayed response here. I'm not sure this is an issue with the Ruby library so I'm going to close this for now.

What I'd encourage you to do, if you haven't already, is [send in a report to Twilio support](https://www.twilio.com/help/contact) with the Message SIDs of some messages that are described as "delivered" but never arrived. They can look into what happened to the message then and try to resolve this for you.

Thanks!
