### ISSUE TITLE
SMS not sending

### ISSUE THREAD

**Issue by sai43** [twilio/twilio-ruby#205]
My code was working fine before few days back, suddenly it is not sending sms using my twilio account.  here is my code. 

# Ruby version
ruby 2.3.0p0

# Rails version
Rails 4.2.4

# my ruby code:

    twilio_sid = "account sid"
    twilio_token = "atoken"
    twilio_phone_number = "+14153603584"
     @twilio_client = Twilio::REST::Client.new twilio_sid, twilio_token
      @twilio_client.account.sms.messages.create(
        :from => "#{twilio_phone_number}",
        :to => number_to_send_to,
        :body => "This is an message. It gets sent to #{number_to_send_to}"
      )

# Twilio Validate number    
+919618706514 - 096187 06514 - IN

# Error Message:
<Twilio::REST::Client @account_sid=AC50b6263f0c72a73a9a69ab934334720a>
[DEPRECATED] SMS Resource is deprecated. Please use Messages (https://www.twilio.com/docs/api/rest/message)

The 'To' number 919618706514 is not a valid phone number.(but it is valid number)

**Comment by philnash** [comment]
That is weird that you are being told that isn't a valid phone number. I recommend getting in touch with [Twilio Support](https://www.twilio.com/help/contact) to try to sort that out.

You also have a deprecation warning there. I'd recommend changing the call to send the message to:

```ruby
@twilio_client.account.messages.create(
```

That is, drop the `sms.` before `messages`. Then you will be using the more up to date [Messages resource](https://www.twilio.com/docs/api/rest/message).
