### ISSUE TITLE
list sorting

### ISSUE THREAD

**Issue by mattwarrenrnp** [twilio/twilio-ruby#207]
**Version:** 4.11.1
**API Subdomain:** ip_messaging/messages

### Code Snippet
```ruby
    consumed_index = channel.members.list.find{ |m| m.identity == id.to_s }&.last_consumed_message_index
    consumed_index = 0 if consumed_index.nil?
    channel.messages.list.last.index - consumed_index
```

### Feature Request
trying to compute an unread count for the member.  due to the pagination of the REST API and the ascending sort order of the messages returned the `channel.messages.list.last.index` returns at most `50`.  I wasn't able to find a documented way to get the full count of messages or just return the last message or sort the list in descending order.

**Comment by philnash** [comment]
Hey @mattwarrenrnp, you are right there is no sorting of the API and the [pagination information was removed from the API last year after a number of trade offs were discussed](https://www.twilio.com/engineering/2015/04/16/replacing-absolute-paging-with-relative-paging).

I'd recommend keeping the unread counts locally in your own database. You might have to walk through the whole list of messages to load the information into your database, but you can at least [get pages bigger than 50 using the PageSize parameter](https://www.twilio.com/docs/api/rest/response#response-formats-list-filters).
