### ISSUE TITLE
message.rb methods references (potentially uninitialized) @context variable directly

### ISSUE THREAD

**Issue by benstein** [twilio/twilio-ruby#212]
**Version:** release-5.x
**API Subdomain (api/taskrouter/ip_messaging):** messaging

### Code Snippet
```ruby
>> msg = @client.account.messages.create(...)
>> msg.feedback
NoMethodError: undefined method `feedback' for nil:NilClass
	from /Users/bstein/.rvm/gems/ruby-2.2.1/gems/twilio-ruby-5.0.0.rc9/lib/twilio-ruby/rest/api/v2010/account/message.rb:524:in `feedback'
```

The `feedback` method 
```ruby
def feedback
   @context.feedback
end
```
access the `@context` variable directly, but it's not intialized. It should likely use the `context` method, which initializes and memoizes the variable:
```ruby
def feedback
    context.feedback
end
```

**Comment by ihumanable** [comment]
This was fixed in https://github.com/twilio/twilio-ruby/commit/ddae29996187fbc7497d62bc83ad3369c237a6a9
