### ISSUE TITLE
Tagging all requests with `X-Request-Id` when available

### ISSUE THREAD

**Issue by ciaranarcher** [twilio/twilio-ruby#214]
Hi Twilio folks 👋 

When sending requests using this gem, we set a 3s timeout. This is long enough for almost all API requests we regularly make. It looks like this: 

```
client = Twilio::REST::Client.new(account_sid, token, timeout: 3)
```

We've been troubleshooting some cases where that timeout is exceeded. Given that a timeout yields no response headers (and thus no `Twilio-Request-Id` or `Twilio-Request-Duration`), in these cases, it is more useful for us to pass a known request ID along with our request to Twilio and _then_ ask Twilio support to search for that request ID on their end. This way we can still obtain information about the duration of the request at the Twilio servers which is very helpful when investigating longer latency requests. 

The pitch: would you consider a PR to allow every request for a given client instance to be tagged with a request ID stored in `Thread.current[:request_id]` (if available)? We've used this approach to good effect with our own internal API clients at Zendesk with help from [this rack-middleware](https://github.com/anveo/rack-request-id). 

Thanks for considering this, and keep up the good work!

**Comment by ciaranarcher** [comment]
Hi - has anyone had a chance to take a look at this?

**Comment by ajtack** [comment]
This caught my attention today.

If to do this (we already do in some of our client-side SDKs), I'd be rather inclined to have the library generate a `Twilio-Request-Id` header itself. That way we have a stronger chance of good unique generation.

Just to make sure we stay focused on real problems: When your Twilio requests get timed out, what specific output are you looking for when you contact support? An explanation for the timeout, or something more precise?

**Comment by ciaranarcher** [comment]
> Just to make sure we stay focused on real problems: When your Twilio requests get timed out, what specific output are you looking for when you contact support? An explanation for the timeout, or something more precise?

I'd just like to know how long the request look Twilio to process and compare that to my client timeout. If the processing time was less than my client timeout it suggests the latency is being introduced elsewhere.

**Comment by dougblack** [comment]
Hey @ciaranarcher, we introduced `I-Twilio-Request-Id and `I-Twilio-Request-Duration` a while back to address both of these issues.
