### ISSUE TITLE
Feature request: support new notify services

### ISSUE THREAD

**Issue by eford1** [twilio/twilio-ruby#218]
### Feature Request

I was wondering if you have a timeline for supporting the new Notify Services, especially push notifications (https://www.twilio.com/docs/api/notifications/rest/notifications) Thanks!

**Comment by philnash** [comment]
Hi @eford1, Notify is supported as part of the next-gen version of this library, which is currently available in release candidate status. You can get it by installing RC11 (the latest) like so:

    gem install twilio-ruby -v 5.0.0.rc11

or by adding

    gem "twilio-ruby", "5.0.0.rc11"

to your Gemfile.

The [documentation you point to](https://www.twilio.com/docs/api/notifications/rest/notifications) actually uses code from the version 5 library. Do watch out though, as the version 5 gem is not backwards compatible with the version 4 gem.

**Comment by eford1** [comment]
Thank you for the quick reply @philnash!
