### ISSUE TITLE
Using master account credentials cannot access subaccount resource

### ISSUE THREAD

**Issue by bdmac** [twilio/twilio-ruby#225]
**Version:** 4.11.1
**API Subdomain (api/taskrouter/ip_messaging):** incoming_phone_numbers

### Code Snippet
```ruby
client = Twilio::REST::Client.new # Master account credentials used
sid = "[subaccount owned phone number sid]"
number = client.incoming_phone_numbers.get(sid)
=> <Twilio::REST::IncomingPhoneNumber @path=/2010-04-01/Accounts/[MASTER ACCOUNT SID]/IncomingPhoneNumbers/[sid]>
number.account_sid
Twilio::REST::RequestError: The requested resource /2010-04-01/Accounts/[MASTER ACCOUNT SID]/IncomingPhoneNumbers/[sid].json was not found
from /Users/bdmac/.gem/ruby/2.3.0/gems/twilio-ruby-4.11.1/lib/twilio-ruby/rest/base_client.rb:125:in `connect_and_send'
```

### Exception / Log
```
Twilio::REST::RequestError: The requested resource /2010-04-01/Accounts/[MASTER ACCOUNT SID]/IncomingPhoneNumbers/[sid].json was not found
from /Users/bdmac/.gem/ruby/2.3.0/gems/twilio-ruby-4.11.1/lib/twilio-ruby/rest/base_client.rb:125:in `connect_and_send'
```

### Steps to Reproduce
1. Create a subaccount using master account credentials.
2. Purchase a phone number in that subaccount.
3. Attempt to fetch the phone number for the subaccount using the master account credentials.

The problem here is that the path that the Ruby gem builds injects the current client's sid which in this case is the master account. This leads to a 404 because the expected path to the phone number resource uses the **subaccount's** sid. If I construct my client using the subaccount's sid/token then the Ruby API calls work as expected.

This actually appears to be a bit of a mismatch between Twilio REST API and the gem (IMO). The [docs clearly indicate](https://www.twilio.com/docs/api/rest/subaccounts#authentication) "You can use your master Twilio Account credentials (AccountSid and AuthToken) to access Twilio's REST API for your master account as well as any of your subaccounts." That appears to be exactly what I'm trying to do (using my master account credentials to fetch a subaccount's resource) but it's failing.

Is there some way to override the path's account SID to not match the credentials used when constructing the client so that the path it builds is correct (while still using the master account credentials for auth)?

Alternatively could the REST API be updated to allow a subaccount-owned phone number to be accessible from either the master or subaccount sid in the paths?
```
/2010-04-01/Accounts/[MASTER-ACCOUNT-SID]/IncomingPhoneNumbers/[sid]
/2010-04-01/Accounts/[SUB-ACCOUNT-SID]/IncomingPhoneNumbers/[sid]
```

**Comment by philnash** [comment]
Twilio developer evangelist here.

The docs do indicate that you can you use your master credentials to authenticate with the API and access resources for your subaccounts. However, since the resources live under the subaccount resource itself, they are only available at the URL that contains the subaccount SID.

However, you do go on to ask the right questions. If you have an API client that is authenticated with the master account credentials, you can use those to access your subaccounts like so:

```ruby
client = Twilio::REST::Client.new
account = client.accounts.get(subaccount_sid)
number = account.incoming_phone_numbers.get(number_sid)
number.account_sid
```

Note the use of the `account` object to get the subaccount resource.

Now you are using your master account credentials to authenticate with the API and you correctly construct the URL for the subaccount resource using the account object for that subaccount.

**Comment by bdmac** [comment]
Cool yah I get that. Does running `client.accounts.get(subaccount_sid)` add a network request?

**Comment by philnash** [comment]
It does not add a network request, it's lazy like the rest of the library.

**Comment by dominiceden** [comment]
Just a quick comment as I has the same issue and think the latest Twilio Ruby library has changed - the call to get a subaccount by SID is now:

`@client.api.accounts('ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX').fetch`

See https://www.twilio.com/docs/iam/api/subaccounts?code-sample=code-return-a-subaccount-resource-by-its-account-sid&code-language=Ruby&code-sdk-version=5.x for more information.
