### ISSUE TITLE
Update msg to message in the to_s method in RestException

### ISSUE THREAD

**Issue by jefflinwood** [twilio/twilio-ruby#234]
https://github.com/twilio/twilio-ruby/blob/next-gen/lib/twilio-ruby/framework/exception.rb#L26

**Version:** 5.0.0-rc17
**API Subdomain (api/taskrouter/ip_messaging):** exception.rb

### Code Snippet
```ruby
     def to_s
        "[HTTP #{status_code}] #{code} : #{msg}"
      end
```

### Exception / Log
```
NameError - undefined local variable or method `msg' for #<Twilio::REST::RestException:0x007fbc3cd79358>
```

### Steps to Reproduce
1. Make an invalid API call with the current library

**Comment by philnash** [comment]
Both PRs #230 and #232 address this. Thanks for reporting! Will close this issue so it can be sorted through the PRs.

**Comment by nexhealth** [comment]
when will this be merged?
Thanks
