### ISSUE TITLE
Trivial README issue: link in gem badge leads to twilio gem instead of twilio-ruby gem

### ISSUE THREAD

**Issue by olleolleolle** [twilio/twilio-ruby#235]
The README contains a badge with a correct version number for this gem.

Its link seems to be configured to point at the `twilio` gem, which is older.

The desired link would be one that took us to the `twilio-ruby` gem.

(It's not a fix that can made to the README, though, it's configured _elsewhere_.)

Hope this helps!

**Comment by philnash** [comment]
There is no good reason that that points at the `twilio` gem! Thanks for reporting I'll see what I can do to get this pointing the right way.

**Comment by olleolleolle** [comment]
_Hi @philnash!_ (Last I saw you was in PolyConf!) Hope your day is great. ✨

**Comment by olleolleolle** [comment]
Yay!

**Comment by philnash** [comment]
Ah! Found it, the link was at the bottom of the README.

Thanks again for pointing it out @olleolleolle.
