### ISSUE TITLE
Unable to fetch resource context through list-resource

### ISSUE THREAD

**Issue by mcelicalderon** [twilio/twilio-ruby#238]
**Version:** 5.0.0.rc17
**API Subdomain (api/taskrouter/ip_messaging):** API, Taskrouter, all

[Client methods](https://github.com/twilio/twilio-ruby/blob/next-gen/lib/twilio-ruby/rest/client.rb#L153) allow to fetch list resources without a problem:

``` ruby
client.calls.list()
```

this snippet works, but methods on the client are not declared with an SID optional param that would allow the user to fetch a `resource context` directly, like this:

``` ruby
client.calls('call_sid').fetch
```

Account class does implement the optional sid param so right now we can do:

``` ruby
client.account.calls('call_sid').fetch
```

but having to access sub resources through account makes sub resources methods on the client class not very useful.

The same applies to other API domains like [taskrouter](https://github.com/twilio/twilio-ruby/blob/next-gen/lib/twilio-ruby/rest/taskrouter.rb#L29) (won't work):

``` ruby
client.taskrouter.workspaces('workspace_sid').fetch
```

and in this case the workaround is to call v1 that does implement the optional sid parameter:

``` ruby
client.taskrouter.v1.workspaces('workspace_sid').fetch
```

**Comment by dougblack** [comment]
This appears to have been addressed sometime between 5.0.0rc17 and the latest release. Please update. Going to close, feel free to reopen if you continue seeing issues.
