### ISSUE TITLE
Missing workflow config JSON generation (next-gen)

### ISSUE THREAD

**Issue by mcelicalderon** [twilio/twilio-ruby#239]
**Version:** 5.0.0.rc17
**API Subdomain (api/taskrouter/ip_messaging):** taskrouter

Next-gen version of this library is missing the workflow configuration generator that was found in the previous version [here](https://github.com/twilio/twilio-ruby/blob/master/lib/twilio-ruby/task_router/workflow_builder.rb)

**Comment by jingming** [comment]
@mcelicalderon Thanks for flagging. This is an intentional omission from the new libraries.
