### ISSUE TITLE
Will twilio ever support OAuth for Twilio Connect?

### ISSUE THREAD

**Issue by jeffblake** [twilio/twilio-ruby#240]
I was looking forward to integrating Twilio Connect through omniauth/oauth, but after looking deeper into the documentation, it doesn't look like Connect uses OAuth. Is this something thats on the roadmap?
It's nice to have a consistent interface for third party apps as I have about a dozen that I connect with at the moment.

**Comment by efossier** [comment]
@jeffblake I think this is a better question for help@twilio.com, I'm not very familiar with Twilio Connect and how one implements the auth flow so they will be better equipped to answer that. In terms of the library, we do not support oauth in the gem and don't have any plans to at the moment. We can definitely revisit this if it is a requirement for supporting twilio connect.
