### ISSUE TITLE
Cacheing /Headers

### ISSUE THREAD

**Issue by yoshie902a** [twilio/twilio-ruby#246]
"Twilio will attempt to cache the audio file the first time it is played. This means the first attempt may be slow to play due to the time spent downloading the file from your remote server. Twilio may play a processing sound while the file is being downloaded.

Twilio obeys standard HTTP caching headers. If you change a file already cached by Twilio, make sure your web server is sending the proper headers to inform us that the contents of the file have changed."

What are the typical headers to initiate caching and what are the correct headers to inform that he headers have changed? 

How does one use the twilio gem to pass the correct headers for this?

**Comment by philnash** [comment]
Hey @yoshie902a,

Caching is not a concern of the Twilio gem. This refers to the headers that _your web server_ sets on requests made to it by Twilio when fetching an audio resource, for example.

The main HTTP header you need to be concerned with is the `Cache-Control` header which allows you to set a number of options. The [MDN documentation on `Cache-Control`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control) is a pretty useful resource and a good place to start, check out the cache response directives.
