### ISSUE TITLE
missing fields on MemberInstance and MessageInstance

### ISSUE THREAD

**Issue by cainlevy** [twilio/twilio-ruby#249]
**Version:** 5.0.0.rc17
**API Subdomain (api/taskrouter/ip_messaging):** ip_messaging

### Feature Request

The REST API returns a `last_consumed_message_index` on Member, and an `index` on Message. But the Ruby client doesn't expose those values on MemberInstance or MessageInstance. I would like access to both of those so that when I am generating a batched notification, I may programmatically determine which messages a user has already seen.

**Comment by tmconnors** [comment]
This has been addressed in `5.0.0.rc19+`, please upgrade to the latest `gem install twilio-ruby -v 5.0.0.rc23`
