### ISSUE TITLE
empty? method isn't working when gettings calls or recordings

### ISSUE THREAD

**Issue by pikitgb** [twilio/twilio-ruby#257]
Version: 5.0.0.rc17
Related to recordings

```ruby

account_sid = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXX'
auth_token = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXX'
@client = Twilio::REST::Client.new account_sid, auth_token

calls = @client.calls.list("start_time>=" => "2017-04-01", "page_size" => 1000)

total = 0
results = []
begin
  calls.each do |c|
    results << c
    total = total + 1
  end
  calls = calls.next_page
  puts "Total: #{total}"
end while not calls.empty?

```
Hello i'm trying to get my calls logs and put then in my local db. (Not using pagination, cuz only have next_page, previous_page, and i don't see a way to pass in the arguments a page_number, page_size is available, but page_number give error about PageToken). So lets say this is running on a background process in Ruby. My first question is if there is anyway to know how many pages there is on my calls or recordings object?
And the current problem i'm having with this is about the empty? method.
- The empty? method for this array keeps going and is creating an infinite loop.

Thanks in advance.

**Comment by pikitgb** [comment]
Sorry, seems to be the start_time >=  the equal symbol isn't working. Without that it seems to be working right.

**Comment by jingming** [comment]
@pikitgb If you are trying to filter by start time after please use the `start_time_after` parameter here: https://github.com/twilio/twilio-ruby/blob/master/lib/twilio-ruby/rest/api/v2010/account/call.rb#L156
