### ISSUE TITLE
Expired security certificate for link in Wiki

### ISSUE THREAD

**Issue by zinosama** [twilio/twilio-ruby#258]
## Issue
In https://github.com/twilio/twilio-ruby/wiki/RequestValidator, the link to 'Twilio security documentation' triggers a Chrome warning (expired certificate?).

## To Reproduce
To reproduce, go to  https://github.com/twilio/twilio-ruby/wiki/RequestValidator, click on the link 'Twilio security documentation'.

**Comment by tmconnors** [comment]
This has been addressed.
