### ISSUE TITLE
Using TwilioWebhookAuthentication for Addons with multiple Twilio accounts

### ISSUE THREAD

**Issue by ndbroadbent** [twilio/twilio-ruby#267]
Hello,

I've figured out how to use the proc support to configure auth tokens for requests coming from multiple Twilio accounts:

```ruby
  config.middleware.use(Rack::TwilioWebhookAuthentication, nil, /^\/twilio/) { |account_sid|
    if account_sid == ENV['SID_ONE']
      ENV['AUTH_TOKEN_ONE']
    elsif account_sid == ENV['SID_TWO']
      ENV['AUTH_TOKEN_TWO']
    else
      nil
    end
  }
```

This is working for regular webhooks (e.g. call events), but it is failing for addon results. I am getting the `Auth token is required` exception. I've figured out that this is because the `AccountSid` parameter is not sent in the addon webhook JSON:

```ruby
auth_token = @auth_token || get_auth_token(params['AccountSid'])
```

I've thought about parsing the account SIDs in the addon payload URLs, but they're actually the subaccount ids, and I would need to have the master account SID to know which auth token to use.

For now I will just configure multiple routes for each of our accounts, and will set up `TwilioWebhookAuthentication` middlewares for each account, limited to certain routes.

Could I please request that the master `AccountSid` is also sent with addon webhooks?

**Comment by jingming** [comment]
@ndbroadbent This is a remnant from older version of the library. We've created a ticket internally to remove this file.
