### ISSUE TITLE
Get the Friendly Name for a TwiML bin

### ISSUE THREAD

**Issue by ndbroadbent** [twilio/twilio-ruby#270]
I've just figured out how to fetch the TwiML URL: #268 

This works to get the actual TwiML data, but I need to get the friendly name so that I can import this data from our Twilio account.

Could you please add an endpoint for TwiML bins, or point me in the right direction?

**Comment by jingming** [comment]
@ndbroadbent please reach out to help@twilio.com. One of our awesome support agents will be happy to help you out!
