### ISSUE TITLE
I think the next gen version (5.x) has lost the ability to fetch a subaccount by SID

### ISSUE THREAD

**Issue by ndbroadbent** [twilio/twilio-ruby#276]
**Version:** 5.0.0.pre.rc21

I'm just trying to fetch a subaccount by sid. In the old version you could call:

```ruby
@account = @client.accounts.get(@account_sid)
```

I can't see any example or methods in the new API that would allow me to do this in 5.x. Things I've tried:

```ruby
client.accounts.get(@account_sid)
# NoMethodError: undefined method `get' for #<Twilio::REST::Accounts:0x007ff5cefec1a0>
```

I tried following the [convention in the migration docs](https://github.com/twilio/twilio-ruby/wiki/Ruby-Version-5.x-Upgrade-Guide#accessing-resources):

(`call = @client.api.account.calls('CA123xxx').fetch`)

```ruby
2.3.3 :084 > client.accounts(@account_sid)
# ArgumentError: wrong number of arguments (given 1, expected 0)

2.3.3 :085 > client.api.accounts(@account_sid)
# ArgumentError: wrong number of arguments (given 1, expected 0)
```

**Comment by tmconnors** [comment]
@ndbroadbent This should have been addressed in `rc22`. Please upgrade to the latest, `gem install twilio-ruby -v 5.0.0.rc23`. Lets us know if you still have issues. 

```
@account_context = client.api.accounts(@account_sid)
```
