### ISSUE TITLE
"errorcode" method does not exist for Twilio::REST::Message

### ISSUE THREAD

**Issue by dli1022** [twilio/twilio-ruby#278]
*Note: These issues are for bugs and feature requests for the helper libraries. If you need help or support, please email help@twilio.com and one of our experts will assist you!*

**Version:** 4.4.0
**API Subdomain (api/taskrouter/ip_messaging):**

### Code Snippet
```ruby
# paste code here
client = Twilio::REST::Client.new account_sid, auth_token
message = client.account.messages.get(self.twilio_sid.to_s)
errorcode = message.errorcode
### Exception / Log
NoMethodError: undefined method `errorcode' for #<Twilio::REST::Message:0x0000000ba7a200>

### Steps to Reproduce
See code above

### Feature Request
_If this is a feature request, make sure you search Issues for an existing request before creating a new one!_

**Comment by tmconnors** [comment]
4.X family is only being supported for security vulnerabilities. Please upgrade to the latest `gem install twilio-ruby -v 5.0.0.rc23`
