### ISSUE TITLE
 next gen version (5.x) VOIP Call

### ISSUE THREAD

**Issue by shoaib-iqbal** [twilio/twilio-ruby#282]
i am writing back end for android app  the purpose of the app is connect users with each other(one to one ) for chat, voice video calls.
i am have generated voice token l
```ruby
token = Twilio::JWT::AccessToken.new TWILIO_ACCOUNT_SID, TWILIO_API_KEY, TWILIO_API_SECRET, 3600, 'user1'
    grant = Twilio::JWT::AccessToken::VoiceGrant.new
    grant.push_credential_sid = TWILIO_PUSH_CREDENTIAL_SID
    grant.outgoing_application_sid = TWILIO_APP_SID
    token.add_grant grant
```
Now i am unable to create a voice call. I am trying like this 

```ruby
client = Twilio::REST::Client.new(TWILIO_API_KEY, TWILIO_API_SECRET,TWILIO_ACCOUNT_SID)
@call = client.account.calls.create(:from => 'test2', :to => 'test1',:url => 'http://example.com')
```
Can anybody please help
Thanks in advance

**Comment by shoaib-iqbal** [comment]
I have been able to solve this by
`    from = 'client:'+ params[:From]
    to = params[:To]
    response = Twilio::TwiML::Response.new do |r|
      r.Dial callerId: from do |d|
        d.Client to
      end
    end
  render xml: response.text`

**Comment by ilanbiala** [comment]
@shoaib-iqbal is there a bug in our library/error in our docs, or is everything working?

**Comment by tmconnors** [comment]
@shoaib-iqbal Call creation comes is available from the`api.v2010.account.calls` context, but there are some helper shortcuts:

```
client.calls.create(:from => 'test2', :to => 'test1', :url => 'http://example.com)
client.api.calls.create(:from => 'test2', :to => 'test1', :url => 'http://example.com)
```
