### ISSUE TITLE
uninitialized constant Twilio::JWT

### ISSUE THREAD

**Issue by devudilip** [twilio/twilio-ruby#283]
Trying to create an access token for video throwing an error.
*** NameError Exception: uninitialized constant Twilio::JWT

> Code

`token = Twilio::JWT::AccessToken.new(account_sid, api_key, api_secret, identity);`

**Comment by tmconnors** [comment]
@devudilip Which version of the library are you using? Please update to the latest, `5.0.0.rc22`, of `twilio-ruby` if you've haven't already.

I noticed your constructor parameters sequence is not right. 

` def initialize(account_sid, signing_key_sid, secret, grants=[], identity: nil, nbf: nil, ttl: 3600, valid_until: nil)`

**Comment by HanggiAnggono** [comment]
also got the same error, running `Twilio.constant` however, only returns the following constants

`[:VERSION, :Util, :TwiML, :TaskRouter, :REST]`

**Comment by devudilip** [comment]
@tmconnors thanks, 

after updating the gem to 5.0.0.rc22  "`Twilio::JWT::AccessToken`" works.

But facing problem with "`Twilio::JWT::AccessToken::VideoGrant`".

`NameError: uninitialized constant Twilio::JWT::AccessToken::VideoGrant
`

**Comment by tmconnors** [comment]
@HanggiAnggono The `Twilio::JWT` module is from the 5.X class of the library, while your constants array is from a 4.X class of the library. We are only supporting security vulnerabilities in 4.X please update to 5.X. You'll need to specify the version as it is a pre-release.

`gem install twilio-ruby -v 5.0.0.rc23`

**Comment by tmconnors** [comment]
@devudilip VideoGrant is part of the `JWT` module, but lives in the `access_token.rb` file. 

`Twilio::JWT::VideoGrant.new` 

Do we have conflicting documentation? I apologize, it will be audited and fixed.

**Comment by devudilip** [comment]
Yes Documentation says it :-)

https://www.twilio.com/docs/api/video/user-identity-access-tokens#ruby

**Comment by tmconnors** [comment]
@devudilip My bad. Additionally, having the `VideoGrant` scoped to `AccessToken` namespace is a much clearer approach. I'll make the switch in `rc-24`, should be released tonight.

**Comment by devudilip** [comment]
Cool thanks @tmconnors. 

I will update and let you know if i face any problem

**Comment by angelicas** [comment]
you should upgrade the docs here https://www.twilio.com/docs/api/video/user-identity-access-tokens#ruby and show that identity is hash, which you can see from looking at the library code but is not clear in this example doc. just wanted to let you know to avoid confusion for others. thanks! :)

**Comment by angelicas** [comment]
just fyi the doc examples here https://www.twilio.com/docs/api/video/user-identity-access-tokens#ruby need to be updated to show that identity is hash, which you can see from looking at the library code itself but is not clear in this example doc. just wanted to let you know to avoid confusion for others. thanks! :)

**Comment by buckmaxwell** [comment]
I am on the latest version 5.0.0.rc23 and am getting, NameError (uninitialized constant Twilio::TwiML::Response).  Twilio and Twilio::TwiML do not throw errors.  Not sure if this is related to this issue.  Any thoughts?

**Comment by ilanbiala** [comment]
@buckmaxwell This is unrelated, but `Twilio::TwiML::Response` isn't a class. The main TwiML classes are `Twilio::TwiML::VoiceResponse` and `Twilio::TwiML::MessagingResponse`. There are some other ones that are useful, so you can look in those files to see what TwiML elements you're looking to create.

**Comment by buckmaxwell** [comment]
@ilanbiala - figured that out with some code digging.  Might be worth making that more clear in the documentation - it's just listed as Twilio::TwiML::Response in the readme (and most everywhere else).. which was a bit deceiving.

**Comment by ilanbiala** [comment]
@buckmaxwell Sorry about that, we're in the process of releasing an all-new Ruby library, which is the next-gen branch, but we have yet to update all the documentation. We'll definitely update the documentation once the library is fully finished.
