### ISSUE TITLE
Uninitialized constant Twilio::REST::RequestError

### ISSUE THREAD

**Issue by jmelkor** [twilio/twilio-ruby#298]
I used gem 'twilio-ruby', '~> 5.0.0.rc26'. The call was successful set to Twilio, but the getting some error when raise occurred.

```
begin
  client = Twilio::REST::Client.new(account_sid, auth_token)
  message = client.api.account.messages.create(from: nil, to: to, body: body)
rescue Twilio::REST::RequestError => e
  print e.message
end

```
Print ```uninitialized` constant Twilio::REST::RequestError```

**Comment by tmconnors** [comment]
@jmelkor Our documentation is outdated, I will fix. Use

`Twilio::REST::TwilioError` or `Twilio::REST::RestError`

**Comment by tmconnors** [comment]
@jmelkor Actually you will need to rescue from `StandardError` because the library is not allowing you to construct the request, not that the request is unsuccessful.

**Comment by skplunkerin** [comment]
@tmconnors are you able to fix the migration guide to also reflect this?

**Guide:** https://www.twilio.com/docs/libraries/ruby/migration-guide

The guide says to change this to `Twilio::REST::RestException` which provides the same error as `Twilio::REST::RequestError`

**Comment by philnash** [comment]
Thanks for pointing that out @skplunkerin! It's sorted now.

**Comment by RealSilo** [comment]
@tmconnors still outdated :(
