### ISSUE TITLE
Attempting to create a channel returns an error

### ISSUE THREAD

**Issue by cmavromoustakos** [twilio/twilio-ruby#302]
I am completely new to twilio so excuse the stupidity if I am doing something wrong.

When I try to create a channel for a give service I get the following error:

    >> service.channels.create(friendly_name: "Chat with booger", unique_name: "Unique-123")
    URI::InvalidURIError: bad URI(is not URI?): https://chat.twilio.com/v2/Services/{:sid=>"ISb94e1005ad134e1e822a9874081f0d7f"}/Channels
    	from (irb):28
    >>

**Comment by tmconnors** [comment]
@cmavromoustakos No worries, the channel creation is syntactically correct. I believe when you're fetching the service context you're incorrectly passing the sid such as:

```
@service = @client.chat.v2.services(:sid=>"ISb94e1005ad134e1e822a9874081f0d7f")
```
Try:

```
@service = @client.chat.v2.services("ISb94e1005ad134e1e822a9874081f0d7f")
```

**Comment by cmavromoustakos** [comment]
Bingo 👍 that was it. Thank you sir
