### ISSUE TITLE
[Regression] LookupClient does not handle numbers with spaces in them

### ISSUE THREAD

**Issue by Firfi** [twilio/twilio-ruby#304]
It seems https://github.com/twilio/twilio-ruby/issues/153 is back;

Code: 

`TWILIO = Twilio::REST::Client.new`

...

`TWILIO.lookups.phone_numbers('123 456 789').fetch(type: 'carrier')`

=>

`URI::InvalidURIError: bad URI(is not URI?): https://lookups.twilio.com/v1/PhoneNumbers/123 456 789`

**Comment by oguzbilgic** [comment]
Is this fixed on v5.1?

**Comment by jingming** [comment]
@Firfi @oguzbilgic thanks for flagging the issue. We've created a ticket to investigate this and we will get back to you as soon as possible.

**Comment by tmconnors** [comment]
@Firfi @oguzbilgic After investigation this is expected behavior - don't include spaces in numbers or encoded them prior to the method call. The helper library is a reflection of the API and you cannot pass a non-encoded URI to the endpoint.
