### ISSUE TITLE
Unable to create invites on a channel.

### ISSUE THREAD

**Issue by cmavromoustakos** [twilio/twilio-ruby#305]
I am getting the following error when trying to create invites. I am using the example provided in the spec test: 

https://github.com/twilio/twilio-ruby/blob/master/spec/integration/chat/v2/service/channel/invite_spec.rb#L92 

    >> channel.invites.create(identity: "gus@indie.ninja")
    Twilio::REST::RestError: [HTTP 404] 20404 : Unable to create record: The requested resource /Services/ISb94e1005ad134e1e822a9874081f0d7f/Channels/CH0b811d04cfe54083b6c1fbf0620662ff/Invites was not found
	from (irb):42

**Comment by cmavromoustakos** [comment]
It appears that the following works:

    >> channel.members.create(identity: "gus@indie.ninja")
    => #<Twilio::REST::Chat::V2::ServiceContext::ChannelContext::MemberInstance:0x007fd3ebbc9de8 @version=#<Twilio::REST::Chat::V2:0x007fd3efe1bd40 @domain=#<Twil.....

The documentation on the rest API resource gave me a hint that the nested resource for invites was member not invites:

https://www.twilio.com/docs/api/chat/rest/invites#action-list


    List All Invites of a Channel

    GET /Services/{Instance SID}/Channels/{Channel SID}/Members

**Comment by efossier** [comment]
@cmavromoustakos Have you also created a user with that identity? Creating an invite with an identity that twilio doesn't know about will result in a 404 with the misleading message above. See the following sequence of calls:

```
irb(main):024:0> @channel.invites.create(identity: "me@twilio.com")
Twilio::REST::RestError: [HTTP 404] 20404 : Unable to create record: The requested resource /Services/ISxxxxxxxxxxxxxxxxx/Channels/CHxxxxxxxxxxxxxxxxx/Invites was not found

irb(main):026:0> @client.chat.v2.services("ISxxxxxxxxxxxxxxxxxx").users.create(identity: "me@twilio.com")
#<Twilio::REST::Chat::V2::ServiceContext::UserInstance:..

irb(main):027:0> @channel.invites.create(identity: "me@twilio.com")
# No Error
=> #<Twilio::REST::Chat::V2::ServiceContext::ChannelContext::InviteInstance:...
```

**Comment by efossier** [comment]
@ajtack This is equivalent to:
```
curl -u ACxxxxxxxxxxxxxxxxxxxxx:<auth> -s https://chat.twilio.com/v2/Services/ISxxxxxxxxxxxxxxxxxxxxx/Channels/CHxxxxxxxxxxxxxxxxxx/Invites -X POST -d Identity=fake@twilio.com | jq

{
  "code": 20404,
  "message": "The requested resource /Services/ISxxxxxxxxxxxxxxxxxxxx/Channels/CHxxxxxxxxxxxxxxxxxxxxxx/Invites was not found",
  "more_info": "https://www.twilio.com/docs/errors/20404",
  "status": 404
}
```

Would it be possible to make the error message more clear that the resource that wasn't found is a user with that identity and not the individual service or channel sids?

**Comment by cmavromoustakos** [comment]
@efossier  re "Have you also created a user with that identity?" No I had not and I suspect that was my issue.

I misunderstood that I needed to create an invite before I add a member to a channel, which was not my intent. I am creating the channel for the users and adding them through the members resource directly.

**Comment by efossier** [comment]
@cmavromoustakos I am going to close this since it seems to be resolved, feel free to reopen if you continue to have issues.
