### ISSUE TITLE
Set timeout for http connections on new 5.0

### ISSUE THREAD

**Issue by cavneb** [twilio/twilio-ruby#306]
We were setting our timeout on for all requests on the version 4.x when instanciating the client:

```
client = ::Twilio::REST::Client.new(timeout: 10)
```

Is there a way to do this in version 5?

**Comment by dougblack** [comment]
Hey @cavneb, we haven't exposed a way to do this the latest version. We'll look into fixing that.

Note that these are client side timeouts though, so it won't cause Twilio to stop processing requests. If, for instance, the client side timeout gets hit while attempting to send a `Message`, the client will give up on the request and won't know if Twilio sent that `Message` or not.

**Comment by NeoPhi** [comment]
Any update on this? We are trying to migrate to v5 and would also like this capability.

**Comment by efossier** [comment]
@cavneb @NeoPhi I am working on a quick PR for this now, in the meantime you can always create a `Twilio::REST::Client` with your own HttpClient which accepts a timeout.

**Comment by efossier** [comment]
Included in release `5.2.2`
