### ISSUE TITLE
Is it possible to add a method for querying messages for a particular member

### ISSUE THREAD

**Issue by cmavromoustakos** [twilio/twilio-ruby#310]
Something along the lines of:

    >> message = service.channels("CHe3eab5c33b7741d5985c99724482a28b").messages(from: "5936ed511e753a227ca39c7b").fetch

**Comment by tmconnors** [comment]
@cmavromoustakos Unfortunately, by definition the endpoint does not currently support this behavior and as result code will not be generated. I recommend emailing help@twilio.com about features requests for Chat.
