### ISSUE TITLE
Finding channel by unique-name does form proper urls

### ISSUE THREAD

**Issue by wiseleyb** [twilio/twilio-ruby#312]
Given a service instance

## works
c = service.channels.create(unique_name: 'bob123').fetch
c.members.list
service.channels(c.sid).members.list

## doesn't work
c = service.channels('bob123').fetch
c.sid # returns a typical sid
c.unique_name # returns bob123
c.members.list

**Comment by daqo** [comment]
Same here.

**Comment by efossier** [comment]
@wiseleyb @daqo Good catch, this should be supported from my understanding of the chat api. @ajtack  Can you confirm? Everything looks ok from the api perspective.

**Comment by ajtack** [comment]
Confirmed, @efossier! This is in line for getting fixed shortly.

**Comment by petercip** [comment]
Hi all, any update on a fix for this issue?

**Comment by jingming** [comment]
@ajtack any updates on this issue?

**Comment by childish-sambino** [comment]
This looks to have been resolved in chat v2. Running the sample code using v2 (`client.chat.v2.services` or simply `client.chat.services`) works.
