### ISSUE TITLE
Add documentation for TwiML SMS response

### ISSUE THREAD

**Issue by teeparham** [twilio/twilio-ruby#314]
With 4.x, I did this to respond to a POST:

```ruby
response = Twilio::TwiML::Response.new do |r|
  r.Sms message
end

render xml: response.text
```

That no longer works. Can you add a simple example that works with 5.0?

**Comment by philnash** [comment]
Sorry for the slow reply here @teeparham. With version 5.x there are now different responses for Voice and Messaging TwiML.

It's not entirely clear whether you are using Voice or Messaging here, as `<Sms>` is available for both. If you are responding to an incoming message, I recommend you change to use [`<Message>`](https://www.twilio.com/docs/api/twiml/sms/message) as `<Sms>` is deprecated. That would look like this:

```ruby
response = Twilio:::TwiML::MessagingResponse.new do |r|
   r.message message_text
end

render xml: response.to_s
```

If it is a voice response, then you are stuck with `<Sms>` for now, despite its deprecation, and you can make this response with:


```ruby
response = Twilio:::TwiML::VoiceResponse.new do |r|
   r.sms message_text
end

render xml: response.to_s
```

Let me know if that helps at all.

**Comment by teeparham** [comment]
Thank you. 

That appears to work for a SMS  response, with one minor change (add `body:` kwarg:)

```
response = Twilio:::TwiML::MessagingResponse.new do |r|
   r.message body: message_text
end

render xml: response.to_s
```

**Comment by philnash** [comment]
Ah yes, you're right! Sorry about that (and for the delay). Just to note, I've updated my answer so that if other's see it they aren't waylaid by my incorrectness.

**Comment by teeparham** [comment]
For anyone finding this issue, while the above block syntax works, chaining looks much better for simple responses:

```ruby
response = Twilio:::TwiML::MessagingResponse.new.message(body: "text")
render xml: response.to_s
```
