### ISSUE TITLE
why change the api?

### ISSUE THREAD

**Issue by taf2** [twilio/twilio-ruby#316]
client.accounts.get('A...')

vs

client.api.accounts('A...').fetch

why?

**Comment by mlund01** [comment]
These exact changes are discussed in the migration guide under Access Resources (the first section). The changes you are referring to specifically have to do with being able to target multiple versions of the api (could do `@client.api` for the latest version, or `@client.v2010` for an older version), and network efficiency (fetch explicitly gets all attributes, where if you don't use fetch, it will just give you a context to work with... i.e. less data unless explicitly asked for)

Here is the guide,

https://www.twilio.com/docs/libraries/ruby/migration-guide
