### ISSUE TITLE
gather with attribute partialResultCallback incorrectly downcased

### ISSUE THREAD

**Issue by nlib** [twilio/twilio-ruby#333]
**Version:**
gem twilio-ruby-5.1.2

### Code Snippet
```ruby
    r = Twilio::TwiML::VoiceResponse.new
    r.gather(input: 'speech', action: url, partialResultCallback: result_url) 
```
creates the following TWIML

```xml
<Gather action="https://zyx" input="speech" partialresultcallback="https:/xyz">
```

The response from Twilio is this:

```
WARNING
  12200 Schema validation warning
DESCRIPTION
 Attribute 'partialresultcallback' is not allowed to appear in element 'Gather'.
```

Either need to fix the ruby gem, or adjust TWIML for downcased attributes.

**Comment by efossier** [comment]
@nlib Hi there, the reason this is happening is that attributes in Twiml constructors are expected to be snake_case, so your code snippet should be:
```
r = Twilio::TwiML::VoiceResponse.new
r.gather(input: 'speech', action: url, partial_result_callback: result_url) 
```

That will properly set the attribute on the generated Twiml.

**Comment by nlib** [comment]
great, thanks!
