### ISSUE TITLE
Stale Lookups API docs reference "Twilio::REST::LookupsClient.new" which does not exist

### ISSUE THREAD

**Issue by f3ndot** [twilio/twilio-ruby#334]
It looks like the Lookups documentation is stale and doesn't properly show you how to instantiate the lookup client.

Would be happy to submit PR if you can show me where the docs are located in source!

**Version:** 5.1.1

### Code Snippet

See example snippet in https://twilio-ruby.readthedocs.io/en/latest/usage/lookups.html#looking-up-details-on-a-phone-number section:

```ruby
require "twilio-ruby"

# Find these values at twilio.com/user/account
account_sid = "AC123123"
auth_token = "secret"

@lookups_client = Twilio::REST::LookupsClient.new account_sid, auth_token
```

### Exception/Log
```
NameError: uninitialized constant Twilio::REST::LookupsClient
```

### Solution

It looks like it's been renamed to `Twilio::REST::Lookups` and expects the original Twilio REST client to work:

```ruby
Twilio.configure do |config|
  config.account_sid = '...'
  config.auth_token = '...'
end
t = Twilio::REST::Client.new
resp = Twilio::REST::Lookups.new(t).phone_numbers(URI.encode('(416) 555-7375')).fetch
resp.phone_number
# => +14165557375
```

**Comment by f3ndot** [comment]
Following up: it looks like all of the code snippets are out of date for 5.1. It doesn't follow the `fetch` paradigm:

What the docs show:

```ruby
response = @lookups_client.phone_numbers.get("+12316851234")
response.country_code
# => "US"
response.phone_number
# => "+12316851234"
response.national_format
# => "(231) 685-1234"
response.url
# => "https://lookups.twilio.com/v1/PhoneNumbers/+12316851234"
```

What it should be:

```ruby
response = @lookups_client.phone_numbers(URI.encode("+12316851234")).fetch
response.country_code
# => "US"
response.phone_number
# => "+12316851234"
response.national_format
# => "(231) 685-1234"
response.url
# => "https://lookups.twilio.com/v1/PhoneNumbers/+12316851234"
```

**Comment by jingming** [comment]
@f3ndot Thanks for flagging the issue. This looks like the old library - please update to the latest `twilio-ruby` and we will work on updating our documentation.

**Comment by synth** [comment]
Has there been any work done on the documentation for Lookups? I looked around, including the version 5.x migration guide and I couldn't find any. 

For anyone else reaching this, we're on Ruby 2.7 and changed two things: 

```ruby
      -- @lookup ||= Twilio::REST::LookupsClient.new(sid, token)
      ++ @lookup ||= Twilio::REST::Lookups.new(client)
```

and

```ruby
      -- response = Recognize::Application.twilio_client.lookup.phone_numbers.get(number)
      ++ encoded_number = URI.encode_www_form_component(number) # Use this instead of URI.encode which is deprecated
      ++ response = Recognize::Application.twilio_client.lookup.phone_numbers(encoded_number).fetch
```

**Comment by JenniferMah** [comment]
Hi @synth 
Here's a [link](https://www.twilio.com/docs/lookup/api) to the documentation around Lookups for ruby 5.X . We don't currently track comments on closed issues so if you have anymore questions please open a new GitHub issue in this repository.

**Comment by synth** [comment]
@JenniferMah Thanks!
