### ISSUE TITLE
Require 'twilio-ruby' results in a loaderror

### ISSUE THREAD

**Issue by yolo-ruby** [twilio/twilio-ruby#337]
**Version:** 5.2.1 ; Ruby 2.3.3 + the required DevKits for the libxml-ruby (3.0.0) gem

### Code Snippet
```ruby
require 'twilio-ruby'
```

### Exception/Log
```
C:\Users\SexyBeast>C:\Users\SexyBeast\Desktop\Ruby1\twilio\test_text.rb
C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:i
 `require': cannot load such file -- libxml_ruby (LoadError)
        from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_re
uire.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libxml-ruby-3.0.0-x64-mingw
2/lib/libxml.rb:8:in `rescue in <top (required)>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/libxml-ruby-3.0.0-x64-mingw
2/lib/libxml.rb:4:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_re
uire.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_re
uire.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/twilio-ruby-5.2.1/lib/twili
-ruby.rb:3:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_re
uire.rb:133:in `require'
        from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_re
uire.rb:133:in `rescue in require'
        from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_re
uire.rb:40:in `require'
        from C:/Users/SexyBeast/Desktop/Ruby1/twilio/test_text.rb:1:in `<main>'
```

### Steps to Reproduce
1. gem install twilio-ruby
2. require 'twilio-ruby'

I have installed everything correctly, using Ruby 2.3.3 and I have correctly installed the required DevKits.

I believe the error is the result of 'libxml_ruby' instead of 'libxml-ruby' however, I am not sure where in the code that would be or even if that is the problem.

**Comment by jingming** [comment]
@yolo-ruby Thanks for flagging this issue. We've opened a ticket internally to investigate this issue.

**Comment by yolo-ruby** [comment]
Hi, @jingming . Does this mean you are (or someone else is) actually investigating this or you are just saying that so you can close this issue?

If this actually is being investigated then you probably can predict that 5.2.3 isn't working for me either.

I am using a 64bit computer and I am using 64bit version of Ruby and the 64bit versions of the DevKits. Probably unimportant but I forgot to put it in the actual post.

Thanks

**Comment by tmconnors** [comment]
@yolo-ruby Hello, I have investigated your issue and unfortunately am unable to reproduce on a Windows 64bit machine running 64bit Ruby 2.3.X. This seems to be an issue with `libxml-ruby` being properly built - I'd recommend verifying that is successfully installing. Here is some potential references: 

http://rajmohanb.blogspot.com/2008/02/libxml-ruby-gem-installation-issues.html
https://stackoverflow.com/questions/22417544/having-trouble-installing-libxml-ruby-on-windows

**Comment by KapilMetacube** [comment]
Any update on this.
Still encountering the [issue](https://github.com/xml4r/libxml-ruby/issues/42).
Adding related issue #322

**Comment by philnash** [comment]
Good news, due to other reasons, alongside difficulty all round with `libxml_ruby` [this PR will be repacing `libxml_ruby` with Nokogiri](https://github.com/twilio/twilio-ruby/pull/375). Hopefully that will make life easier :)

**Comment by KapilMetacube** [comment]
That's a great news for me @philnash. `libxml_ruby` error was occurring for me only because of twilio-ruby being dependent on it.
Your PR will make my life easier.
Hoping it to be merged soon.
Thanks

**Comment by philnash** [comment]
Hey @KapilMetacube, the latest version of the gem, [5.5.0](https://rubygems.org/gems/twilio-ruby/versions/5.5.0), has been released and uses Nokogiri instead of `libxml_ruby`. Please upgrade and I hope it does make your life easier. 🙂

**Comment by KapilMetacube** [comment]
Thanks, @philnash for informing. (Was using your branch) 😇
