### ISSUE TITLE
JWT 2.0

### ISSUE THREAD

**Issue by Alagaesia93** [twilio/twilio-ruby#343]
Hi guys,

Jwt 2.0 has come out! [https://github.com/jwt/ruby-jwt](url) 

Could you please update your dependencies? 

Thank you very much 🥇

**Comment by jingming** [comment]
@Alagaesia93 Thanks for bringing this up. We've opened a ticket internally to investigate and will get back to you as soon as we can.

**Comment by anazar** [comment]
@jingming Any update on this?  JWT is now on 2.1.0.

**Comment by gkats** [comment]
Hey @jingming (or anybody else interested in this), I took a naive shot at just updating the version dependencies in the gem's specification file. Please see #372.

I'm running ruby 2.4.1p111.

Gem builds successfully.
```
$ gem build twilio-ruby
  Successfully built RubyGem
  Name: twilio-ruby
  Version: 5.4.5
  File: twilio-ruby-5.4.5.gem
```
Bundle succeeds
```
$ bundle
Bundle complete! 8 Gemfile dependencies, 24 gems now installed.
```
And tests seem to pass
```
$ make test
1896 examples, 0 failures
```
I've already used the newly built gem in a personal project and had success sending an SMS through the API. 

From a quick `$ git grep ::JWT` it looks like the only places that the jwt gem's JWT class is used are
- `lib/twilio-ruby/jwt/jwt.rb` (JWT.encode)
- `spec/jwt/client_capability_spec.rb` (JWT.decode)
I guess the JWT API for these two methods hasn't changed. 

I hope the above helps. Happy to look further into this in case I'm missing anything.
