### ISSUE TITLE
Bug: no results when passing exclude_local_address_required flag for available numbers

### ISSUE THREAD

**Issue by alextilson** [twilio/twilio-ruby#345]
### Version affected
4.13 (known), need to ensure this was fixed in subsequent releases 

### Issue Summary
Passing the `exclude_local_address_required` flag with `available_phone_numbers.get('AU').local.list` returns null, regardless if flag is true or false. Requests without the flag work as expected.

Likely affects countries other than AU as well.

### Examples
2.3.1 :019 > TwilioHelper.twilio_client.account.available_phone_numbers.get('AU').local.list( exclude_local_address_required: true)
=> []

2.3.1 :020 > TwilioHelper.twilio_client.account.available_phone_numbers.get('AU').local.list( exclude_local_address_required: false)
=> []

In both cases, when exclude_local_address_required is set to true, or to false, 0 results are returned. However, when executing the following, we do see results.

2.3.1 :021 > TwilioHelper.twilio_client.account.available_phone_numbers.get('AU').local.list
2.3.1 :021 > TwilioHelper.twilio_client.account.available_phone_numbers.get('AU').local.list
=> [<Twilio::REST::AvailablePhoneNumber @path=/2010-04-01/Accounts/{SID}/AvailablePhoneNumbers/AU/Local/>, <Twilio::REST::AvailablePhoneNumber @path=/2010-04-01/Accounts/{SID}/AvailablePhoneNumbers/AU/Local/>, <Twilio::REST::AvailablePhoneNumber @path=/2010-04-01/Accounts/{SID}/AvailablePhoneNumbers/AU/Local/>, <Twilio::REST::AvailablePhoneNumber @path=/2010-04-01/Accounts/{SID}/AvailablePhoneNumbers/AU/Local/>]

**Comment by jingming** [comment]
@alextilson thanks for flagging the issue. We've forwarded this to the appropriate internal team.
