### ISSUE TITLE
Misleading Error: The 'From' number is not a valid phone number, shortcode, or alphanumeric sender ID.):

### ISSUE THREAD

**Issue by erlandsona** [twilio/twilio-ruby#348]
# Issue 
I had everything hooked up properly, then today made some small changes that affected the value that was being passed into the `to` field of the twilio arguments but got an error message indicating something was wrong with the `from` field.

# Resolution 
Preferably, the gem should throw an error related to the to field being passed an improper value.

**Version:**
* Twilio-Ruby 5.2.3
* Ruby 2.3.4p301
* Rails 5.1.3

### Code Snippet
```ruby
  def perform(client, body, to)
    twilio = Twilio::REST::Client.new(
      client.twilio_account_sid,
      client.twilio_auth_token
    )
    twilio.api.account.messages.create(
      from: client.twilio_phone_number,
      to: to, # to here was {phone_number: '1234567890'}. I forgot to pull the number out of the hash.
      body: body
    )
  end
```

### Exception/Log
```
Twilio::REST::RestError (Unable to create record: The 'From' number +...ellided... is not a valid phone number, shortcode, or alphanumeric sender ID.):
/box/gems/twilio-ruby-5.2.3/lib/twilio-ruby/framework/version.rb:157:in `create'
/box/gems/twilio-ruby-5.2.3/lib/twilio-ruby/rest/api/v2010/account/message.rb:71:in `create'
/messaging/app/jobs/twilio_job.rb:13:in `perform'
```

### Steps to Reproduce
1. Put in a bad type of value for the `to:` field. EG: Hash or array or something not a string.

**Comment by efossier** [comment]
@erlandsona Sorry for the confusion, this is the error message returned by the API. I've flagged this issue with responsible team but your best bet is to reach out at help@twilio.com to make sure they do it ;)

**Comment by Mabooka** [comment]
I am getting this (and am totally frustrated) :

`>>> TO = "+15005550006"
>>> FROM = "+15005550006"
>>> 
>>> client.api.account.messages.create(to=TO, from_=FROM, body='Hi there')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda/lib/python2.7/site-packages/twilio/rest/api/v2010/account/message/__init__.py", line 92, in create
    data=data,
  File "/anaconda/lib/python2.7/site-packages/twilio/base/version.py", line 209, in create
    raise self.exception(method, uri, response, 'Unable to create record')
twilio.base.exceptions.TwilioRestException: 
HTTP Error Your request was:

POST /Accounts/aaaaaaaaaaaaaaaaXXXXXXXXXXXXXXXX/Messages.json

Twilio returned the following information:

Unable to create record: The 'To' number +15005550006 is not a valid phone number.

More information may be available here:

https://www.twilio.com/docs/errors/21211


>>> 
`

**Comment by mcjoshi** [comment]
Iam also getting same error as @Mabooka

**Comment by amsimon** [comment]
This is still happening. Very misleading and cost me hours of debugging for nothing.

**Comment by igbanam** [comment]
@Mabooka @mcjoshi @amsimon did you find a solution to this issue yet? The same error is blowing up my AirBrake. I am using version 5.6.1 on a project and I'm inclined to thinking it may be solved by a version upgrade. But I wanted to confirm with you first
