### ISSUE TITLE
V5.3.0 Broke my build: Uncaught exception: undefined method `configure' for Twilio:Module

### ISSUE THREAD

**Issue by rkiller** [twilio/twilio-ruby#349]
Seems like the latest version broke my build. Is this not supported anymore?:

Twilio.configure do |config|
  config.account_sid = XXXXX
  config.auth_token = XXXXX
end

**Comment by trautwein** [comment]
Same issue here.

**Comment by efossier** [comment]
@trautwein @rkiller Apologies for breaking your build, we identified these files as legacy code from the old libraries however it does seem that our docs currently reference some of this behavior. We'll go back and audit what was removed and ensure it is indeed legacy.

**Comment by taf2** [comment]
If Twilio.configure is going to be legacy... you might consider also updating the README.md

**Comment by nil0bject** [comment]
https://github.com/twilio/twilio-ruby/pull/350

**Comment by efossier** [comment]
@kevinelliott We identified that file incorrectly as dead code left over from the previous version, since we've moved to auto-generating most of our client code we thought this code no longer worked in the new client and so should be removed.

The preferred way to configure a client is to pass your credentials when instantiating the client rather than setting them globally:
```ruby
# set up a client to talk to the Twilio REST API
@client = Twilio::REST::Client.new account_sid, auth_token
```

We'll be adding back the global configure functionality as a deprecated feature in the next release, is there a use case in Rails that you must globally configure the credentials?

**Comment by kevinelliott** [comment]
We use this in an application that pulls the account details from the `ENV`, and configuring via an initializer allows the config to be simple. We could pass the account details throughout the application where a client is initialized, though there is some slight repetition to do that. Also, we could wrap the client initialization into a new application controller method or helper. Neither is ideal, but also not a huge problem. It is not important enough for me to make a case for keeping the configure block.

**Comment by taf2** [comment]
the real issue is breaking backwards compatibility...

**Comment by fredngo** [comment]
Agreed with @kevinelliott. The `Twilio.configure` block makes it easy to pull account details from the `ENV`.

Without it, we have to repeat code all over the place, as there are many potential places in the application code where I will now have to call

```
client = Twilio::REST::Client.new ENV['account_sid'], ENV['auth_token']
```
instead of simply

```
client = Twilio::REST::Client.new
```

**Comment by taf2** [comment]
It might make sense to have another library that sits on top of the twilio ruby library that for example defines the configure method.... and other higher level rubyisms on top of the auto generated library...

**Comment by efossier** [comment]
Thanks for the feedback everyone, we'll keep that in mind when deciding our next move re: the configure block. It will definitely be added back at least temporarily in the next release to fix your builds. Apologies again for the breaking change, it was not our intention to do so.

**Comment by philnash** [comment]
Hey everyone, version 5.3.1 has been released and returns the `configure` block to the library.

**Comment by nil0bject** [comment]
For those keeping notes, the configure block in an application initialiser is not really the best. I know it's a standard practice for rails, but this is twilio-ruby, not twilio-rails.

If you don't want to use the configure block, but don't want to repeat your environment variables everywhere, then:
```
module Notify
  module Models
    class Sms
      def self.call
        client = Twilio::REST::Client.new ENV['TWILIO_ACCOUNT_SID'], ENV['TWILIO_AUTH_TOKEN']
        client
      end
    end
  end
end

module Notify
  class Sms
    def self.call(to, body, args = {})
      return if to.empty? || Rails.env.development? #change these conditions for not sending the sms
      notification = ::Notify::Models::Sms.call.messages.create(
        { from: ENV['TWILIO_SEND_MESSAGES_FROM'], to: to, body: body }.merge(args)
      )
      notification
    end
  end
end

::Notify::Sms.call('+601234567890', 'I'm not assimilated')
```

**Comment by kevinelliott** [comment]
You have a nested single-quote, so that code will break ;)
