### ISSUE TITLE
Twilio configuration block is deprecated but no alternative or rationale is presented

### ISSUE THREAD

**Issue by badosu** [twilio/twilio-ruby#354]
After migrating to latest `twilio-ruby` version started receiving deprecation messages.

So I looked for some place for an explanation on why and how to fix this. I found no documentation on how to configure `Twilio` globally nor an explanation telling that global configuration is not recommended anymore, the wiki even presents the block configuration still (https://github.com/twilio/twilio-ruby/wiki/Util).

So I'd like to know if there's an alternative for global configuration or if this is not going to be supported on later versions.

**Version:** 5.3.1

### Exception/Log
```
'Twilio::Util::Configuration.account_sid' has been deprecated. Please do not use the configure block.
'Twilio::Util::Configuration.auth_token' has been deprecated. Please do not use the configure block.
```

### Steps to Reproduce
1. Configure twilio with a block
2. Receive deprecation messages on firing up the library
3. Try to find an alternative and do not find it

**Comment by efossier** [comment]
@badosu Sorry for the confusion, we've decided to un-deprecate the configuration block in the next release due to popular demand and a lack of coordination on our part with the docs team as you noted. We don't have any plans to remove it in the future at this time so you can continue relying on it.

**Comment by badosu** [comment]
@efossier Thanks for the clarification!
