### ISSUE TITLE
All Twiml parameter names are being lowercased, resulting in multiple warning per call

### ISSUE THREAD

**Issue by vt-gpatrick** [twilio/twilio-ruby#358]
**Version:**

5.4

We use the "traditional" way of creating TwiML responses, with camel cased parameters.  E.g. for responding to an incoming call:

```
        Twilio::TwiML::VoiceResponse.new do |r|
          r.dial(callerId: <some_id>, timeout: <timeout>, record: 'record-from-ringing-dual',
                 action: <url>, method: :post) do |d|
            d.client(<client id>,
                     statusCallbackEvent: 'ringing',
                     statusCallback: <url>,
                     statusCallbackMethod: :post,
                     url: call_answered_location, method: :post)
          end
        end
```

This results in a working call, but 4 warnings are logged in the Twilio logs:
E.g:

WARNING
  12200 Schema validation warning
DESCRIPTION
 Attribute 'statuscallbackmethod' is not allowed to appear in element 'Client'.

Our `statusCallbackMethod` has been lowercased `statuscallbackmethod`

And the same for `callerid`, `statuscallback`, and `statuscallbackevent` param names...

The problem is in /lib/twilio-ruby/twiml/twiml.rb, in the `to_lower_camel_case` method.  It assumes parameters names are in a words_with_underscore_separators format.  If there are no underscores, the parameter is `.downcase`d.

Here's one way of fixing it, which I've tested:

```
        def self.to_lower_camel_case(symbol)
          # Symbols don't have the .split method, so convert to string first
          result = symbol.to_s
          pieces = result.split('_')
          if pieces.length > 1
            result = pieces.map(&:capitalize).join
            result[0].downcase + result[1..result.length]
          else
            result
          end
        end
```

**Comment by efossier** [comment]
@vt-gpatrick Thanks for flagging this, we'll get a fix out asap.

**Comment by efossier** [comment]
See https://github.com/twilio/twilio-ruby/pull/360
