### ISSUE TITLE
Option for Logging Reqest/Response

### ISSUE THREAD

**Issue by sshaw** [twilio/twilio-ruby#361]
### Feature Request

I didn't see a option in the docs to log request/response. After quick look at the [source code](https://github.com/twilio/twilio-ruby/blob/732ee034fbeb6396f9ed5b8bef141c410b5af0a6/lib/twilio-ruby/rest/base_client.rb), I don't see an option for this.

**Comment by jmctwilio** [comment]
@sshaw We don't have any logging enabled in the source code.  You should be able to access the request and response objects allowing you to log them at your discretion.  They're available as `last_request` and `last_response` on the `client` object.
