### ISSUE TITLE
TwiML::FaxResponse is not required by default

### ISSUE THREAD

**Issue by Wylan** [twilio/twilio-ruby#362]
The FaxResponse TwiML class is not included by `twilio-ruby.rb` by default. You have to manually require `twilio-ruby/twiml/fax_response` before usage.

**Version:** 5.4.2

### Code Snippet
```ruby
Twilio::TwiML::FaxResponse.new
```

### Exception/Log
```
NameError: uninitialized constant Twilio::TwiML::FaxResponse
```

### Steps to Reproduce
1. Create a new instance of `Twilio::TwiML::FaxResponse.new`
2. Receive NameError

**Comment by guillaume-tgl** [comment]
Any plan to fix this issue?

**Comment by childish-sambino** [comment]
Working on a fix now.
