### ISSUE TITLE
making call from skype to twilio

### ISSUE THREAD

**Issue by tuanmobilefolk** [twilio/twilio-ruby#364]
**Version:**

### Code Snippet
```ruby
    call = client.calls.create(
      to: phone_number_to.phone_number,
      from: raw_phone_number_from,
      url: request.original_url+'/incoming_call',
      method: 'POST'
      )

  def client
    @client ||= Twilio::REST::Client.new(Settings.twilio_api_key, Settings.twilio_api_secret, Settings.twilio_account_sid)
    return @client
  end
```

### Exception/Log
```
Twilio::REST::RestError (Unable to create record: The source phone number provided, +19102943009, is not yet verified for your account. You may only make calls from phone numbers that you've verified or purchased from Twilio.):

```

**Comment by dkundel** [comment]
Hi @tuanmobilefolk,

You can only start a phone call with the REST API from an actual Twilio number. Only the `to` target number can be a non-Twilio number.

What precisely are you trying to do? Maybe I can help you.

Cheers,
Dominik

**Comment by tuanmobilefolk** [comment]
@dkundel 
Thank you for your help. I wanna describe more detail what i want to do:
In my app, When someone call to a twilio number in my app from another skype number or from another twilio number. How can I make a call?

I saw it in python and I already tested it but I try to implement in ruby it not worked:

import os
from flask import Flask, request
from twilio.jwt.access_token import AccessToken, VoiceGrant
from twilio.rest import Client
import twilio.twiml

ACCOUNT_SID = 'AC21a90870ce086440cb9d00c4afef4735'
API_KEY = 'SK92681dda98b66f2dc56826713bf45a0f'
API_KEY_SECRET = 'ktcHmjgZr8wihYDlznOAeppCkdNXgtsR'
PUSH_CREDENTIAL_SID = 'CR9cba08819b748b652f1caff25d672dd4'
APP_SID = 'APe2e5f4fe60d954c9b553b94510097edf'


IDENTITY = 'voice_test'
CALLER_ID = 'quick_start'

app = Flask(__name__)

@app.route('/accessToken')
def token():
  account_sid = os.environ.get("ACCOUNT_SID", ACCOUNT_SID)
  api_key = os.environ.get("API_KEY", API_KEY)
  api_key_secret = os.environ.get("API_KEY_SECRET", API_KEY_SECRET)
  push_credential_sid = os.environ.get("PUSH_CREDENTIAL_SID", PUSH_CREDENTIAL_SID)
  app_sid = os.environ.get("APP_SID", APP_SID)

  grant = VoiceGrant(
    push_credential_sid=push_credential_sid,
    outgoing_application_sid=app_sid
  )

  token = AccessToken(account_sid, api_key, api_key_secret, IDENTITY)
  token.add_grant(grant)

  return str(token)

@app.route('/outgoing', methods=['GET', 'POST'])
def outgoing():
  resp = twilio.twiml.Response()
  resp.say("Congratulations! You have made your first oubound call! Good bye.")
  return str(resp)

@app.route('/incoming', methods=['GET', 'POST'])
def incoming():
  resp = twilio.twiml.Response()
  resp.say("Congratulations! You have received your first inbound call! Good bye.")
  return str(resp)

@app.route('/placeCall', methods=['GET', 'POST'])
def placeCall():
  account_sid = os.environ.get("ACCOUNT_SID", ACCOUNT_SID)
  api_key = os.environ.get("API_KEY", API_KEY)
  api_key_secret = os.environ.get("API_KEY_SECRET", API_KEY_SECRET)

  client = Client(api_key, api_key_secret, account_sid)
  call = client.calls.create(url=request.url_root + 'incoming', to='client:' + IDENTITY, from_='client:' + CALLER_ID)
  return str(call.sid)

@app.route('/', methods=['GET', 'POST'])
def welcome():
  resp = twilio.twiml.Response()
  resp.say("Welcome to Twilio")
  return str(resp)

if __name__ == "__main__":
  port = int(os.environ.get("PORT", 5000))
  app.run(host='0.0.0.0', port=port, debug=True)

**Comment by philnash** [comment]
Are you still having trouble with this? I'm looking to close old issues.
