### ISSUE TITLE
Phone Number lookups should take parameters

### ISSUE THREAD

**Issue by serene** [twilio/twilio-ruby#366]
In prior versions of the gem (~4.0), you could call
`Twilio::REST::LookupsClient.new.phone_numbers.get(phone_mobile.to_s, type: 'carrier')`
to get carrier information about a phone number. 

The new syntax
`Twilio::REST::Client.new.lookups.phone_numbers(phone_mobile.to_s)`
does not allow the addition of other parameters, which the API does support.

**Comment by sergiopantoja** [comment]
I was able to do it like this:

```ruby
client = Twilio::REST::Client.new(...)
client.lookups.v1.phone_numbers(phone_mobile).fetch(type: 'carrier')
```

**Comment by Baril27** [comment]
I am having the same issue after upgrading to `4.13.0`. I am now unable to pass `type: 'carrier'` into the lookup and I receive an argument error.

`Twilio::REST::LookupsClient.new(...).phone_numbers.get(mobile_number, type: 'carrier')`

returns

`ArgumentError: wrong number of arguments (given 2, expected 1)`

**Comment by philnash** [comment]
The correct way to do this is as @sergiopantoja wrote, with a `fetch` with the options.

@Baril27 That should still work in version 4.13 (the [signature of the method didn't change](https://github.com/twilio/twilio-ruby/blob/4.13.0/lib/twilio-ruby/rest/lookups/phone_numbers.rb#L8)). I recommend you upgrade to version 5 to get the latest updates though.
