### ISSUE TITLE
Docs outdated

### ISSUE THREAD

**Issue by mattes** [twilio/twilio-ruby#368]
The example code here doesn't work. It's outdated. 

https://www.twilio.com/docs/api/messaging/send-messages?code-sample=code-send-a-message-with-an-image-url&code-language=rb&code-sdk-version=5.x

**Comment by rept** [comment]
Same with this code on this page: https://www.twilio.com/docs/api/video/identity

```
token = Twilio::JWT::AccessToken.new(account_sid, api_key, api_secret, [], identity);
ArgumentError: wrong number of arguments (given 5, expected 3..4)
```

**Comment by efossier** [comment]
@atbaker Does your team own these pages?

**Comment by TeTiRoss** [comment]
@rept if you are following this example: 
```ruby
token = Twilio::JWT::AccessToken.new ACCOUNT_SID, API_KEY_SID, API_KEY_SECRET,
    ttl=3600,
    identity='example-user'
```
and get ```ArgumentError: wrong number of arguments (given 5, expected 3..4)```, that is because of mistake in this example code.
You should write keyword args with **colon**, not equal sign.
Like this: ```identity: 'example-user'``` instead of ```identity='example-user'```

**Comment by gmulliez** [comment]
Hi, thanks for your post, here is how I use it :

token = Twilio::JWT::AccessToken.new account_sid, api_key, api_secret, ttl: 3600, identity: 'gregoire@convers.com'

**Comment by joliveros** [comment]
Hi everyone,

If you use keyword arguments you can avoid this issue and not have to guess the order of the function arguments: https://stackoverflow.com/questions/15062570/when-to-use-keyword-arguments-aka-named-parameters-in-ruby
