### ISSUE TITLE
Return value for `context.delete` always `true`?

### ISSUE THREAD

**Issue by jayschab** [twilio/twilio-ruby#370]
**Version:** 5.4.4

Hi there. I have a question regarding the comments, and consequently, the documentation for all of the instance `context.delete` calls. Currently the code for all the `delete` methods are:

```ruby
  # @return [Boolean] true if delete succeeds, true otherwise
  def delete
    @version.delete('delete', @uri)
  end
```
I assume the comment/generated docs should read "true if delete succeeds, **false** otherwise". Can you please confirm?

I discovered this looking at the documentation [here](https://www.twilio.com/docs/libraries/reference/twilio-ruby/5.4.4/Twilio/REST/Api/V2010/AccountContext/RecordingContext.html#delete-instance_method)

Thanks!

**Comment by childish-sambino** [comment]
Ha! That's a funny one. You're right that it should be `false otherwise`. I'll work on a PR.
