### ISSUE TITLE
OutgoingClientScope params bug or naming issue

### ISSUE THREAD

**Issue by cuddlyogre** [twilio/twilio-ruby#373]
When using the params in OutgoingClientScope only actually uses the first set value. In my example, param_1 will be the only one received by twilio and sent to the action url specified in the TWIML. The others are ignored or stripped, I'm not sure which. 

The argument being named params and it being a hash leads me to believe it is not supposed to only accept one value. V4 of twilio-ruby did not have this issue.

**Version:**
5.4.5

### Code Snippet
```ruby
params = {param_1: 'xxx', param_2: 'xxx', param_3: 'xxx'}
Twilio::JWT::ClientCapability::OutgoingClientScope.new(app_sid, current_user.id.to_s, params)
```

**Comment by alexcchan** [comment]
PR https://github.com/twilio/twilio-ruby/pull/385
