### ISSUE TITLE
Can't install twilio-ruby gem on JRUBY

### ISSUE THREAD

**Issue by zoras** [twilio/twilio-ruby#374]
As `twilio-ruby > '5.0.0'` depends on `libxml-ruby` C extension, it can't be installed on Jruby platform.

Any alternative to C code or java platform specific gem will be really appreciated.

Reference: https://www.ruby-forum.com/topic/156622

**Comment by philnash** [comment]
I've made PR #375 to change from using `libxml-ruby` to `nokogiri` and hopefully fix this for you.

It might take a while to get this in, as it actually requires a change in a generated file, but this proof should work. You could even try installing the gem from my branch if you need experimental support right now.

**Comment by philnash** [comment]
Hey @zoras, [`twilio-ruby >= 5.5.0`](https://rubygems.org/gems/twilio-ruby/versions/5.5.0) now uses Nokogiri in place of `libxml_ruby` so you should be able to use it successfully on JRuby now.

I'm going to close this issue, but do please open it again if it still isn't working.

**Comment by zoras** [comment]
Awesome! Thanks @philnash 😄
