### ISSUE TITLE
Unable to fetch room participants

### ISSUE THREAD

**Issue by rissem** [twilio/twilio-ruby#378]
**Version:**
5.4.5
### Code Snippet
```ruby
client.video.rooms('*****************').participants().fetch()
```

### Exception/Log
```
NoMethodError: undefined method `fetch' for #<Twilio::REST::Video::V1::RoomContext::RoomParticipantList:0x007f89d50cac40>
```

### Steps to Reproduce
1. Create Twilio client and attempt to fetch participants.

**Comment by vincentwoo** [comment]
To elaborate on Mike's request, it appears that the API has some notion of the participants in a video room, but that the ruby client doesn't have a wrapped way to access it yet. This seems like an oversight, is this by design?

**Comment by alexcchan** [comment]
IIt looks like the library handles this with 2 different methods, depending on whether you are getting a list or a single participant.

```
client.video.rooms('*****************').participants().list()
```

```
client.video.rooms('*****************').participants('Alice').fetch()
```

The docs were just published but some of the Ruby samples are incorrect.

https://www.twilio.com/docs/api/video/participants

**Comment by childish-sambino** [comment]
Doc samples are now correct.
