### ISSUE TITLE
Twilio::TwiML::MessagingResponse New Line Not Working

### ISSUE THREAD

**Issue by antonhalim** [twilio/twilio-ruby#379]
All, I am using `Twilio::TwiML::MessagingResponse` to reply to incoming SMS, the content of the SMS must have new lines. tried multiple ways, and nothing is working. Basically a string response of `Hello\n\nWorld`=>`HelloWorld`. Even with the old xml hack `<![CDATA[ ]]>` that some ppl claimed to be working from #76, or like how it's clearly stated in this [doc](https://support.twilio.com/hc/en-us/articles/223181468-How-do-I-add-a-line-break-in-my-SMS-message-) stating that I only need to use "\n" and it will be interpolated as a new line.

**None** of these methods work:
1. Follow the [docs](https://support.twilio.com/hc/en-us/articles/223181468-How-do-I-add-a-line-break-in-my-SMS-message-).
2. Using `<![CDATA[ ]]>`.
3. Using [XML new line encoding](https://stackoverflow.com/questions/10917555/adding-a-new-line-break-tag-in-xml) or [this issue](https://github.com/twilio/twilio-ruby/issues/54): `&#xD;`, `&#xA;`, `%0a`.
4. HTML `<br/>` tag.

I am confused. What is the best way to create a messaging response with new lines?

**Version:**
5.5.1

### Code Snippet
<img width="831" alt="screen shot 2017-12-11 at 6 18 49 pm" src="https://user-images.githubusercontent.com/10498035/33864413-6234e790-dea1-11e7-8b9b-c526447105fe.png">

### Steps to Reproduce
1. Create a new Twilio::TwiML::MessagingResponse
2. Add body with new line.
3. Expecting the message body has a new line, but it's sanitized

**Comment by lemuelbarango** [comment]
I think this issue was as a result of the last PR. @philnash

https://github.com/twilio/twilio-ruby/pull/375

**Comment by antonhalim** [comment]
@lemuelbarango Thank you for the quick response!

**Comment by philnash** [comment]
Ack! I did break this and I apologise. I'll see what I can do to get this PR in as soon as possible.

**Comment by antonhalim** [comment]
@philnash No worries. Can't wait to get this fixed!

**Comment by greysteil** [comment]
Just ran into this. Any progress on a fix?

**Comment by antonhalim** [comment]
@philnash @efossier I am not sure with the status of this fix. I working and ongoing production app that relies on this library and this fix. Maybe someone can lmk which version that's not affected by this bug.

**Comment by antonhalim** [comment]
@philnash Glad to have you back! I can't wait for the updates. 😄

**Comment by philnash** [comment]
Hey everyone, this has all been fixed as of #386 and released as Twilio Ruby 5.7.0. You can check out the [messaging response test](https://github.com/twilio/twilio-ruby/blob/5.7.0/spec/twiml/messaging_response_spec.rb#L155-L170) that makes sure this works too.

Apologies this took a while, but you should be able to upgrade, get the best of the latest in the gem and now maintain those new lines.
