### ISSUE TITLE
How to mock sending sms when testing with RSpec ?

### ISSUE THREAD

**Issue by Mohammed-Eliass** [twilio/twilio-ruby#383]
I'm using this versions:

    rspec (3.7.0)
    twilio-ruby (5.6.0)
    rails (5.1.4)

and I'm looking for a guide on how to mock sending sms when testing, because I got this error when the test reach create Twilio client:
        
    Twilio::REST::RestError:
            Unable to create record: The requested resource /2010-04-01/Accounts//Messages.json was not found

**Comment by sergiopantoja** [comment]
Here's one guide: https://robots.thoughtbot.com/testing-sms-interactions

Another route to consider is using the [VCR](https://github.com/vcr/vcr) gem to mock the HTTP responses.

**Comment by LizPrescott** [comment]
Hi! I was having the same issue. Following the instructions from the link gives me a NoMethodError on 'messages.'
Adding the .api.accounts that the docs here suggest gives me NoMethodErrors on those. Any other ideas?

**Comment by sergiopantoja** [comment]
@LizPrescott Would you mind posting a code sample?

**Comment by Mohammed-Eliass** [comment]
@LizPrescott  I have posted a question on Stackoverflow, long time ago!

[this is the question](https://stackoverflow.com/questions/48364728/how-to-fix-twiliorestresterror-while-testing-with-rspec)

I hope this will help you!

**Comment by Mohammed-Eliass** [comment]
What about doing the same as :
        
            class TwilioAdapter

              attr_reader :client
              def initialize(client = Twilio::REST::Client.new)
                @client = client
              end

              def send_sms(body:, to:, from: Rails.application.secrets.twilio_phone_number)
                client.messages.create(
                  from: from,
                  to:   to,
                  body: body,
                )
              end

            end

and when ever you want to use 'client' just use it as variable, cause we already instantiate it!
