### ISSUE TITLE
Faraday version constraint bump...

### ISSUE THREAD

**Issue by ghost** [twilio/twilio-ruby#392]
Just wondering if there's a strict reason for pegging faraday on the 0.9 minor tag... currently trying to run through some gem updates and this is a requirement.  Happy to submit a PR if folks are open to adjusting the gemspec.  The only major breaking change I see is dropping ruby 1.8 support ( https://github.com/lostisland/faraday/releases )

Looks like twilio version 3.13.0 way back in 2014 dropped ruby 1.8 support anyways :)
https://github.com/twilio/twilio-ruby/blob/master/CHANGES.md#version-3130

**Version: 5.7.2**

**Comment by philnash** [comment]
Hey! Sorry for the slow reply. Please do feel free to send in a PR (that'll let TravisCI have a go at it). An initial glance looks to me like it should just work though. Thanks!

**Comment by childish-sambino** [comment]
Latest spec calls for `faraday ~> 0.9` which pulls the latest `0.X` release (currently `0.15.4`).
