### ISSUE TITLE
[HTTP 400] 21620 : Unable to create record Media urls. Multiple images in MMS broken in 5.8.0

### ISSUE THREAD

**Issue by ramaboo-deliv** [twilio/twilio-ruby#395]
Sending multiple images for an SMS fails with the following exception:

```
[HTTP 400] 21620 : Unable to create record
Media urls: ["https://pbs.twimg.com/media/DZ8RuvhVoAAxYXz.jpg", "https://c1.staticflickr.com/3/2899/14341091933_1e92e62d12_b.jpg"] are invalid. Please use only valid http and https urls
https://www.twilio.com/docs/errors/21620
```

I do not believe this error to be correct as I tested sending each image separately and that worked. I have tried a half dozen combinations and all the images work when sent alone but all combinations fail when multiple images are sent. Which according to the docs here http://twilio-ruby.readthedocs.io/en/latest/usage/messages.html is possible

5.8.0

### Code Snippet
```ruby
options = {
        to: user.cellphone,
        from: Rails.configuration.twilio_driver_message_number,
        body: 'does not matter',
        media_url: ['https://pbs.twimg.com/media/DZ8RuvhVoAAxYXz.jpg', 'https://c1.staticflickr.com/3/2899/14341091933_1e92e62d12_b.jpg'] # this is what fails. A single image works but an array does not.
      }

      client = ::Twilio::REST::Client.new(Rails.configuration.twilio_account_sid, Rails.configuration.twilio_auth_token)

        client.api.account.messages.create(options)

```

### Exception/Log
```
[HTTP 400] 21620 : Unable to create record
Media urls: ["https://pbs.twimg.com/media/DZ8RuvhVoAAxYXz.jpg", "https://c1.staticflickr.com/3/2899/14341091933_1e92e62d12_b.jpg"] are invalid. Please use only valid http and https urls
https://www.twilio.com/docs/errors/21620
```

### Steps to Reproduce
1. Send a normal message with one url as the media_url
2. Change that message to send an array of urls
3. Array of url will fail.

**Comment by ramaboo-deliv** [comment]
This works now. Was there some kind of outage?

**Comment by ruhilambe** [comment]
How was this solved?

Facing the same error for array of urls in the MediaUrl parameter.

**Comment by childish-sambino** [comment]
@ruhilambe If it's a transient error, then it's unlikely to be an issue with this client library. Recommend [filing a support ticket](https://twilio.com/help/contact) and including the request ID to help debug.
