### ISSUE TITLE
Default timeout provided by the library using Faraday.default_adapter?

### ISSUE THREAD

**Issue by jcope2013** [twilio/twilio-ruby#402]
**Version:**

5.8.0

what is the default timeouts set if I don't configure a custom Twilio::HTTP::Client or is there any?

**Comment by javierjulio** [comment]
I've been wondering the same thing as I was just searching the code base and didn't see a default value set. The [Ruby community timeouts guide suggests the default is 30 seconds](https://github.com/ankane/the-ultimate-guide-to-ruby-timeouts#twilio-ruby) but I couldn't find anything that would suggest its set to that here.

**Comment by childish-sambino** [comment]
Answered here: https://github.com/lostisland/faraday/issues/708#issuecomment-477614664

> default `open_timeout` and `read_timeout` is 60 seconds
