### ISSUE TITLE
error_code is converted to zero when it's nil?

### ISSUE THREAD

**Issue by AndrewRayCode** [twilio/twilio-ruby#404]
### Code Snippet
```ruby
@message = @client.messages.create(
  from: '...',
  to: '...',
  body: '...'
)

puts @message.error_code
```

`error_code` is `0` (which isn't a valid Twilio status code) since (`to_i` is called on it)[https://github.com/twilio/twilio-ruby/blob/master/lib/twilio-ruby/rest/api/v2010/account/message.rb#L352].

It also appears this changed in some version of twilio-ruby but is not mentioned in the changelog? I'm having trouble tracing the history of the change as I'm not sure how code in this library is generated at a glance

**Comment by childish-sambino** [comment]
This was fixed as part of the [5.24.0](https://github.com/twilio/twilio-ruby/releases/tag/5.24.0) release.
