### ISSUE TITLE
undefined method `messages' for #<Twilio::REST::RequestError:0x000000039909a0> Did you mean? message

### ISSUE THREAD

**Issue by sahilchopra** [twilio/twilio-ruby#411]
*Note: These issues are for bugs and feature requests for the helper libraries.
If you need help or support, please email help@twilio.com and one of our experts
will assist you!*

**Version:**

gem 'twilio-ruby', '~> 4.11.1'

### Code Snippet
```ruby
require 'twilio-ruby'

module App
  # Sending SMS Library
  class SmsSend

    def initialize
      account_sid = Rails.application.secrets.twilio_account_id
      auth_token = Rails.application.secrets.twilio_auth_token
      @client = Twilio::REST::Client.new account_sid, auth_token
      @t_phone = Rails.application.secrets.twilio_sender_no
    end

    def send_sms(options = {})
      begin
        @client.account.messages.create(options.merge!({from: @t_phone}))
      rescue => e
        Rails.logger.warn "-------#{Date.today} \n-------- #{e.messages} \n---------#{options}"
      end
    end

  end
end

```

### Exception/Log
```
NoMethodError: undefined method `messages' for #<Twilio::REST::RequestError:0x000000039909a0> Did you mean? message
Processor: ip-172-31-33-228:18062
```

### Steps to Reproduce
1.
2.
3.

### Feature Request
_If this is a feature request, make sure you search Issues for an existing
request before creating a new one!_

**Comment by philnash** [comment]
Hi @sahilchopra,

Your error here is in your own code. In the `rescue` block:

```ruby
      rescue => e
        Rails.logger.warn "-------#{Date.today} \n-------- #{e.messages} \n---------#{options}"
      end
```

you make a call on `e.messages`. `e` in this case is a `Twilio::REST::RequestError` and doesn't have a `messages` method, but it does have a `message` method (as the exception shows).

Once you have that sorted, you will see the actual error message that is causing your `Twilio::REST::RequestError` and it should become clearer then.
