### ISSUE TITLE
Lower jwt version requirement for twilio-ruby version 5.x 

### ISSUE THREAD

**Issue by mecodess** [twilio/twilio-ruby#417]
**Version: 5.10.6**
I am going from twilio-ruby 3.x to 5.x in an existing application (for studio apis) and have following issue upgrading:

### Code Snippet
```
  In Gemfile:
    omniauth-auth0 (~> 1.4.1) was resolved to 1.4.2, which depends on
      omniauth-oauth2 (~> 1.1) was resolved to 1.1.2, which depends on
        oauth2 (~> 0.9.3) was resolved to 0.9.3, which depends on
          jwt (~> 0.1.8)

    twilio-ruby (~> 5.10.0) was resolved to 5.10.6, which depends on
      jwt (<= 2.5, >= 1.5)
```

If oauth2 was updated to the latest(1.4.0), I'd still need to have jwt ~> 1.0 [see here](https://rubygems.org/gems/oauth2)
I suppose people using omniauth, oauth gems will face this issue. 

I'd hence request to lower jwt version requirements.

**Comment by childish-sambino** [comment]
Doesn't appear to be an issue anymore since oath2 was updated to `jwt < 3.0, >= 1.0`.
