### ISSUE TITLE
Change to say method should have triggered a major version bump

### ISSUE THREAD

**Issue by esilverberg** [twilio/twilio-ruby#425]
I just want to report that the change to the ["say" method](https://www.twilio.com/docs/voice/twiml/say) to require a label on the first argument, as described here in [Release Notes as a "Breaking Change"](https://github.com/twilio/twilio-ruby/blob/master/CHANGES.md#2018-07-16-version-5110), really should have triggered a major version bump, [as per SemVer](https://semver.org/spec/v2.0.0.html#summary)

Fortunately I caught this change quickly in my code but others won't be so lucky. I guess it's too late now, but worth considering in the future.

**Comment by philnash** [comment]
Hey @esilverberg,

Appreciate the note, we don't follow SemVer exactly with this repo. Everything is explained in the [document on versioning strategy](https://github.com/twilio/twilio-ruby/blob/master/VERSIONS.md), but the important part is below:

> When a new large feature set comes online or a small breaking change is introduced, the MINOR version will be incremented by one and the PATCH version reset to zero. MINOR changes may require some amount of manual code change for upgrade. These backwards-incompatible changes will generally be limited to a small number of function signature changes.

I'm glad you caught the change yourself and I recommend you pin your dependency on `twilio-ruby` to patch changes only to ensure that you check with extra care when making a minor point upgrade to the library.
