### ISSUE TITLE
twilio-ruby freeing too many memory slots

### ISSUE THREAD

**Issue by gemfarmer** [twilio/twilio-ruby#429]
This is a memory issue and is potentially related to #396. 

I recently added the `twilio-ruby` gem to our rails application and suddenly started experiencing memory issues. Not only did our project's average memory usage increased (from stabilizing at ~500 MB to ~700/750MB), but our application started freeing up a ton of memory slots. Below are two charts of [Free Memory Slots](https://devcenter.heroku.com/articles/language-runtime-metrics-ruby#free-memory-slots), based on heroku's runtime metrics. 

##### Usage without `twilio-ruby` gem added:
<img width="1134" alt="screenshot 2018-10-12 12 23 18" src="https://user-images.githubusercontent.com/4803473/46884575-ff26bb00-ce1a-11e8-9c93-f463f30c9520.png">

##### Usage with `twilio-ruby` gem added:
Keep in mind that 50,000 free memory slots isn't too concerning. When I was actively using the gem, the number of free slots was quite a bit higher, sometims 600k+. All of this wouldn't be too concerning if my overall memory usage wasn't spiking, but as it is, I'm assuming that this is related.
<img width="1152" alt="screenshot 2018-10-12 12 23 26" src="https://user-images.githubusercontent.com/4803473/46884604-0d74d700-ce1b-11e8-81f1-13d44e04892b.png">

### Memory usage
With regards to #396, I'm not seeing the crazy numbers reported for `twilio-ruby`

##### Here is mine with a few other gems for comparison:

```bash
> bundle exec derailed bundle:mem
rails: 9.5508 MiB (Also required by: active_record/railtie, active_model/railtie, and 13 others)
twilio-ruby: 11.2109 MiB
pg: 3.8047 MiB
devise: 1.6914 MiBaction_dispatch/middleware/stack)
```

**Version:**
`gem 'twilio-ruby', '~> 5.14', '>= 5.14.1'`

### Steps to Reproduce
1. Add it to your Rails Project 
2. Add project to Heroku
3. Follow steps [here](https://devcenter.heroku.com/articles/language-runtime-metrics-ruby#free-memory-slots) to add Ruby runtime Metrics

**Comment by gemfarmer** [comment]
Thanks @philnash. What other information do you need to do dig into it more?

**Comment by acflint** [comment]
+1 on this. Came here looking for any one else reporting memory issues. Thank you @philnash for getting it on the schedule!

**Comment by gemfarmer** [comment]
@philnash any update on this?

**Comment by philnash** [comment]
I've updated #396. Would be interested to see if that work has helped here too. Any testing and feedback would be appreciated.

**Comment by gemfarmer** [comment]
@philnash thanks for updating. I'll test as soon as possible!
