### ISSUE TITLE
Allow adding comments into TwiML responses

### ISSUE THREAD

**Issue by dbrody** [twilio/twilio-ruby#430]
I'd like a way to add comments into a TwiML response for documentation / comprehension.

Something like
```ruby
Twilio::TwiML::VoiceResponse.new do |r|
    r.comment('This is a sample comment')
end
```

Which would output:
### Exception/Log
```
<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <!--This is a sample comment-->
</Response>
```

**Comment by dbrody** [comment]
Ops, this is a duplicate of https://github.com/twilio/twilio-ruby/pull/407

**Comment by philnash** [comment]
Glad to have pre-empted your request! 😄
