### ISSUE TITLE
Passing Custom Parameters to Client through Conference Call

### ISSUE THREAD

**Issue by audiolion** [twilio/twilio-ruby#434]
Hello 👋 ,

**Version:** 1.6.x

### Feature Request

Is it possible to add `<Parameter>` TwiML to the `<Conference>` noun? I saw that `<Parameter` was recently added to `<Client>`

https://github.com/twilio/twilio-ruby/blob/7ad2f01e2546bcf8176d4f14c362051b6ded61f1/lib/twilio-ruby/twiml/voice_response.rb#L865-L900

but there seems to be no parallel if you are using Conferences.

The use-case here is that if I leave a conference call, I want to be able to rejoin that call without having to be "dialed back in", so the solution would be to hit our API which would send us a TwiML `<Conference>` dial in, but with custom parameters so I know I am being dialed back in and not display the incoming call to the user and immediately accept it on the client.

**Comment by audiolion** [comment]
ping @philnash

**Comment by childish-sambino** [comment]
This is not a change that can be made in the library. An internal ticket has been filed against the relevant product team.

**Comment by audiolion** [comment]
Ok thank you
