### ISSUE TITLE
ll libxml-ruby-3.1.0

### ISSUE THREAD

**Issue by danchily2** [twilio/twilio-ruby#439]
*Note: These issues are for bugs and feature requests for the helper libraries.
If you need help or support, please email help@twilio.com and one of our experts
will assist you!*

**Version:**

### Code Snippet
```ruby
# paste code here
```

### Exception/Log
```
<place exception/log here>
```

### Steps to Reproduce
1.
2.
3.

### Feature Request
_If this is a feature request, make sure you search Issues for an existing
request before creating a new one!_

**Comment by childish-sambino** [comment]
Looks like just the issue template got submitted. Could you add some details about the problem you're having and re-open?
