### ISSUE TITLE
Version 5.22.0 introduced a breaking change without bumping the major version

### ISSUE THREAD

**Issue by hex337** [twilio/twilio-ruby#449]
**Version: 5.22.0**

From the changelog:

**Voice**
- changed file names to dialing_permissions prefix **(breaking change)**

If you are using semver for versioning, this should have been part of a 6.0 release. We had some code breaks from this from doing a minor bump, which we did not expect.

**Comment by childish-sambino** [comment]
This lib uses _modified_ semver. It should be called out in the main README, but it's not right now.

https://github.com/twilio/twilio-ruby/blob/master/VERSIONS.md
