### ISSUE TITLE
Dial TwiML verb should support multiple Numbers

### ISSUE THREAD

**Issue by ericcf** [twilio/twilio-ruby#451]
**Version: all**

### Feature Request
According to https://www.twilio.com/docs/voice/twiml/number, the Dial TwiML verb supports up to 10 Number nouns nested within. However, the `#dial` method of the `VoiceResponse` class is designed to support exactly one number: https://github.com/twilio/twilio-ruby/blob/ccad134a29c54b785b2394cb50c812fa79a0fd2d/lib/twilio-ruby/twiml/voice_response.rb#L50. In addition, the inner class `Dial` supports only one `Number`: https://github.com/twilio/twilio-ruby/blob/ccad134a29c54b785b2394cb50c812fa79a0fd2d/lib/twilio-ruby/twiml/voice_response.rb#L721

Is there any intention of adding this feature, or would a pull request adding it be welcomed? If not, I'll work on a workaround for my project.

Thanks!

**Comment by childish-sambino** [comment]
You can call `dial` multiple times on the same `VoiceResponse` to add multiple numbers. There's an example here using block-syntax: https://www.twilio.com/docs/voice/twiml/number?code-sample=code-multi-dial-with-call-progress-events-3&code-language=Ruby&code-sdk-version=5.x
