### ISSUE TITLE
`error_code` changed to `nil` from 0 in Version 5.24.0 

### ISSUE THREAD

**Issue by y-yagi** [twilio/twilio-ruby#453]
**Version: 5.24.0**

Before v5.24.0, `error_code` was `0` when response is null. But this behaviour changed to v5.24.0.
https://github.com/twilio/twilio-ruby/commit/4a4691a491c9e6c03388dbfed99ecac2d9334c55 

Is this expected change? This seems to breaking change but not described in CHANGES. 
https://github.com/twilio/twilio-ruby/blob/master/CHANGES.md#2019-06-12-version-5240 

Our team expected to `error_code`to be integer value. If this change is expected, we will fix an application. However, since there was no explanation in CHANGE, please let me confirm what kind of intention this change was made.

Thanks.

**Comment by y-yagi** [comment]
Just a friendly ping

**Comment by childish-sambino** [comment]
Yes, this was an intentional fix to more uniformly match what's returned from the API (`null` if no error).

It should have been noted in the release notes but ended up falling through.

**Comment by jtebaldi** [comment]
I just spent half a day looking for this, so it would definitely be helpful if the docs were updated.

**Comment by childish-sambino** [comment]
Release notes updated: https://github.com/twilio/twilio-ruby/releases/tag/5.24.0
