### ISSUE TITLE
Twilio::REST::Client exposes password/auth_token via attr_accessor

### ISSUE THREAD

**Issue by tomwilshere** [twilio/twilio-ruby#456]
**Version: 5.19.0**

This is primarily a security issue for users of the client who don't suppress credentials in logging/monitoring software. Credentials may be exposed in logs for these users.

### Steps to Reproduce
1. Initialise a Twilio::REST::Client with auth_token/password
2. Calling `@client.password` or `@client.auth_token` returns the secure credential
3. Calling `@client.inspect` (as done by most error handlers) also exposes the credentials.

This appears to be the result of the autogenerated client from Yoyodyne

**Comment by childish-sambino** [comment]
This was fixed by https://github.com/twilio/twilio-ruby/pull/438 in release _5.20.1_.
