### ISSUE TITLE
undefined method 'verify' for Twilio::REST::Client

### ISSUE THREAD

**Issue by talhashoaib** [twilio/twilio-ruby#461]
**twilio-ruby (5.12.4):**

### Code Snippet
```@client = Twilio::REST::Client.new(my_account_sid, my_auth_token)
@client.verify.services('VAABCDDDKLK').verifications.create(to: '+9number', channel: 'sms', customCode: '1234')
```

### Exception/Log
```
NoMethodError: undefined method `verify' for #<Twilio::REST::Client:0x000000090f9408>
	from (irb):9
```

### Steps to Reproduce
1. Just call the verify method to the client helper. It throws an error.

**Comment by childish-sambino** [comment]
Verify was moved out of preview added as part of the [5.13.0](https://github.com/twilio/twilio-ruby/releases/tag/5.13.0) release.
