### ISSUE TITLE
Using an API Key Results in HTTP 400

### ISSUE THREAD

**Issue by mgomes** [twilio/twilio-ruby#478]
It doesn't look like the twilio-ruby client has support for using revocable API keys rather than an account_sid. Is this the case? If not, could you please point me to the code or docs for reference?

Thanks!

**Version:**
5.23.0

### Code Snippet

The README and docs only specify instantiating a client with an account_sid and auth_token.
From the docs:

```ruby
# set up a client to talk to the Twilio REST API
@client = Twilio::REST::Client.new account_sid, auth_token
```

### Exception/Log
If I instantiate the client using a revocable API Key (beginning with `SK`) I get an error for each request:

```
[HTTP 400] 90002 : Unable to create record
AccountSid SK1234 is invalid
https://www.twilio.com/docs/errors/90002

```

### Steps to Reproduce
1. Instantiate client with `@client = Twilio::REST::Client.new api_key, api_secret`
2. Run any request.

**Comment by childish-sambino** [comment]
Try sticking the account SID after the secret.

**Comment by mgomes** [comment]
@childish-sambino like just concatenate the two without a space?

**Comment by childish-sambino** [comment]
Sorry, meant as the 3rd arg:
```
@client = Twilio::REST::Client.new api_key, api_secret, account_sid
```

**Comment by mgomes** [comment]
Thanks, @childish-sambino. That did the trick! 🙌
