### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by piotr-galas** [twilio/twilio-ruby#482]
*Note: These issues are for bugs and feature requests for the helper libraries.
If you need help or support, please email help@twilio.com and one of our experts
will assist you!*

## You have a typo in documentation that make integration more difficult.

At the page: 

https://www.twilio.com/docs/video/tutorials/user-identity-access-tokens#ruby

In the initializer there is a mistake

![img](https://cl.ly/a16b27f3e2e0/[5b6b69d4c24dc6265321f6785f2662c0]_Screenshot%25202019-10-29%2520at%252010.39.35.png)

It should be 
```ruby
token = Twilio::JWT::AccessToken.new(account_sid, api_key, api_secret, [], identity: identity);
```

**Comment by childish-sambino** [comment]
Thanks! Nice catch. I've submitted the change for review. Will update here when it's been approved.

**Comment by childish-sambino** [comment]
Doc fix pushed: https://www.twilio.com/docs/video/tutorials/user-identity-access-tokens#ruby
