### ISSUE TITLE
Task list default page size is 50, not 1000

### ISSUE THREAD

**Issue by sbaar** [twilio/twilio-ruby#483]
In the 5.28.0 version in the [taskrouter workspace task file](https://github.com/twilio/twilio-ruby/blob/master/lib/twilio-ruby/rest/taskrouter/v1/workspace/task.rb) the list function will return a list of all tasks without limit. It will do so by default with a page size of 50, even though it is more efficient on the client and the twilio servers to default to the max, 1000.

To be clear, the documentation for the page_size param on the list function and stream function is 
```
            # @param [Integer] page_size Number of records to fetch per request, when
            #    not set will use the default value of 50 records.  If no page_size is defined
            #    but a limit is defined, stream() will attempt to read the limit with the most
            #    efficient page size, i.e. min(limit, 1000)
```

This makes complete sense for the stream() function where it will return fewer results than the complete task list. However, when the list() function is called **and limit is :unset** then there will always be the same or fewer client/server calls if the page size is as high as possible. This is true if there are 5 tasks, 50, 100, or 5000

**Comment by childish-sambino** [comment]
It's not necessarily more efficient to use a larger page size (really depends on backing datastore and implementation), and there are several Twilio resources that clients are likely to get better results with by using smaller page sizes.

That said, the pattern should be avoided where a large number of items are being pulling on a frequent basis as it can be expensive for both the client and the server, especially if the same records are being pulled multiple times. Filtering and/or webhook callbacks should be used when available to lower the total data transfer.

Either way, the method does allow you to specify a larger page size if it works best for your usecase. Let me know if this doesn't meet your requirements and we can dive more into the details.

**Comment by sbaar** [comment]
> It's not necessarily more efficient to use a larger page size (really depends on backing datastore and implementation), and there are several Twilio resources that clients are likely to get better results with by using smaller page sizes.
> 
> That said, the pattern should be avoided where a large number of items are being pulling on a frequent basis as it can be expensive for both the client and the server, especially if the same records are being pulled multiple times. Filtering and/or webhook callbacks should be used when available to lower the total data transfer.

Long term, we are architecting our system to rely on infrequent twilio list pulls and transformative webhooks to our cache.

> Either way, the method does allow you to specify a larger page size if it works best for your usecase. Let me know if this doesn't meet your requirements and we can dive more into the details.

I get what you're saying and it makes sense for the page function(). If you are just sampling the resource or getting the most recent, page()'s current defaults make sense.

My gripe is with list(). list, by default, grabs all the tasks without limit, so maximizing page size makes sense here.

Actually, looking at the description and way list() works
`            # Unlike stream(), this operation is eager and will load `limit` records into
            # memory before returning.
`
why is there page size param at all? If it doesn't return until everything's loaded, then what will specifying a page size even do besides require more api calls?

**Comment by childish-sambino** [comment]
It's relating back to the point that larger page sizes may not be more efficient. Yes, the result will be the same, but the _cost_ is different in terms of the number of API calls, individual payload sizes, and total time. Based on the backing implementation, the total time _could_ increase with a larger page size.

The code samples on the Twilio dos include an explicit limit in all the `list` examples so clients wouldn't pull pages and pages of records, and `twilio-cli` actually uses a default limit of 50 when calling `list` commands. I'm actually in favor of making this the default behavior in the helper libraries, but it would be a _very_ breaking change at this point.

Overall, I don't see this changing unless given the OK by product teams that own the backing data stores that larger page sizes are better across the resources they own.
