### ISSUE TITLE
After  v5.29.1 upgrade, getting Twilio::REST::TwilioError -> "execution expired" errors

### ISSUE THREAD

**Issue by rylanb** [twilio/twilio-ruby#486]
**Version:**
v5.29.1 (recently upgraded from v4.13.0

### Code Snippet
```ruby

# Preconfigured: 
Twilio.configure do |config|
  config.account_sid = ENV['TWILIO_ACCOUNT_SID']
  config.auth_token  = ENV['TWILIO_AUTH_TOKEN']
end

def twilio_client
    @twilio_client ||= Twilio::REST::Client.new
  end

SubscriberTexter.weather_forecast_alert(facade).deliver` # using Textris to send 

```

### Exception/Log
```
/app/vendor/bundle/ruby/2.5.0/gems/twilio-ruby-5.29.1/lib/twilio-ruby/http/http_client.rb:58:in `rescue in send'
/app/vendor/bundle/ruby/2.5.0/gems/twilio-ruby-5.29.1/lib/twilio-ruby/http/http_client.rb:53:in `send'
/app/vendor/bundle/ruby/2.5.0/gems/twilio-ruby-5.29.1/lib/twilio-ruby/http/http_client.rb:40:in `_request'
/app/vendor/bundle/ruby/2.5.0/gems/twilio-ruby-5.29.1/lib/twilio-ruby/http/http_client.rb:63:in `request'
/app/vendor/bundle/ruby/2.5.0/gems/twilio-ruby-5.29.1/lib/twilio-ruby/rest/client.rb:82:in `request'
/app/vendor/bundle/ruby/2.5.0/gems/twilio-ruby-5.29.1/lib/twilio-ruby/framework/domain.rb:22:in `request'
/app/vendor/bundle/ruby/2.5.0/gems/twilio-ruby-5.29.1/lib/twilio-ruby/framework/version.rb:53:in `request'
/app/vendor/bundle/ruby/2.5.0/gems/twilio-ruby-5.29.1/lib/twilio-ruby/framework/version.rb:147:in `create'
/app/vendor/bundle/ruby/2.5.0/gems/twilio-ruby-5.29.1/lib/twilio-ruby/rest/api/v2010/account/message.rb:116:in `create'
/app/vendor/bundle/ruby/2.5.0/gems/textris-0.7.1/lib/textris/delivery/twilio.rb:20:in `deliver'
/app/vendor/bundle/ruby/2.5.0/gems/textris-0.7.1/lib/textris/delivery/base.rb:12:in `block in deliver_to_all'
/app/vendor/bundle/ruby/2.5.0/gems/textris-0.7.1/lib/textris/delivery/base.rb:11:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/textris-0.7.1/lib/textris/delivery/base.rb:11:in `deliver_to_all'
/app/vendor/bundle/ruby/2.5.0/gems/textris-0.7.1/lib/textris/message.rb:20:in `block in deliver'
/app/vendor/bundle/ruby/2.5.0/gems/textris-0.7.1/lib/textris/message.rb:19:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/textris-0.7.1/lib/textris/message.rb:19:in `deliver'
```

### Steps to Reproduce
1. Send ~ 5000 texts one at a time via Textris, I guess? 
2. We send about 20k texts/day over 3-4 hours in the AM.

I recently upgraded the `twilio-ruby` gem and noticed that there was an http_client added using Faraday, so I'm starting here but will be reaching out to Twilio support to try to resolve either way and can update this issue if they give me good pointers. Feel free to close this and tell me to reach out to support only, but I wanted to ask if you had seen anything around this, like another issue that I can't find in here on my own. 

These `execution expired` errors are new to us (but maybe weren't showing in the previous gem?) and we are getting 3-4 a day and have been trying to debug and can't find a lot of information about that error. 

Any pointers / tips / ideas would be good.

**Comment by childish-sambino** [comment]
No similar issues that I know of. Sounds like a transient network issue. Recommend adding retry logic. There have been a lot of changes since v4.

**Comment by rylanb** [comment]
Ok, will update if support adds any extra details there. I figured it was something like that, was just curious that it was tied directly to the gem upgrade and the errors starting. Perhaps they are just being surfaced properly now, where before they were not.

**Comment by rylanb** [comment]
Thanks, support agreed with you, so I'll institute retries and consider this closed! Thanks for letting me troubleshooting / bother you.

**Comment by syoder** [comment]
> Recommend adding retry logic

Any specific recommendations? The project I'm working on is set to retry 3 times, but that doesn't seem to be enough sometimes.
