### ISSUE TITLE
Update version gem Faraday dependency

### ISSUE THREAD

**Issue by killondark** [twilio/twilio-ruby#487]
I want to use **Active Storage** with **google-cloud-storage** gem. But

```
google-cloud-storage (~> 1.8) was resolved to 1.15.0, which depends on
  googleauth (~> 0.6.2) was resolved to 0.6.7, which depends on
    faraday (~> 0.12)
```
Please update version **faraday** dependecy in **twilio-ruby**

**Version: 5.31.0**

**Comment by childish-sambino** [comment]
Version `5.31.0` of this lib has a dependency on `'faraday', '~>0.9'` which currently evaluates to `0.17.1`: https://github.com/twilio/twilio-ruby/blob/master/twilio-ruby.gemspec#L29

**Comment by killondark** [comment]
Thank you
