### ISSUE TITLE
Twilio Add-on error : Bad request code:61005

### ISSUE THREAD

**Issue by eftikharEmad** [twilio/twilio-ruby#500]
### Issue Summary
I am using voicebase add-on, every thing was fine till this morning , I make calls normally but I am getting Bad request code:61005 (https://www.twilio.com/docs/api/errors/61005) for the call back on transcriptions. any Idea about this ??

thank you

**Comment by childish-sambino** [comment]
Best to [file a support ticket](https://twilio.com/help/contact) in order to debug what's going on.
