### ISSUE TITLE
Unable to generate Capability Token

### ISSUE THREAD

**Issue by dhara-thacker** [twilio/twilio-ruby#501]
### Issue Summary
I'm trying to generate capabilities token. And I'm getting below error while doing that: 
NameError (uninitialized constant Twilio::JWT::Capability)

Checkout my code to make sure I'm doing in the correct manner:

```
account_sid = 'sid'
auth_token = 'token'
capability = Twilio::JWT::Capability.new(account_sid, auth_token)
```
The last line in the above code produces the above mentioned error. Kindly help.

Note::

Twilio gem and all other things are configured properly. As I'm already using it to send sms. Also, Have tried making call using code. Also generated a normal access token. But I want to generate a capability token.

Any help appreciated.

Thanks

**Comment by childish-sambino** [comment]
Is this for a `TaskRouterCapability`?

```
Twilio::JWT::TaskRouterCapability
```

**Comment by dhara-thacker** [comment]
@childish-sambino  Thanks for your help.

I had tried this and that worked. But it's not what I'm looking for.  Checkout this link:

https://www.twilio.com/docs/voice/client/tutorials/capability-tokens


```@client = Twilio::JWT::ClientCapability.new(account_sid, auth_token)```

This does create an instance for me. But then I cannot go ahead as shown in the above link.

i.e.
```
capability.allow_client_incoming('joey')
token = capability.generate
```

```allow_client``` this function seems be to available with ```Twilio::JWT::Capability.new``` this resource only.

**Comment by childish-sambino** [comment]
Ah, thanks for the link. Looks like that doc is incorrect. Working on a proper example ...

**Comment by childish-sambino** [comment]
This works for me:
```
account_sid = 'ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
auth_token = 'your_auth_token'
capability = Twilio::JWT::ClientCapability.new(account_sid, auth_token)

capability.add_scope(Twilio::JWT::ClientCapability::IncomingClientScope.new('joey'))
token = capability.to_jwt
```

**Comment by dhara-thacker** [comment]
@childish-sambino : 

Hey, thanks for such a prompt response. This worked for me.. 
Thanks again :)
