### ISSUE TITLE
Documentation for streaming message logs

### ISSUE THREAD

**Issue by jeremy04** [twilio/twilio-ruby#503]
### Issue Summary

Hello! I ran into an issue with using `@client.messages.list` due to the size of my message logs exceeding 1000.

I resolved my issue by using `@client.messages.stream` instead.

It would be nice to have additional documentation for this public api:
`@client.messages.stream`

somewhere close by:
https://www.twilio.com/docs/sms/api/message-resource?code-sample=code-read-list-messages-filter-by-before-sent-date&code-language=Ruby&code-sdk-version=5.x

If there is already documentation, let me know, and I can close this issue!

Hope everyone is safe

### Technical details:
* twilio-ruby version: 5.7.1
* ruby version: 2.4.2

**Comment by childish-sambino** [comment]
Not sure why you're seeing an issue with more than 1k results. `list` basically just calls `stream` and gets the full array. If it's an issue with heap memory, then yes, it's best to not use `list` in general unless you're just looking for the last _X_ records.

**Comment by jeremy04** [comment]
Thank you for the explanation!

I was unsure about >1k, due to trying `limit: 5000` but the method was returning 1000. which makes sense now (last x records).  I also had to change the page_size to 1000 to allow the `list` call to actually finish in a timely manner ( I didn't wait long enough):

```
[35] pry(main)> Benchmark.realtime do
[35] pry(main)*   @client.messages.list(date_sent_after: "2020-03-27 00:00:00", date_sent_before: "2020-03-27 23:59:59", page_size: 1000)
[35] pry(main)* end
=> 36.50756600004388
```

Going to close this issue
