### ISSUE TITLE
 undefined method `wireless' for #<Twilio::REST::Client:0x0055ac2adcb578>

### ISSUE THREAD

**Issue by RentlyNandha** [twilio/twilio-ruby#504]
undefined method `wireless' for #<Twilio::REST::Client:0x0055ac2adcb578>
 
version 3.11.0
 
code:
 require 'twilio-ruby'

      account_sid = Figaro.env.twilio_account
      auth_token = Figaro.env.twilio_secret
      # set up a client to talk to the Twilio REST API
      client = Twilio::REST::Client.new(account_sid, auth_token)
      sim = client.wireless.sims('').fetch

**Comment by childish-sambino** [comment]
`3.11.0` is pretty old and probably did not contain the wireless APIs. Are you able to upgrade to a later release?
