### ISSUE TITLE
ArgumentError (JWT does not have a signing key)

### ISSUE THREAD

**Issue by DRBragg** [twilio/twilio-ruby#509]
### Issue Summary
I'm attempting to generate an access token from my rails app for use with video calling. I'm following the instructions of the example code from the [Twilio dashboard](https://www.twilio.com/console/video/project/testing-tools) and this [repos wiki](https://github.com/twilio/twilio-ruby/wiki/JWT-Tokens#access-tokens).  When the method runs i get `ArgumentError (JWT does not have a signing key)`

Admittedly I may just be burnt out at this point, so forgive me if this is a ID10T issue on my part.

### Steps to Reproduce
1. Follow the instructions in either the [Twilio Programmable Video Dashboard](https://www.twilio.com/console/video/project/testing-tools) or this [repos wiki](https://github.com/twilio/twilio-ruby/wiki/JWT-Tokens#access-tokens)
2. Run method
3. fail...

### Code Snippet
```ruby
  def token
    account_sid = ENV['TWILIO_ACCOUNT_SID']
    api_key = ENV['TWILIO_API_KEY']
    api_secret = ENV['TWILIO_API_KEY_SECRET']

    grant = Twilio::JWT::AccessToken::VideoGrant.new
    grant.room = 'Test room'

    token = Twilio::JWT::AccessToken.new(
      account_sid,
      api_key,
      api_secret,
      [grant],
      identity: current_user.full_name
    )

    render json: { token: token.to_jwt }, status: :ok
  end
```

### Exception/Log
```
JWT does not have a signing key excluded from capture: DSN not set

ArgumentError (JWT does not have a signing key):
```

### Technical details:
* twilio-ruby version: 5.33
* ruby version: 2.6.1
* rails version: 5.2.4.1

**Comment by childish-sambino** [comment]
This error is raised when the secret is nil. Recommend testing to make sure the env vars are being read properly.

**Comment by DRBragg** [comment]
I popped a pry in there and checked it all out.  Looks like everything is working until I call `Twilio::JWT::AccessToken.new`.  Even passing in hard coded values I get the same error.  It's weird, I looked through this repo's code and you're right I should only get that error with a nil value is passed for secret but I get it no matter what.  I'll have to keep looking.  Feel free to close this issue.

**Comment by childish-sambino** [comment]
🤷 Just tried this and it was fine:
```
account_sid = 'sid'
api_key = 'key'
api_secret = 'secret'

grant = Twilio::JWT::AccessToken::VideoGrant.new
grant.room = 'Test room'

token = Twilio::JWT::AccessToken.new(
    account_sid,
    api_key,
    api_secret,
    [grant],
    identity: 'me'
)

puts token.to_jwt
```

**Comment by DRBragg** [comment]
Yea, I was trying the same thing but still had the problem. Luckily, we found the issue and it wasn't related to this gem. Sorry for opening an unnecessary issue.

**Comment by OmkarArote** [comment]
> Yea, I was trying the same thing but still had the problem. Luckily, we found the issue and it wasn't related to this gem. Sorry for opening an unnecessary issue.

Can I know the solution?

**Comment by HardikPurohit** [comment]
> Yea, I was trying the same thing but still had the problem. Luckily, we found the issue and it wasn't related to this gem. Sorry for opening an unnecessary issue.

@DRBragg , Can you please let us know the solution?

**Comment by DRBragg** [comment]
> > Yea, I was trying the same thing but still had the problem. Luckily, we found the issue and it wasn't related to this gem. Sorry for opening an unnecessary issue.
> 
> @DRBragg , Can you please let us know the solution?

Sorry @HardikPurohit and @OmkarArote at this point I dont remember what the issue was, only that it wasn't actually related to this gem. I'm sorry.
