### ISSUE TITLE
GSM encoding on SMS

### ISSUE THREAD

**Issue by kevinchugh** [twilio/twilio-ruby#521]
### Issue Summary
Can you force GSM encoding on SMS to reduce cost?  (https://www.twilio.com/blog/2017/03/what-the-heck-is-a-segment.html)

### Code Snippet
```ruby
 response = client.messages.create(
                        from: twilio_phone_number,
                        to: recipient,
                        body: content # can you add encoding: :gsm here or something like this?
                    )
```

### Exception/Log
```
# paste exception/log here
```

### Technical details:
* twilio-ruby version:
* ruby version:

**Comment by thinkingserious** [comment]
Hello @kevinchugh,

We don't have a means to force GSM encoding via the helper library or API. However, per [this documentation](https://www.twilio.com/docs/glossary/what-is-gsm-7-character-encoding), when sending SMS messages with Twilio, we'll automatically send messages in the most compact encoding possible.

With best regards,

Elmer
