### ISSUE TITLE
Question: Create a room with end time

### ISSUE THREAD

**Issue by luchiago** [twilio/twilio-ruby#522]
### Issue Summary
I want to know if there's any way to create a room with a specific end time

### Steps to Reproduce
1. Create a room

### Code Snippet
```ruby
# paste code here
```

### Exception/Log
```
# paste exception/log here
```

### Technical details:
* twilio-ruby version: 5.37.0
* ruby version: 2.6.5

**Comment by childish-sambino** [comment]
Nothing that I could find, other than using a scheduler of sorts to mark the room `completed` at a certain time.

**Comment by luchiago** [comment]
@childish-sambino Thanks for answering me so quickly. Yeah, I'm using sidekiq to schedule the update of the status, but I'm having some trouble with it. I asked about this way bc it's a workaround for me.

**Comment by childish-sambino** [comment]
Best thing to do would be to reach out to [support](https://support.twilio.com). The support and product teams use tickets there to track product feature requests.

**Comment by luchiago** [comment]
Alright. Thanks again @childish-sambino
