### ISSUE TITLE
RFC: configure sending an X-Request-Id header for use by twilio engineers in debugging requests

### ISSUE THREAD

**Issue by bf4** [twilio/twilio-ruby#523]
### Issue Summary

A twilio engineer in a support ticket has asked me to add an [`X-Request-Id`](https://blog.heroku.com/http_request_id_s_improve_visibility_across_the_application_stack
) header to requests we make, and though adding custom headers [is supported in the library in general](https://github.com/twilio/twilio-ruby/blob/5b96b5413bf61b0fab38e135a0828471cfa652a8/lib/twilio-ruby/framework/version.rb
) (since https://github.com/twilio/twilio-ruby/pull/516 ), there's no public interface for me to add this in `twilio_client.messages.create(payload)`.  

Short of generally exposing a custom headers interface, it seems that opting in to including a request-id might be a desirable feature.

I don't see an small surgical way to add the header on message creation, e.g. https://github.com/twilio/twilio-ruby/blob/5.39.1/lib/twilio-ruby/rest/api/v2010/account/message.rb

per https://github.com/twilio/twilio-ruby/issues/214#issuecomment-330970827 something like this was added a while ago, but I see no evidence of it beyond the comment.

I'd be willing to write it.

### Steps to Reproduce

1. get a net open timeout
1. contact support
1. support says add this header
1. ?

### Code Snippet

```ruby
twilio_client.messages.create(payload)
```

### Exception/Log

n/a

### Technical details:
* twilio-ruby version: 5.39.1
* ruby version: 2.6.2

**Comment by bf4** [comment]
In the meantime, I made this patch in our app

```ruby
require 'twilio-ruby/http/http_client'

module TwilioHttpClientPatch
  # https://github.com/rails/rails/blob/6-0-stable/actionpack/lib/action_dispatch/middleware/request_id.rb
  X_REQUEST_ID = "X-Request-Id" #:nodoc:

  def request(host, port, method, url, params = {}, data = {}, headers = {}, auth = nil, timeout = nil)
    headers ||= {}
    headers[X_REQUEST_ID] ||= SecureRandom.uuid
    super
  end
end
Twilio::HTTP::Client.prepend(TwilioHttpClientPatch)
```

**Comment by eshanholtz** [comment]
Hi @bf4 

I would recommend using passing a [custom HTTP client](https://www.twilio.com/docs/libraries/php/custom-http-clients-php) and adding your custom headers there for this use case. The custom headers referred to in #516 are the ones defined by the downstream API and auto-generated into the helper libraries.

**Comment by bf4** [comment]
@eshanholtz my patch is working now so I think I'll just keep using it until either Twilio support says the header doesn't help or it gets first class support from Twilio

**Comment by eshanholtz** [comment]
@bf4 Sounds good. I'm going to close this ticket. You can reopen if you require further library help.
