### ISSUE TITLE
MessageInstance.to_json doesn't return JSON

### ISSUE THREAD

**Issue by JohnnyMorbo** [twilio/twilio-ruby#524]
### Issue Summary
When I call .to_json on a message object, I don't get a JSON string, I get something like:
"\"<Twilio.Api.V2010.MessageInstance account_sid: AC<my account sid> sid: SM<message sid>>\"

I was expecting something like:
" { body: "Testing 1,2,3", to: "+11234567890", from: "+10987654321", account_sid: "blah blah" }"
that I could use the JSON parser on.

Is this a bug, or user error?

### Code Snippet
```ruby
client = Twilio::REST::Client.new(ACCOUNT_SID, AUTH_TOKEN)
message = client.messages.create(From: FROM, to: to, body: body)
puts message.to_json
```
output:
"\"<Twilio.Api.V2010.MessageInstance account_sid: ACxxxxxxx sid: SMxxxxxxxx>\""

### Technical details:
* twilio-ruby version: 5.39.1
* ruby version: 2.5.8p224

**Comment by JohnnyMorbo** [comment]
I can get the response I am expected by using:
`MessageInstance.instance_variable_get(:@properties).to_json`
But this seems, to me, an inelegant solution.
I think I should be able to just use
`MessageInstance.to_json`
to get a JSON representation of the message.

- twilio-ruby version: 5.39.2

**Comment by JohnnyMorbo** [comment]
And/Or, add an attr_reader for `@properties` so I can get the Hash, like 
```ruby
MessageInstance.properties
```

**Comment by eshanholtz** [comment]
Hi @JohnnyMorbo, can you tell me more about your use case? It sounds like you want access to the underlying API Response payload, which should be the same as adding a `attr_reader` for `@properties`, as you mentioned. This would require a change to our generated code. This feature request has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by JohnnyMorbo** [comment]
Hi @eshanholtz, sorry about my stream-of-consciousness updates.  Let me try to summarize:
The existing `MessageInstance.to_json` method does not return a valid JSON string.  I think this is a bug, so this method should either be patched or removed.  Unless the original author had a different intent for the .to_json method, I think it should be patched so it emits a JSON string of the API response payload, AKA `@properties`

My second Issue is a feature request, I guess, so I'll start a new Issue for it.  In short, I'd like to have a `.to_h` method emits a Hash object of the `@properties` to complement the `.to_json` method.

As for my use case, I just want to see all of the information available after I send a text message.  Currently, I need to make individual method calls for each attribute I want to inspect.  That requires me to know the names of every attribute.  This is tedious and frustrating.  If there were a method, such as .to_json or .to_h that emitted the entire `@properties` then I could see all the data with one method call, and then I could drop the result in my local database, or format it for display, or something.  And, if Twilio changes the API response upstream, there's nothing to change in the gem - .to_h just emits the entire API response, no matter what's in it.  Should probably update the docs, tho :)

**Comment by JohnnyMorbo** [comment]
I've now taken a look at the code, and...
I can't find where .to_json is defined.  However, it seems to output the same thing as MessageInstance.to_s
The intention of .to_s seems to be to just output a representation of the object class, and then the `@params` (**not** `@properties`)
Which is fine, although the object class it reports isn't really right, it's just there for convenience and probably doesn't need to be altered.
But my original complaint, that .to_json doesn't emit actual JSON, is still valid.  I think if you name a method 'to_json' it should return, well, _JSON_
I think something simple like this could be added:
```ruby
class MessageInstance
  def to_json(opts = nil)
    JSON.generate(@properties, opts)
  end
end
```
and that would fix this issue.

**Comment by eshanholtz** [comment]
This library doesn't currently support a `.to_json` method. You are welcome to submit a PR with your proposed changes to the resource you're talking about that we can use as an example for incorporating into our generated code. Otherwise, this feature request has been added to our internal backlog to be prioritized.

**Comment by eshanholtz** [comment]
@JohnnyMorbo, If you're just looking to inspect the JSON payload for debugging reasons, the underlying http client stores the last request and last response for this purpose:
```ruby
@client = Twilio::REST::Client.new(ACCOUNT_SID, AUTH_TOKEN)
message = @client.messages.create(to: '+14434653403', from: '+17637032543', body: 'test')
puts @client.http_client.last_response # Stores the JSON payload response
```
Note that the [Twilio Response returned](https://github.com/twilio/twilio-ruby/blob/main/lib/twilio-ruby/http/http_client.rb#L46) from the underlying http client's request call is [used to initialize the `MessageInstance` object returned from `@client.messages.create()`](https://github.com/twilio/twilio-ruby/blob/main/lib/twilio-ruby/rest/api/v2010/account/message.rb#L124).
