### ISSUE TITLE
feature request: MessageInstance.to_h

### ISSUE THREAD

**Issue by JohnnyMorbo** [twilio/twilio-ruby#525]
I would like a new method `MessageInstance.to_h` that emits a Hash object of the `@properties` attribute.

This would allow me to easily inspect the contents of the entire `@properties` without iterating over each attribute by name.

I think this should be a pretty simple code change (famous last words!), adding something like:
```ruby
class MessageInstance
  def to_h
    @properties
  end
end
```
This won't require any code maintenance in the future if, for instance, Twilio changes the API response upstream.  Just change the documentation to note what's now available in the hash.

**Comment by JohnnyMorbo** [comment]
Just a comment:
As I noted elsewhere, the `@properties` hash actually is available if you call `MessageInstance.get_instance_variable(:@properties)`
but this seems...uh..._bad_ to me.

I'm actually a ruby noob, so maybe I just don't understand how this stuff is supposed to work, but it seems to me that allowing access - even if it's just read access - to an arbitrary instance variable is undesirable.  Maybe unsafe in certain situations.
While the .get_instance_variable method is helpful during development and testing, may it should be disabled somehow for public/production code?

**Comment by eshanholtz** [comment]
Closing in favor of #524
