### ISSUE TITLE
Toll Free filter on incoming phone numbers is no longer working.

### ISSUE THREAD

**Issue by jstrouse** [twilio/twilio-ruby#527]
### Issue Summary
The list of toll-free incoming numbers is no longer working.  In order to figure out if a phone number is toll-free and appropriately charge for it, we were getting the list of toll-free numbers using to the toll_free filter on incoming phone numbers, but sometime in the last week that quit working.

### Steps to Reproduce
Run a list of toll free numbers and notice that it's the exact same list as the incoming phone numbers list

### Code Snippet
twilio_client = Twilio::REST::Client.new twilio_account_sid, twilio_auth_token
twilio_client.api.incoming_phone_numbers.list.count
=> 497
twilio_client.api.incoming_phone_numbers.toll_free.list.count
=> 497

### Technical details:
* twilio-ruby version: 5.33.0 and 5.39.2
* ruby version: 2.6.5

**Comment by eshanholtz** [comment]
Hi @jstrouse, this does not appear to be a library-specific bug. In order to properly debug this issue, please [file a support ticket](https://twilio.com/help/contact)
