### ISSUE TITLE
Using the new deactivation API returns a 307 response causing an "Unable to fetch record" exception

### ISSUE THREAD

**Issue by owaiswiz** [twilio/twilio-ruby#532]
### Issue Summary
When using the new deactivation API, an exception occurs with HTTP Error 307. A workaround for now is to catch the exception and get the redirect URL using the exception_object.response.

Similar to https://github.com/twilio/twilio-php/issues/655 and https://github.com/twilio/twilio-csharp/issues/534#issuecomment-676508898

### Steps to Reproduce
Fetch deactivated numbers list from the [official example](https://www.twilio.com/docs/sms/deactivated-phone-numbers?code-sample=code-fetching-deactivated-numbers-for-september-5th-2020&code-language=Ruby&code-sdk-version=5.x)

### Code Snippet
```ruby
your_twillio_client.messaging.deactivations.fetch(date: Date.new(2020, 9, 5));
```

### Exception/Log
```
Twilio::REST::RestError: [HTTP 307] 307 : Unable to fetch record
from /home/owaiswiz/.rvm/gems/ruby-2.6.6/gems/twilio-ruby-5.40.1/lib/twilio-ruby/framework/version.rb:72:in `fetch'
```

### Technical details:
* twilio-ruby version: 5.40.1
* ruby version: 2.6.6

**Comment by childish-sambino** [comment]
This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.
