### ISSUE TITLE
unable to send messages, InvalidURIError

### ISSUE THREAD

**Issue by jainankita90** [twilio/twilio-ruby#536]
### Issue Summary

Unable to send message using twilio-ruby gem. I am  getting invalid URL.
### Steps to Reproduce
I am doing this in rails env
1.edit Gemfile 
2. add gem twilio-ruby, 5.10.7
2. open rails console
3. run below code
### Code Snippet
```
 client = Twilio::REST::Client.new('SIDxxxxxxxxxxxxxxxxxxxxxx', 'tokenxxxxx', nil, nil)

  m = client.messages.create({
    from: '+1000000',
    to: '+111111111',
    body: 'trying to send sms'})

## Another way as per doc
client.api.account.messages.create(
  from: '+14159341234',
  to: '+16105557069',
  body: 'Hey there!'
)
```

### Exception/Log
```URI::InvalidURIError: bad URI(absolute but no path): api.twilio.com://
  from PATH/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/uri/common.rb:146:in `split'
  from PATH/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/uri/common.rb:211:in `parse'
  from PATH/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/uri/common.rb:747:in `parse'
  from PATH/.rvm/gems/ruby-2.1.2/gems/faraday-0.17.3/lib/faraday/connection.rb:454:in `proxy_from_env'
  from PATH/.rvm/gems/ruby-2.1.2/gems/faraday-0.17.3/lib/faraday/connection.rb:86:in `initialize'
  from PATH/.rvm/gems/ruby-2.1.2/gems/faraday-0.17.3/lib/faraday.rb:69:in `new'
  from PATH/.rvm/gems/ruby-2.1.2/gems/faraday-0.17.3/lib/faraday.rb:69:in `new'
  from PATH/.rvm/gems/ruby-2.1.2/gems/twilio-ruby-5.10.7/lib/twilio-ruby/http/http_client.rb:23:in `_request'
  from PATH/.rvm/gems/ruby-2.1.2/gems/twilio-ruby-5.10.7/lib/twilio-ruby/http/http_client.rb:56:in `request'
  from PATH/.rvm/gems/ruby-2.1.2/gems/twilio-ruby-5.10.7/lib/twilio-ruby/rest/client.rb:74:in `request'
  from PATH/.rvm/gems/ruby-2.1.2/gems/twilio-ruby-5.10.7/lib/twilio-ruby/framework/domain.rb:22:in `request'
  from PATH/.rvm/gems/ruby-2.1.2/gems/twilio-ruby-5.10.7/lib/twilio-ruby/framework/version.rb:53:in `request'
  from PATH/.rvm/gems/ruby-2.1.2/gems/twilio-ruby-5.10.7/lib/twilio-ruby/framework/version.rb:147:in `create'
  from PATH/.rvm/gems/ruby-2.1.2/gems/twilio-ruby-5.10.7/lib/twilio-ruby/rest/api/v2010/account/message.rb:115:in `create'
  from (irb):7
  from PATH/.rvm/gems/ruby-2.1.2/gems/railties-4.2.1/lib/rails/commands/console.rb:110:in `start'
  from PATH/.rvm/gems/ruby-2.1.2/gems/railties-4.2.1/lib/rails/commands/console.rb:9:in `start'
  from PATH/.rvm/gems/ruby-2.1.2/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:68:in `console'
  from PATH/.rvm/gems/ruby-2.1.2/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  from PATH/.rvm/gems/ruby-2.1.2/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
  from PATH/.rvm/gems/ruby-2.1.2/gems/railties-4.2.1/lib/rails/app_rails_loader.rb:45:in `require'
  from PATH/.rvm/gems/ruby-2.1.2/gems/railties-4.2.1/lib/rails/app_rails_loader.rb:45:in `block in exec_app_rails'
  from PATH/.rvm/gems/ruby-2.1.2/gems/railties-4.2.1/lib/rails/app_rails_loader.rb:34:in `loop'
  from PATH/.rvm/gems/ruby-2.1.2/gems/railties-4.2.1/lib/rails/app_rails_loader.rb:34:in `exec_app_rails'
  from PATH/.rvm/gems/ruby-2.1.2/gems/railties-4.2.1/lib/rails/cli.rb:5:in `<top (required)>'
  from PATH/.rvm/gems/ruby-2.1.2/gems/railties-4.2.1/bin/rails:9:in `require'
  from PATH/.rvm/gems/ruby-2.1.2/gems/railties-4.2.1/bin/rails:9:in `<top (required)>'
  from PATH/.rvm/gems/ruby-2.1.2/bin/rails:23:in `load'
  from PATH/.rvm/gems/ruby-2.1.2/bin/rails:23:in `<main>'
  from PATH/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:24:in `eval'
  from PATH/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:24:in 
```

### Technical details:
* twilio-ruby version:5.10.7 
* ruby version:2.1.2
* rails version 4.2.1

**Comment by philnash** [comment]
You are running quite an old version of the library there, the latest is 5.41.0. Can you update the version and try again?

**Comment by jainankita90** [comment]
> You are running quite an old version of the library there, the latest is 5.41.0. Can you update the version and try again?

@philnash  any version above > v5.10.7 doesnot support ruby 2.1.2. 
So I cannot use other versions. 

Is it possible to pass url  during initialize,
  **Twilio::REST::Client.new('SIDxxxxxxxxxxxxxxxxxxxxxx',** 'tokenxxxxx', nil, nil)

Thanks 
Ankita

**Comment by philnash** [comment]
That may be, but Ruby 2.1.2 is way out of support and potentially insecure: https://www.ruby-lang.org/en/downloads/. In fact Ruby 2.1.4 is over 6 years old.

It is not safe for you to be using such an old version of Ruby and you will be missing out on countless improvements to not only this gem, but many others you depend on.

That being said, I don't think this should be failing like this. Is there a reason you are passing `nil` as the last two arguments to the constructor? What if you only pass the first 2 arguments?

Are you using an API Key and secret or your Account Sid and Auth Token?

Is there anywhere else in your application that you use this library?

**Comment by jainankita90** [comment]
I do understand that and planning to upgrade after sometime. 
first four args of constructor are default nil [ref ](https://github.com/twilio/twilio-ruby/blob/513657df0835b8cb76c01eb7cf2dd30c571ecb95/lib/twilio-ruby/rest/client.rb#L18

Actually, I did tried with v5.41 and everything worked fine. But I am worried that it does not create any issue in future on production.

**Comment by childish-sambino** [comment]
Not sure what the issue was in the older version, but there's been lots of improvements and fixes over the past couple years. Only 3 known bugs in the latest version, if that eases your mind: https://github.com/twilio/twilio-ruby/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22type%3A+bug%22

**Comment by eshanholtz** [comment]
Closing as recommended course of action is to update ruby version.
