### ISSUE TITLE
Adding a newline to a text message

### ISSUE THREAD

**Issue by larryh** [twilio/twilio-ruby#54]
Hi,

First of all: thanks for the great gem - it makes our programming lives a lot easier!

I am trying to insert a newline into my text message as per the instructions at http://www.twilio.com/help/faq/sms/how-do-i-add-a-line-break-in-my-sms-message , however, when I insert  '%0a' into the body of my message it comes out as exactly that as opposed to generating a new line, e.g. "This is line 1%0aThis is line 2".

I'm wondering if somehow special characters are getting escaped and are appearing intact in the final message (like Rails does for special characters in HTML).

Is that what is happening or am I doing something wrong? Is there a way to get newlines into a text message using your gem?

Thanks,
Larry

**Comment by edorgeville** [comment]
Thanks @larryh, 4 years later! 👍

**Comment by myfitment** [comment]
This doesn't work if you are using views with Textris, unfortunately.
