### ISSUE TITLE
Is there any method to check if room exists?

### ISSUE THREAD

**Issue by panSarin** [twilio/twilio-ruby#540]
Do we have something that would look like:

``` client.video.rooms.exists?(room_name) ```

or we have to handle it by 

```
      begin
         room = client.video.rooms(room_name).fetch
      rescue Twilio::REST::RestError => e # Unable to fetch record
         client.video.rooms.create(unique_name: room_name)
      end
```

if we want to add room? 

And if no - should I create PR, or we don't want to add this kind of logic since we can handle error by rescue'ing it?

**Comment by eshanholtz** [comment]
There is no `exists?` method to check if a room exists. The error handling logic you laid out is the preferred method, since we want to make each API call explicit. I recommend writing a helper function for yourself if you use this logic often.

**Comment by panSarin** [comment]
Thanks for reply.

That makes sense, it would also probably makes sense if Twilio would have endpoint to check if room existis but since it doesn't I will stick to current approach. I am closing that one!
