### ISSUE TITLE
JSON format in response

### ISSUE THREAD

**Issue by alexborovkov** [twilio/twilio-ruby#543]
As I see it is possible to return JSON from twilio api endpoint

https://www.twilio.com/docs/usage/troubleshooting/data-types

For example I want to retrieve all messages from channel in JSON format, but this method return XML representation

```@client.chat.services(service_sid).channels(params[:channelSid]).messages.list```

Is it possible to return JSON using this gem?

**Comment by eshanholtz** [comment]
@alexborovkov What version of twilio-ruby are you using?
