### ISSUE TITLE
Question: How to create a conversation under a specific Conversations Service

### ISSUE THREAD

**Issue by gnumarcelo** [twilio/twilio-ruby#549]
### Issue Summary
According to the [Api reference](https://www.twilio.com/docs/conversations/api/service-resource), a Conversation Service is the top-level container for other resources in the Twilio Conversations REST API and can be used to create multiple, distinct environments (such as dev, stage, and prod) under a single Twilio account.
I've set multiples Conversations Services, but whenever I create Conversation on the backend it is aways created under the *default* Conversation Service [set in the configurations](https://www.twilio.com/console/conversations/configuration/defaults).

Is there a way to provide the Conversation Service Sid somewhere in the api so that I could scope my resources fetch/create under that Conversation Service?

**Comment by shwetha-manvinkurke** [comment]
@gnumarcelo This doesn't look like a helper library issue to me. Please reach out to support at [support.twilio.com](https://support.twilio.com/) for help.
