### ISSUE TITLE
Autopilot macro incorrectly sets attribute names?

### ISSUE THREAD

**Issue by ni3t** [twilio/twilio-ruby#552]
### Issue Summary
When connecting a call to Autopilot, using this example code to call a customer, make an introduction, then redirect to an autopilot action to handle customer input, I get an error in the twilio console.

```rb
TWILIO_CLIENT = ::Twilio::REST::Client.new(<secrets>)

twiml = 
  Twilio::TwiML::VoiceResponse.new
    .say("Hello")
    .connect do |c|
      c.autopilot(
        "<app SID>",
        target_task: "some_task"
      )
    end

call_params = { 
  to: <example>
  from: <our number>
  twiml: twiml
}

TWILIO_CLIENT.api.calls.create(call_params)
```

the error in the console is this: 

Msg | "XML Validation warning"
line | "4"
parserMessage | " Attribute 'targetTask' is not allowed to appear in element 'Autopilot'."
ErrorCode | "12200"
cols | "78"
url | ""
LogLevel | "WARN"

My guess is this is due to the code here: https://github.com/twilio/twilio-ruby/blob/7e218c44288b8a0954e141dfc5c8e99b5f63ffa6/lib/twilio-ruby/twiml/twiml.rb#L44

it looks like the keyword args are automatically lowerCamelCased, which is causing the keyword arg `target_task` to be passed along as `targetTask`, instead of the expected `TargetTask`. 

If I construct the relevant TwiML by hand and pass the attr in as `TargetTask` i get the expected behavior. 

### Technical details:
* twilio-ruby version: 5.51.0
* ruby version: 2.7.3

**Comment by ni3t** [comment]
I am happy to make a contribution to sidestep the lowerCamelCase step if the argument is `target_task`.

**Comment by thinkingserious** [comment]
Hello @ni3t,

Thank you for the detailed report and associated PR! We have your PR on our backlog for review.

**Comment by eshanholtz** [comment]
This requires a fix from a product team. Internal tracking ID: UN-2070
