### ISSUE TITLE
[Support] No way to fetch sms message/delivery attempts that is sent by a notification request

### ISSUE THREAD

**Issue by silverscrub** [twilio/twilio-ruby#557]
### Issue Summary
Hello,
I am looking for ways to fetch sms delivery attempts by a notification request the same way that we can do it in the console at the moment. The reason is that, in my app,
1.  A notification has_many :sms_messages, and each sms_message has a sid attributes to match with Twilio's database for tracking status and synchronization.
2. When a notification request is sending multiple sms messages out, I also need to create the sms_message record in the database for further tracking (delivery_url_callback), but a NotificationInstance currently has no way to tell me the message sids of its attempts.

I have tried looking over a lot of Twilio's documentation + this repo source code, but no function(?) has offered this capabilities

After some inspection on web console, by requesting json format to this link
```
https://www.twilio.com/console/notify/services/#{notify_service_sid}/logs/#{notification_sid}/deliveries
```
it gives out the list of delivery attempts along with the provider_message_id/SmsSid that I need for creating sms_message records in my own database.

### Current work-around strategy (not working)
I am trying to use Twilio::REST::Client to request to the link above by
```
@client = Twilio::REST::Client.new(account_sid, auth_token)
@client.request(
  'https://twilio.com',
  443,
  'GET',
  'https://www.twilio.com/console/notify/services/#{notify_service_sid}/logs/#{notification_sid}/deliveries'
)
```
What I don't understand is the response returning 302 FOUND and giving a redirect url to login page even though I have provided the account_sid and auth_token in the client.

###Question

Is there any supported way to fetch the message delivery attempt by a notification request? If none, what would be a suitable workaround in this case?

Many thanks!

### Technical details:
* twilio-ruby version: 5.51.0
* ruby version: 2.6.3

**Comment by thinkingserious** [comment]
Hello @silverscrub,

Thank you for taking the time to report this issue!

Does [this resource](https://www.twilio.com/docs/notify/api/service-resource?code-sample=code-create-a-service-resource&code-language=Node.js&code-sdk-version=3.x#fetch-a-service-resource) contain the information you need?

With best regards,

Elmer

**Comment by silverscrub** [comment]
Hi Elmer,
Unfortunately, I haven't seen any information in that specific resource that would allow me to fetch the delivery attempts of a certain notification. Seems like there are no such api request to retrieve such information.

However, in the mean time, I figured out a workaround which is to use the custom delivery callbacks when sending out a notification request. 

```
    @client.notify.services(notify_service_sid).notifications.create(
      to_binding: sms_binding_details),
      body: 'some content',
      sms: {
        status_callback: "#{ENV.fetch("MY_API_URL")}/api/url?notification_id=#{created_notification.id}"
      }
    )
```

Then, the data from returned sms status sending to this url would allow me to match the sms message to the notification instance.
