### ISSUE TITLE
Class `Autopilot` has multiple different ancestors

### ISSUE THREAD

**Issue by hlascelles** [twilio/twilio-ruby#560]
### Issue Summary
Depending on how you require the gem (or parts of it) you can cause an error as some classes have different ancestor chains.

### Steps to Reproduce
1. Use gem `5.56.0` (for example)
2. ```
    require "twilio-ruby"
    require "twilio-ruby/rest/autopilot"
    ```
3. See error:
    ```
    twilio-ruby-5.56.0/lib/twilio-ruby/rest/autopilot/v1/assistant.rb:13:in `<module:REST>': 
          superclass mismatch for class Autopilot (TypeError)
    ```

### Technical details:
* twilio-ruby version: `5.56.0`
* ruby version: Any

### Cause

This line declares Autopilot with no ancestors: https://github.com/twilio/twilio-ruby/blob/7e218c44288b8a0954e141dfc5c8e99b5f63ffa6/lib/twilio-ruby/rest/autopilot/v1.rb#L11
This line declares Autopilot with ancestor `Domain`: https://github.com/twilio/twilio-ruby/blob/7e218c44288b8a0954e141dfc5c8e99b5f63ffa6/lib/twilio-ruby/rest/autopilot.rb#L11

Is this a bug in the code generator?

**Comment by hlascelles** [comment]
Possibly related: https://github.com/twilio/twilio-ruby/pull/558

**Comment by hlascelles** [comment]
Confirmed `5.55.0` works fine.

**Comment by thinkingserious** [comment]
Thank you for reporting this @hlascelles! 

I was able to reproduce this issue locally.

This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

With best regards,

Elmer

**Comment by kridai** [comment]
This is issue is fixed now.
