### ISSUE TITLE
Creating a Flex Web Channel returns 404.

### ISSUE THREAD

**Issue by josh08h** [twilio/twilio-ruby#564]
### Issue Summary
Creating a Flex Web Channel returns 404.

### Steps to Reproduce
1. Create a web_channel via the Ruby SDK
2. See below code snippet

### Code Snippet
```ruby
client.flex_api.web_channel.create(
  flex_flow_sid: 'FOxxxxxxxxxxxxxx',
  identity: 'QgS4UHiBukm6TYrVjUf6uU',
  customer_friendly_name: 'Mrs Test User',
  chat_friendly_name: 'Flex WebChat'
)

```

### Exception/Log
```
twilio-ruby-5.57.0/lib/twilio-ruby/framework/rest/version.rb:146:in `create': [HTTP 404] 20404 : Unable to create record (Twilio::REST::RestError)
The requested resource /WebChannels was not found
https://www.twilio.com/docs/errors/20404
```

### Technical details:
* twilio-ruby version: 5.57.0
* ruby version: 2.7.4

**Comment by JenniferMah** [comment]
Hi @josh08h!
It looks like you are missing the version in your code snippet. It should be `client.flex_api.v1.web_channel.create` with the `v1` between `flex_api` and `web_channel`. It should look similar to the syntax used on [this line](https://github.com/twilio/twilio-ruby/blob/7e218c44288b8a0954e141dfc5c8e99b5f63ffa6/spec/integration/flex_api/v1/web_channel_spec.rb#L153) of the integration test.

**Comment by josh08h** [comment]
Ah yes! Thanks a lot @JenniferMah

**Comment by JenniferMah** [comment]
No problem! Please feel free open a new issue if you run into another problem in the twilio-ruby library.

**Comment by shwetha-manvinkurke** [comment]
@josh08h have you tried curl-ing the request and see if it goes through ok?

**Comment by josh08h** [comment]
@shwetha-manvinkurke ah.. I see the same error with curl (httpie) too:

```
http -a AC1b0e45327716d4beccd48d02e473d99b:$(bpass next passwords/twilio/auth_token) --form POST https://flex-api.twilio.com/v1/WebChannels FlexFlowSid="FO8a6d3b526d9e97a3fdae2e38e50ef843" ChatFriendlyName="Flex Test" CustomerFriendlyName="Josh Test" Identity=$(openssl rand -hex 12)
HTTP/1.1 404 Not Found
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since
Access-Control-Allow-Methods: GET, POST, DELETE, OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: ETag
Connection: keep-alive
Content-Length: 151
Content-Type: application/json
Date: Thu, 05 Aug 2021 09:05:30 GMT
Strict-Transport-Security: max-age=31536000
Twilio-Request-Duration: 0.033
Twilio-Request-Id: RQ012592277d1bf0977a300615f5e3fc61
X-API-Domain: flex-api.twilio.com
X-Home-Region: us1
X-Powered-By: AT-5000
X-Shenanigans: none

{
    "code": 20404,
    "message": "The requested resource /WebChannels was not found",
    "more_info": "https://www.twilio.com/docs/errors/20404",
    "status": 404
}
```

Should I raise this with Twilio support instead?

**Comment by shwetha-manvinkurke** [comment]
@josh08h This points to an error in your flex setup. I recommend you reach out to support or read our [docs](https://www.twilio.com/docs/flex) for more info.
