### ISSUE TITLE
Please cut a release to fix Faraday warning

### ISSUE THREAD

**Issue by johnnyshields** [twilio/twilio-ruby#570]
Hi, looks like the fix for the Faraday warning is on master. Can you please cut a gem release to fix it?

**Comment by JenniferMah** [comment]
Hi @johnnyshields,
Version `5.58.2` of the twilio-ruby library should include the fix for the deprecation warning on Faraday.

**Comment by johnnyshields** [comment]
@JenniferMah thank you!
