### ISSUE TITLE
Getting an error trying to send an SMS with a client configured with more than the default # of retries

### ISSUE THREAD

**Issue by samuel-henry** [twilio/twilio-ruby#585]
### Issue Summary
Getting an error trying to send an SMS with a client configured with more than the default # of retries

### Steps to Reproduce
1. Create client with retry_limit option passed in
2. Send an SMS

### Code Snippet
```ruby
twilio_client_options = {
    retry_limit: 3,
}
client = Twilio::REST::Client.new(account_sid, auth_token, twilio_client_options) 
client.messages.create(
            body: 'Foo',  # a well-formed message that works without passing in the twilio_client_options param
            messaging_service_sid: TWILIO_MESSAGING_SERVICE_ID,      # my service id
            to: '+1234567890' # dummy phone number for this issue
        ) 
```

### Exception/Log
```
"bad URI(is not URI?): \"https://api.twilio.com/2010-04-01/Accounts/{:retry_limit=>3}/Messages.json\""
--


<br class="Apple-interchange-newline">
```

### Technical details:
* twilio-ruby version: 5.48.0
* ruby version: Ruby 2.7 (on AWS Lambda)

**Comment by eshanholtz** [comment]
Hi @samuel-henry,

Where are you seeing a `retry_limit` parameter? I don't believe this is a supported client option by default, and you will likely need to [define and pass a custom HTTP client](https://www.twilio.com/docs/libraries/ruby/custom-http-clients?code-sample=code-custom-http-client-for-ruby&code-language=Ruby&code-sdk-version=default) that has your desired retry limit configured.

**Comment by samuel-henry** [comment]
Hi Elise,

I saw it on https://www.rubydoc.info/gems/twilio-ruby/3.10.1/Twilio/REST/Client

We see that it's set to 1 by default:

`
API_VERSION =
'2010-04-01'
HTTP_HEADERS =
{
  'Accept' => 'application/json',
  'Accept-Charset' => 'utf-8',
  'User-Agent' => "twilio-ruby/#{Twilio::VERSION}",
}
DEFAULTS =
{
  :host => 'api.twilio.com',
  :port => 443,
  :use_ssl => true,
  :ssl_verify_peer => true,
  :ssl_ca_file => File.dirname(__FILE__) + '/../../../conf/cacert.pem',
  :timeout => 30,
  :proxy_addr => nil,
  :proxy_port => nil,
  :proxy_user => nil,
  :proxy_pass => nil,
  :retry_limit => 1,
}
`

But that you can pass in an option to override the default (https://www.rubydoc.info/gems/twilio-ruby/3.10.1/Twilio/REST/Client#initialize-instance_method): 

`
:retry_limit => 1
`
"The number of times to retry a request that has failed before throwing an exception. Defaults to one."

Thank you for the link regarding a custom HTTP client

Thank you,
Sam

**Comment by samuel-henry** [comment]
Hi Elise,

Just checking back on this. 

Thank you!
Sam

**Comment by samuel-henry** [comment]
Ah, thank you Elise

I'll close this out but can you please pass along the feature request or +1 the existing backlog item to re-add this option to make it simple to configure retry strategy without having to define a custom client?

Thank you
Sam
