### ISSUE TITLE
Twillio sms special character automatically changed of @ and _ converting into ? in sms

### ISSUE THREAD

**Issue by visionsIT** [twilio/twilio-ruby#609]
Twillio sms special character automatically changed of @ and _ converting into ? in sms

Please check below attached screenshots, first screen showing response of the sent message and second screen showing the actual SMS received in the mobile @ and _ sign converted to the ?

Is there anyone facing this type of issue with Twilio please guide me. Thanks in advance.

![image](https://user-images.githubusercontent.com/29791900/173538931-c0e08fd5-8e23-4fba-88fe-09d879d63a95.png)
![image](https://user-images.githubusercontent.com/29791900/173539085-c0dc6ced-e8e7-4f9a-b0d4-f1021d055769.png)

**Comment by rakatyal** [comment]
@visionsIT: Character encoding issues tend to be related to how the carrier networks handle special characters (GSM vs. Unicode), not the Twilio helper libraries themselves. The solution is also not universal and cannot be implemented in the libraries themselves.

I recommend you reach out to our support team to fully investigate this issue:
https://www.twilio.com/console/support/tickets/create

When submitting the ticket, please provide a couple recent Message SIDs so they can investigate immediately.

A Message SID is a 34-digit unique identifier that starts with "SM" or "MM". You can find the Message SIDs in your account's message log: https://www.twilio.com/console/sms/logs
