### ISSUE TITLE
Failed to open TCP connection - Temporary failure in name resolution

### ISSUE THREAD

**Issue by lusa** [twilio/twilio-ruby#618]
### Issue Summary
Today we saw > 15 instances of this error on connecting to the API: `Failed to open TCP connection to api.twilio.com:443 (getaddrinfo: Temporary failure in name resolution)`. Was this a result of outages on Twilio's end, or possibly a result of our gem version? Just looking to see if anyone has insight on this. 

### Steps to Reproduce
Happens intermittently - cannot reproduce. 

### Technical details:
* twilio-ruby version: 5.58.2
* ruby version: 3.1.1

**Comment by claudiachua** [comment]
Hi @lusa, could you provide more details, code samples for what you're trying to accomplish? And if error above is still occurring?

**Comment by lusa** [comment]
error no longer appears.
