### ISSUE TITLE
Problem sending messages longer than 160 characters when using this gem

### ISSUE THREAD

**Issue by iRonin** [twilio/twilio-ruby#62]
I've got problem sending messages longer than 160 characters when using this gem. The response I get is:

```
{"status"=>400,
 "message"=>"The message body exceeds the 160 character limit.",
 "code"=>21605,
 "more_info"=>"http://www.twilio.com/docs/errors/21605"}
```

However error 21605 says that a message cannot be longer than 1600 characters.
I can send long SMSes just fine using curl.
Any ideas?

**Comment by mbellamk** [comment]
Hello, I am facing the same issue but In Java. And I am using com.twilio.sdk.resource.factory.SmsFactory. Could you guide me which class I should use in case of Java?

**Comment by dougblack** [comment]
Hi @mbellamk, you'll want to use `com.twilio.sdk.resource.factory.MessageFactory` if you want to send messages longer that 160 characters.

**Comment by mbellamk** [comment]
Thanks doug. It worked.
