### ISSUE TITLE
authy-devise Replacement

### ISSUE THREAD

**Issue by IsmailM** [twilio/twilio-ruby#620]
Adding this Issue here as I cannot add the issue to the original repo - [Authy-devise](https://github.com/twilio/authy-devise) - as the Github repo has now been archived.

I wanted some clarification on the depreciation message in the readme in the Authy-devise Repo.

* The message says support ends on 1st November 22 - Is this just referring the customer support? I.e. will the current Authy services + setup continue to work without any changes?
  * The message says that they will start to deprecate the service for SMS/Voice after this date - what does this mean? Will end-users see a depreciation message or just on the server etc.
  * Essentially I am wondering when is the latest we need to move over by?
* The readme refers to a new Devise plugin for Twilio Verify in the works - any update on this?

**Comment by Hunga1** [comment]
The Authy API is being deprecated and replaced with the Twilio Verify API and support will end on November 1st, 2022. Here is a link to the migration guide from Authy to Verify that is mentioned in the README.

https://www.twilio.com/blog/migrate-authy-to-verify

For any other questions, please [file a support ticket](https://twilio.com/help/contact)
