### ISSUE TITLE
WhatsApp call to action button with Dynamic URL suffix

### ISSUE THREAD

**Issue by mahkhaledm** [twilio/twilio-ruby#624]
WhatsApp business platform allows to send a message with interactive call of action buttons with dynamic URL suffix.
https://developers.facebook.com/docs/whatsapp/api/messages/message-templates/interactive-message-templates

I created a template in whatsApp template with a dynamic URL but can't pass this suffix variable using Twilio-ruby gem.

**Comment by rakatyal** [comment]
Hi @mahkhaledm, this should be supported. Have you tried [these instructions](https://www.twilio.com/docs/whatsapp/buttons#creating-templates-with-buttons)? There is also a [support article](https://support.twilio.com/hc/en-us/articles/4402292727451-Can-I-send-buttons-in-my-WhatsApp-messages-) with some FAQs on this topic. Please let us know if this doesn't work for you.

**Comment by mahkhaledm** [comment]
yes, this is OK for *static* URL type. But WhatsApp supports *dynamic* URL type where you can pass a variable to personalize this button URL
https://business.facebook.com/business/help/2055875911147364?id=2129163877102343
<img width="1153" alt="Screenshot 2022-12-12 at 10 38 38 PM" src="https://user-images.githubusercontent.com/19334497/207150098-c2fcf2ed-3b65-45c5-ba6c-7bcd393695f1.png">

**Comment by rakatyal** [comment]
I see. I don't think Twilio supports creating dynamic url for buttons. This is what I see in my console

![image](https://user-images.githubusercontent.com/12533467/207157587-37806d84-fca5-4b66-9c0d-f144a80da1e6.png)

How were you able to create a dynamic URL template?

**Comment by mahkhaledm** [comment]
Yes, it seems Twilio interface doesn't support it yet. I created it from WhatsApp templates directly.

**Comment by rakatyal** [comment]
Yes. This is outside the scope of the helper libraries. In order to properly track this feature request, please [file a support ticket](https://twilio.com/help/contact).
