### ISSUE TITLE
Maximum allowed jwt version (2.5) is outdated

### ISSUE THREAD

**Issue by MarcPer** [twilio/twilio-ruby#625]
### Issue Summary

A new version of JWT was released ([2.6.0](https://github.com/jwt/ruby-jwt/releases/tag/v2.6.0)), but twilio-ruby requires it to be <= 2.5.

According to JWT's changelog, the new version only adds features. I've ran existing integration tests from my codebase, and twilio-ruby's own tests, using twilio-ruby 3.11.6 together with jwt 2.6.0, and they all passed.

### Technical details:
* twilio-ruby version: 3.11.6
* ruby version: 3.1.2

**Comment by Hunga1** [comment]
This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog (internal ref: DI-2507).
