### ISSUE TITLE
Really no devise-authy replacement library?

### ISSUE THREAD

**Issue by MGPalmer** [twilio/twilio-ruby#656]
Hello!
https://github.com/twilio/authy-devise has promised for a long time that "Coming soon: Look out for a new Devise plugin to use Twilio Verify with Devise". However I can't find any replacement library, one that connects the new API with Devise. Are there still plans to provide one in time for the July deadline?

We just need simple TOTP, with SMS fallback, and a nice-to-have would be Yubikey integration, and that with minimal custom code. authy-devise was great for that and frankly without it we see no reason to use a Twilio product at all.

Could someone provide clarity on what the way forward would be here? Thanks!

**Comment by MGPalmer** [comment]
Slight correction: I learned that SMS is considered too insecure now and that for hardware-based 2FA WebAuthn seems to be the way forward, but still it seems like there is nothing out there that is as easy to use as authy-devise was :smiling_face_with_tear:

**Comment by shrutiburman** [comment]
Hi @MGPalmer , 
Will check with the team internally and come back to you.

**Comment by MGPalmer** [comment]
@shrutiburman Hey, that would be great, thank you!

**Comment by MGPalmer** [comment]
@shrutiburman For what it's worth, we implemented our own TOTP solution now, feel free to close this from my end :)

**Comment by shrutiburman** [comment]
That's great. As you can see the authy repository has been archived and the active support was extended till July 2023, this was not in the priority items for the team, as of now.
Feel free to open up a PR for the feature, if you want to.
