### ISSUE TITLE
Sync not working since version 7.1.0

### ISSUE THREAD

**Issue by taka0125** [twilio/twilio-ruby#722]
### Issue Summary
Since version 7.1.0, sync functionality has stopped working. The `service_sid` and `map_sid` are no longer passed in the `sync_maps` section, causing the following code to fail:

### Steps to Reproduce
1. Initialize the Twilio client with `ACCOUNT_SID` and `AUTH_TOKEN`.
2. Retrieve the sync service using `service_sid`.
3. Attempt to create a sync map item with `key`, `data`, and `ttl`.

### Code Snippet
```ruby
client = Twilio::REST::Client.new(ACCOUNT_SID, AUTH_TOKEN)
sync_service = client.sync.v1.services(service_sid)

sync_service
  .sync_maps(collection_name)
  .sync_map_items
  .create(
    key: key,
    data: data,
    ttl: ttl
  )
```

### Exception/Log
```
`add': [HTTP 404] 20404 : Unable to create record (Twilio::REST::RestError)
The requested resource /Services//Maps//Items was not found
https://www.twilio.com/docs/errors/20404
```

### Technical details:
* twilio-ruby version: 7.1.1
* ruby version:3.2.1

**Comment by AxelTheGerman** [comment]
Noticed the same in `7.1.0` and `7.2.0`.

As far as I can tell the code is all auto generated by OpenAPI so the bug is probably in the corresponding API docs?

**Comment by taka0125** [comment]
Thank you. I'll reach out to Twilio Support and see what they say.
