### ISSUE TITLE
Newlines in SMS not working

### ISSUE THREAD

**Issue by findchris** [twilio/twilio-ruby#76]
Per [this page](https://www.twilio.com/help/faq/sms/how-do-i-add-a-line-break-in-my-sms-message), the client libraries (including this one) should automatically handle newlines in SMS messages.  I am not seeing this correct behavior in `gem 'twilio-ruby', tag: '3.11.0'`.

What I'd expect to work:

``` ruby
Twilio::TwiML::Response.new do |r|
  r.Message "Do\nnewlines\nwork?\nNope."
end
```

Any insight?  Cheers.

**Comment by rbucks** [comment]
I just updated this library from 5.4.2 to 5.6.4 and the newlines have disappeared again. Any help would be wonderful! 

Here's my code. message_body is a double-quoted string containing \n, like "Are you happy?\n\n0 - Yes\n1 - No". 

`def response
      response = Twilio::TwiML::MessagingResponse.new
      message = Twilio::TwiML::Message.new
      body = Twilio::TwiML::Body.new(message_body)

      response.append(message)
      message.append(body)

      response.to_s
    end`
