### ISSUE TITLE
UTF-8

### ISSUE THREAD

**Issue by swiftslipper** [twilio/twilio-ruby#80]
So I'm trying to send "Café" via client.sms.messages.create

I've tried various methods to no avail, the messages arrive as "Caf?".

http://www.twilio.com/engineering/2012/11/08/adventures-in-unicode-sms

**Comment by waits** [comment]
This is an issue for me now. Could be breaking between this gem and the Twilio API. I'm testing on an iPhone 6 (Verizon), which of course receives Unicode messages fine, unless they're coming from Twilio. The response returned by client.account.messages.create is correct, though. I'm stumped.
